feat(core): added helmet in sequence when helmet config is present
sourcefuse/loopback4-microservice-catalog pull request #101
Opened 2020-12-10 10:33 UTC by sf-kansara

RPMS-1734

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-10 13:38 UTC, samarpan-b requested changes

2020-12-10 13:38 UTC, samarpan-b commented on packages/core/src/secure-sequence.ts
> +      if (this.rateLimitConfig) {
have u tested this? pls test using sandbox app in sandbox folder.

2020-12-16 14:44 UTC, sf-kansara commented on packages/core/src/secure-sequence.ts
> +      if (this.rateLimitConfig) {
Added tests in sandbox

2020-12-18 08:17 UTC, samarpan-b approved these changes

2020-12-18 08:18 UTC, merged