feat(authentication-service): add asymmetric login in authentication …
sourcefuse/loopback4-microservice-catalog pull request #1011
Opened 2022-09-07 12:41 UTC by Surbhi-sharma1

…service

1007

## Description
Added asymmetric login in authentication service.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-17 13:04 UTC, akshatdubeysf requested changes

2022-09-17 13:04 UTC, akshatdubeysf commented on packages/core/src/components/bearer-verifier/providers/services-bearer-asym-token-verifier.ts
> +import moment from 'moment-timezone';
You should have two verifier providers like this, one symmetric and one asymmetric

2022-09-17 13:04 UTC, akshatdubeysf commented on services/authentication-service/src/component.ts
> +        AsymmetricAuthCodeGeneratorProvider;
Do not mix code generator with token provider, be consistent with the naming

2022-09-17 13:04 UTC, akshatdubeysf commented on services/authentication-service/src/component.ts
> +        LoginTokenProvider;
This one should be named symmetric token provider

2022-09-17 13:04 UTC, akshatdubeysf commented on services/authentication-service/src/providers/auth-asymmetric-code-provider.ts
> +      const keyValue = fs.readFileSync(process.env.JWT_PRIVATE_KEY ?? '');
This should use just the jwt Token provider, depending on the binding

2022-09-19 05:37 UTC, Surbhi-sharma1 commented on packages/cli/README.md
> +@sourceloop/cli/2.4.1 linux-x64 node-v16.16.0
ok sir

2022-09-19 05:37 UTC, Surbhi-sharma1 commented on packages/core/src/components/bearer-verifier/providers/services-bearer-asym-token-verifier.ts
> +import moment from 'moment-timezone';
yes sir ,I have provided both ,this one is for asymmetric

2022-10-03 11:08 UTC, Surbhi-sharma1 commented on services/authentication-service/src/component.ts
> +        AsymmetricAuthCodeGeneratorProvider;
ok sir

2022-10-03 11:08 UTC, Surbhi-sharma1 commented on services/authentication-service/src/component.ts
> +        LoginTokenProvider;
done

2022-10-03 11:08 UTC, Surbhi-sharma1 commented on services/authentication-service/src/providers/auth-asymmetric-code-provider.ts
> +      const keyValue = fs.readFileSync(process.env.JWT_PRIVATE_KEY ?? '');
done

2022-10-16 09:51 UTC, akshatdubeysf requested changes

2022-10-16 09:51 UTC, akshatdubeysf commented on packages/core/src/components/bearer-verifier/component.ts
> +          BearerAsymmetricTokenVerifyProvider;
Keep the name consistent

2022-10-16 09:51 UTC, akshatdubeysf commented on packages/core/src/components/bearer-verifier/providers/services-bearer-asym-token-verifier.ts
> +        const publicKey = fs.readFileSync(process.env.JWT_PUBLIC_KEY ?? '');
use async await

2022-10-16 09:51 UTC, akshatdubeysf commented on services/authentication-service/src/component.ts
> +    if (process.env.JWT_PUBLIC_KEY && process.env.JWT_PUBLIC_KEY !== '') {
keep this binding in the same condition as above na?

2022-10-16 09:51 UTC, akshatdubeysf commented on services/authentication-service/src/providers/jwt--asymmetric-signer.provider.ts
> +      const accessToken = jwt.sign(JSON.parse(data), clientSecret, {
is the parse required here?

2022-10-16 09:51 UTC, akshatdubeysf commented on services/notification-service/openapi.md
> +notification microservice
why all the other services are changed?

2022-10-16 10:54 UTC, Surbhi-sharma1 commented on packages/core/src/components/bearer-verifier/component.ts
> +          BearerAsymmetricTokenVerifyProvider;
It was giving sonar code smell (length greater than 100).

2022-10-16 10:54 UTC, Surbhi-sharma1 commented on services/authentication-service/src/providers/jwt--asymmetric-signer.provider.ts
> +      const accessToken = jwt.sign(JSON.parse(data), clientSecret, {
yes Sir ,it is required to parse the data here

2022-10-17 11:04 UTC, Surbhi-sharma1 commented on services/notification-service/openapi.md
> +notification microservice
changes done

2022-10-17 11:05 UTC, Surbhi-sharma1 commented on services/authentication-service/src/component.ts
> +    if (process.env.JWT_PUBLIC_KEY && process.env.JWT_PUBLIC_KEY !== '') {
done

2022-10-31 05:52 UTC, akshatdubeysf requested changes

2022-10-31 05:52 UTC, akshatdubeysf commented on services/authentication-service/src/providers/auth-code-generator.provider.ts
> +          client.secret,
But the signed doesn't take third parameter na?

2022-10-31 05:52 UTC, akshatdubeysf commented on services/authentication-service/src/providers/jwt--asymmetric-signer.provider.ts
> +      const clientSecret = await fs.readFile(process.env.JWT_PRIVATE_KEY ?? '');
This one doesn't take clientSecret?

2022-11-09 08:18 UTC, merged