fix(cli): Include the update of loopback packages via sourceloop cli
sourcefuse/loopback4-microservice-catalog pull request #1024
Opened 2022-09-19 06:19 UTC by yeshamavani

gh-1023

## Description

Include the update of loopback packages via sourceloop cli
=> Currently the sourceloop cli makes a super call to loopback cli for update and then updates the sourceloop packages.
=> Now we will directly update loopback and sourceloop packages simultaneously.

Fixes #1023

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-19 06:22 UTC, akshatdubeysf requested changes

2022-09-19 06:22 UTC, akshatdubeysf commented on packages/cli/src/generators/update/index.ts
> +    fs.writeFileSync(
We should show the user which deps will be replaced. This log should be shown once before any services' json is changed

2022-09-22 11:18 UTC, yeshamavani commented on packages/cli/src/generators/update/index.ts
> +    fs.writeFileSync(
we show the list using _printDepsToUpdate()

2022-09-23 09:51 UTC, akshatdubeysf approved these changes

2022-09-23 13:45 UTC, merged