fix(cli): DB pooling and obf fix in cli
sourcefuse/loopback4-microservice-catalog pull request #1025
Opened 2022-09-19 07:43 UTC by AnkurBansalSF

## Description

Fixed :
- OBF was not working in services created using cli.
- loopback-coonector-kv-redis was not installed automatically.
- added connection pooling for postgres datasource.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-09-26 05:40 UTC, akshatdubeysf requested changes

2022-09-26 05:40 UTC, akshatdubeysf commented on packages/cli/src/generators/microservice/index.ts
> +      scripts['prestart'] = 'npm run clean && npm run openapi-spec';
Why is this changed?

2022-09-26 05:40 UTC, akshatdubeysf commented on packages/cli/src/generators/microservice/index.ts
> +        {
Why not use same store for ratelimiting?

2022-09-26 05:40 UTC, akshatdubeysf commented on packages/cli/src/generators/microservice/templates/src/application.ts.ejs
> +      keyGenerator: rateLimitKeyGen,
Should use a better keygen as this one has some issues with the request IP.

2022-09-26 06:29 UTC, AnkurBansalSF commented on packages/cli/src/generators/microservice/index.ts
> +      scripts['prestart'] = 'npm run clean && npm run openapi-spec';
"rebuild": "npm run clean && npm run build",
"preopenapi-spec": "npm run build",
build was executed twice, so I changed it to clean

2022-09-26 06:36 UTC, akshatdubeysf commented on packages/cli/src/generators/microservice/index.ts
> +      scripts['prestart'] = 'npm run clean && npm run openapi-spec';
oh ok

2022-09-27 08:14 UTC, AnkurBansalSF commented on packages/cli/src/generators/microservice/templates/src/application.ts.ejs
> +      keyGenerator: rateLimitKeyGen,
Will have to change it in core

2022-09-27 08:14 UTC, AnkurBansalSF commented on packages/cli/src/generators/microservice/index.ts
> +        {
Done

2022-09-27 09:01 UTC, akshatdubeysf approved these changes

2022-09-27 11:23 UTC, yeshamavani approved these changes

2022-09-27 11:59 UTC, merged