chore(deps): loopback version update in services and packages
sourcefuse/loopback4-microservice-catalog pull request #1086
Opened 2022-11-17 08:05 UTC by AnkurBansalSF

## Description

loopback version update in services and packages.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-11-17 08:21 UTC, samarpan-b requested changes

2022-11-17 08:21 UTC, samarpan-b commented on packages/core/package.json
> -  "name": "@sourceloop/core",
fix indentation

2022-11-17 09:00 UTC, AnkurBansalSF commented on packages/core/package.json
> -  "name": "@sourceloop/core",
Done

2022-11-22 11:12 UTC, akshatdubeysf approved these changes

2022-11-23 07:24 UTC, samarpan-b requested changes

2022-11-23 07:24 UTC, samarpan-b commented on packages/core/src/components/bearer-verifier/providers/facades-bearer-token-verify.provider.ts
> +      if (this.authUserModel) {
Why this check ?

2022-11-23 07:24 UTC, samarpan-b commented on packages/core/src/components/bearer-verifier/providers/facades-bearer-token-verify.provider.ts
> +    @inject(AuthenticationBindings.USER_MODEL, {optional: true})
What is this new injection for ?

2022-11-25 11:34 UTC, akshatdubeysf approved these changes

2022-11-25 12:45 UTC, merged