feat(chat-service): setup chat microservice
sourcefuse/loopback4-microservice-catalog pull request #109
Opened 2020-12-23 06:47 UTC by rashisf

SFO-167

## Description

Base Setup for Chat Microservice

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2020-12-30 09:38 UTC, samarpan-b commented
Please add a sandbox example integration for this. @rashisf

2021-03-10 12:47 UTC, akshatdubeysf requested changes

2021-03-10 12:47 UTC, akshatdubeysf commented on services/chat-service/src/controllers/message-recipient-message.controller.ts
> +    return this.messageRecipientRepository.message(id);
This would always fetch a single message, but ideally a recipient could exist in multiple messages?

2021-03-10 12:47 UTC, akshatdubeysf commented on services/chat-service/src/datasources/pgdb.datasource.ts
> +import config from './pgdb.datasource.config.json';
It's better to fetch such configs from environment.

2021-03-10 12:47 UTC, akshatdubeysf commented on services/chat-service/src/models/message-recipient.model.ts
> +  channelId: string;
How are the channels created and mantained?

2021-03-10 12:47 UTC, akshatdubeysf commented on services/chat-service/src/models/message.model.ts
> +  channelId: string;
Same as in case of recipient, how is channel Id created and maintained?

2021-03-10 12:47 UTC, akshatdubeysf commented on services/chat-service/src/models/message-recipient.model.ts
> +    () => Message,
But Recipient could belong to multiple messages? This is related to the remark in the controller.

2021-03-10 12:47 UTC, akshatdubeysf commented on services/chat-service/src/index.ts
> +export * from './component';
Export keys, types, models and repositories as well so the parent application could use those to extend the functionality in this service.

2021-03-22 06:12 UTC, samarpan-b commented
@rashisf Would you be able to fix the comments or would you prefer if someone else take this forward ?

2021-05-21 07:22 UTC, samarpan-b commented
@ashutosh-bansal-2136 can u attach DB schema as part of PR description please ?

2021-05-21 07:22 UTC, samarpan-b commented
fix code smells

2021-05-21 07:34 UTC, akshatdubeysf requested changes

2021-05-21 07:34 UTC, akshatdubeysf commented on .cz-config.js
> +    {name: 'chat-service'},
Add this in the .czferc.js instead of .cz-config.js.

2021-05-21 07:34 UTC, akshatdubeysf commented on .cz-config.js
> +    {name: 'chat-service'},
I must have missed removing this file, so if possible, remove this file as well, as it's no longer needed.

2021-05-21 07:34 UTC, akshatdubeysf commented on services/chat-service/README.md
> +### Migrations
Can you check in one of the other services to see how we provide migrations, and follow that.

2021-05-21 07:34 UTC, akshatdubeysf commented on services/chat-service/package.json
> +    "typescript": "~3.8.3"
Can you update the packages to ensure compatibility with other sourceloop services and core.

2021-06-30 14:18 UTC, merged