fix(chore): added if condition for createall db call
sourcefuse/loopback4-microservice-catalog pull request #1125
Opened 2022-12-14 08:49 UTC by yeshamavani

gh-1124

## Description

Added the if condition to check the entity length before calling the repo.createAll call
to avoid error.

Fixes #1124

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-12-16 10:56 UTC, akshatdubeysf requested changes

2022-12-16 10:56 UTC, akshatdubeysf commented on packages/core/src/repositories/default-user-modify-crud.repository.base.ts
> +    if (entities.length <= 0) {
Why not just check entities.length

2022-12-16 10:56 UTC, akshatdubeysf commented on services/chat-service/src/controllers/attachment-file.controller.ts
> +    if (attachFiles.length <= 0) {
If is at repo level, why is it required here?

2022-12-19 09:18 UTC, yeshamavani commented on services/chat-service/src/controllers/attachment-file.controller.ts
> +    if (attachFiles.length <= 0) {
will remove this

2023-03-10 13:30 UTC, akshatdubeysf requested changes

2023-03-10 13:30 UTC, akshatdubeysf commented on packages/core/src/repositories/default-transactional-user-modify-repository.base.ts
> +    if (!entities.length) {
This should be breaking change

2023-12-14 10:44 UTC, yeshamavani commented
This will be released when there is a breaking change

2024-01-01 09:56 UTC, yeshamavani commented
Raised another PR with same changes to avoid merge conflicts - https://github.com/sourcefuse/loopback4-microservice-catalog/pull/1881

2024-01-01 09:56 UTC, closed without merging