feat(oidc-service): adds oidc-service functionality
sourcefuse/loopback4-microservice-catalog pull request #1144
Opened 2022-12-30 11:09 UTC by sumiter92

## Description

Adds oidc-service

Fixes #265 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] Code conforms with the style guide

2023-01-30 13:19 UTC, jamescrowley321 requested changes

2023-01-30 13:19 UTC, jamescrowley321 commented on services/oidc-service/migrations/sqls/20210318100600-init-up.sql
> +	first_name           varchar(50)  NOT NULL ,
Why not just use the text type? You don't need to maintain column lengths with it.

2023-01-30 13:19 UTC, jamescrowley321 commented on services/oidc-service/src/services/oidc-service.ts
> +      redirect_uris: [ "https://oidcdebugger.com/debug"],
These values can not be hard coded. We need to read from sort of data store for this.

2023-01-30 13:19 UTC, jamescrowley321 commented on services/oidc-service/src/services/oidc-service.ts
> +      'plain'
Remove `plain`

2023-01-30 13:19 UTC, jamescrowley321 commented on services/oidc-service/src/services/oidc-service.ts
> +    scopeA: ['claim1', 'claim2'],
What is `scopeA`?

2023-05-22 11:05 UTC, antriksha102 commented
Hi @jamescrowley321 

Please review the changes. I have updated based on your comments.

2023-05-26 11:43 UTC, jamescrowley321 approved these changes

2023-06-02 13:51 UTC, antriksha102 commented on services/oidc-service/migrations/sqls/20210318100600-init-up.sql
> +	first_name           varchar(50)  NOT NULL ,
Default table user is varchar. Should be provided by consumer as it can overridden.

2023-06-02 13:52 UTC, antriksha102 commented on services/oidc-service/src/services/oidc-service.ts
> +      redirect_uris: [ "https://oidcdebugger.com/debug"],
These values are modified to get the data from the data source.

2023-06-02 13:52 UTC, antriksha102 commented on services/oidc-service/src/services/oidc-service.ts
> +    scopeA: ['claim1', 'claim2'],
This code is modified.

2023-06-02 14:07 UTC, antriksha102 commented on services/oidc-service/README.md
> +| `OIDC_COOKIES` | For setting cookiee key. |
Added a link for the same.

2023-06-02 14:48 UTC, shubhamp-sf requested changes
Adding few code review points to be looked upon.

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/README.md
> +To get started with a basic implementation of this service, refer to the `/sandbox/oidc-basic-example` directory.
Please add the link to this folder.

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/migration.js
> +const type = 'AUTH';
Shouldn't it be OIDC?

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/package.json
> +    "node": "12 || 14 || 16 || 17"
```suggestion
    "node": "16 || 17 || 18"
```

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/package.json
> +  "license": "",
```suggestion
  "author": "SourceFuse",
  "license": "MIT",
```

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/package.json
> +    "oidc-provider": "^7.12.0",
Why we're not using the latest version for oidc-provider?

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/public/index.html
> +  <title>test-oidc</title>
```suggestion
  <title>OIDC Service</title>
```

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/public/index.html
> +    <h1>test-oidc</h1>
Same.

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/public/views/login.ejs
> +        <button type="submit" class="login login-submit">Sign-in</button>
```suggestion
        <button type="submit" class="login login-submit">Sign In</button>
```

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/public/views/login.ejs
> +    <title>Welcome! Sign-in</title>
```suggestion
    <title>Welcome! Sign In</title>
```

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/src/controllers/index.ts
> +export const controllers = [OidcController];
Why is this needed?

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/src/controllers/oidc.controller.ts
> +          title: 'Sign-in',
```suggestion
          title: 'Sign in',
```

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/src/controllers/oidc.controller.ts
> +    @inject(RestBindings.Http.RESPONSE) response2: Response,
Where is this injection being used?

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/src/controllers/oidc.controller.ts
> +    _requestBody: {
ideally the argument name doesn't starts with underscore, please use something more concrete here.

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/src/controllers/oidc.controller.ts
> +      return 'user not exist or not authenticated';
```suggestion
      return 'The user does not exist or is not authenticated.';
```

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/src/controllers/oidc.controller.ts
> +      throw new Error('Something went wrong');
Can this error be more explicit please, `interactionFinished` method must be throwing some text when rejected. I believe we can get that in catch.

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/src/keys.ts
> +  );
```suggestion
  export const LoginTemplate = BindingKey.create<string>(
    `${BINDING_PREFIX}.oidc.template.login`,
  );
  export const InteractionTemplate = BindingKey.create<string>(
    `${BINDING_PREFIX}.oidc.template.interaction`,
  );
  export const OIDC_PROVIDER = BindingKey.create<OidcProvider>(
    `${BINDING_PREFIX}.oidc.provider`,
  );
  export const FIND_ACCOUNT_PROVIDER = BindingKey.create<FindAccountProviderFn>(
    `${BINDING_PREFIX}.oidc.findAccountProvider`,
  );
```

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/src/models/auth-client.model.ts
> +﻿// Copyright (c) 2022 Sourcefuse Technologies
```suggestion
﻿// Copyright (c) 2023 Sourcefuse Technologies
```

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/src/models/index.ts
> +export const models = [
why is this extra variable export needed?

2023-06-02 14:48 UTC, shubhamp-sf commented on services/oidc-service/src/providers/find-account.provider.ts
> +const defaultClaims = ['firstName', 'lastName'];
why the default claims here doesn't include email like in `oidc.provider.ts`?

2023-06-02 18:45 UTC, antriksha102 commented on services/oidc-service/README.md
> +To get started with a basic implementation of this service, refer to the `/sandbox/oidc-basic-example` directory.
Done.

2023-06-02 18:46 UTC, antriksha102 commented on services/oidc-service/README.md
> +
Table Added for the same.

2023-06-02 18:47 UTC, antriksha102 commented on services/oidc-service/README.md
> +```
Added

2023-06-02 18:47 UTC, antriksha102 commented on services/oidc-service/migration.js
> +const type = 'AUTH';
Changed to OIDC.

2023-06-02 18:48 UTC, antriksha102 commented on services/oidc-service/CHANGELOG.md
> +
Done

2023-06-02 18:48 UTC, antriksha102 commented on services/oidc-service/README.md
> +
Table Added.

2023-06-02 18:49 UTC, antriksha102 commented on services/oidc-service/src/controllers/index.ts
> +export const controllers = [OidcController];
Removed.

2023-06-02 18:50 UTC, antriksha102 commented on services/oidc-service/public/views/login.ejs
> +    <title>Welcome! Sign-in</title>
Done

2023-06-02 18:50 UTC, antriksha102 commented on services/oidc-service/public/views/login.ejs
> +        <button type="submit" class="login login-submit">Sign-in</button>
Done

2023-06-02 18:50 UTC, antriksha102 commented on services/oidc-service/src/controllers/oidc.controller.ts
> +          title: 'Sign-in',
Done.

2023-06-02 18:50 UTC, antriksha102 commented on services/oidc-service/src/controllers/oidc.controller.ts
> +    _requestBody: {
Changed.

2023-06-02 18:51 UTC, antriksha102 commented on services/oidc-service/src/controllers/oidc.controller.ts
> +    @inject(RestBindings.Http.RESPONSE) response2: Response,
Removed.

2023-06-02 18:51 UTC, antriksha102 commented on services/oidc-service/src/controllers/oidc.controller.ts
> +      throw new Error('Something went wrong');
Added error context in catch.

2023-06-02 18:51 UTC, antriksha102 commented on services/oidc-service/src/controllers/oidc.controller.ts
> +      return 'user not exist or not authenticated';
Added.

2023-06-02 18:52 UTC, antriksha102 commented on services/oidc-service/src/keys.ts
> +  );
Added.

2023-06-02 18:52 UTC, antriksha102 commented on services/oidc-service/src/models/auth-client.model.ts
> +﻿// Copyright (c) 2022 Sourcefuse Technologies
Changed for all the files.

2023-06-02 18:52 UTC, antriksha102 commented on services/oidc-service/src/models/index.ts
> +export const models = [
Extra variable export removed.

2023-06-02 18:53 UTC, antriksha102 commented on services/oidc-service/src/providers/find-account.provider.ts
> +const defaultClaims = ['firstName', 'lastName'];
Email added.

2023-06-02 18:53 UTC, antriksha102 commented on services/oidc-service/src/repositories/index.ts
> +  UserCredentialsRepository,
Done.

2023-06-02 18:54 UTC, antriksha102 commented on services/oidc-service/package.json
> +    "node": "12 || 14 || 16 || 17"
Done.

2023-06-02 18:56 UTC, antriksha102 commented on services/oidc-service/public/index.html
> +  <title>test-oidc</title>
Done.

2023-06-02 18:56 UTC, antriksha102 commented on services/oidc-service/package.json
> +  "license": "",
Done.

2023-06-02 18:56 UTC, antriksha102 commented on services/oidc-service/package.json
> +    "oidc-provider": "^7.12.0",
Changed to latest version.

2023-06-03 06:53 UTC, shubhamp-sf commented on services/oidc-service/src/controllers/index.ts
> +export const controllers = [OidcController];
Missed pushing it?

2023-06-03 06:53 UTC, shubhamp-sf approved these changes

2023-06-03 07:10 UTC, antriksha102 commented on services/oidc-service/src/controllers/index.ts
> +export const controllers = [OidcController];
Pushed.

2023-06-03 07:37 UTC, merged