fix(notification-service): hard deleting notif users for gdpr compliance
sourcefuse/loopback4-microservice-catalog pull request #117
Opened 2021-02-03 10:14 UTC by vineet-suri

RFIT-1467

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-02-03 10:20 UTC, bhupesh-sf approved these changes

2021-02-04 11:10 UTC, samarpan-b requested changes

2021-02-04 11:10 UTC, samarpan-b commented on services/notification-service/src/controllers/notification-user.controller.ts
> +    return this.notificationUserRepository.deleteAllHard(
expose a separate API for this.  we shud have both type of apis

2021-02-04 11:23 UTC, vineet-suri commented on services/notification-service/src/controllers/notification-user.controller.ts
> +    return this.notificationUserRepository.deleteAllHard(
done

2021-02-04 11:34 UTC, samarpan-b approved these changes

2021-02-04 11:35 UTC, merged