docs(core): add mkdocs and typedoc configuration
sourcefuse/loopback4-microservice-catalog pull request #1193
Opened 2023-01-11 11:45 UTC by shubhamp-sf

![image](https://user-images.githubusercontent.com/110156023/211797859-b17acb7c-9010-4c61-9e40-6d9be2786aa1.png)

Preview: https://loopback4-microservice-catalog.vercel.app/
1. Added and configured mkdocs and typedoc for later mentioned services and packages in order to export API references.
2. Added "Docs" workflow script that rebuilds API References on push to master branch and updated compiled html files on `gh-pages` branch.
3. By default typdoc won't include other markdown files such as `openapi.md` so to use it I've used custom script that tweaks the formatting of that files and copy it into the folder when building docs.
4. It's important to follow common formatting standards in README files as it will cause failure while building docs, some common mistakes are:
     - Not using backticks (\`\`) while typing out decorators/any code term. for example writing @authentication will fail as it considers this as a tsdoc tag. So this needs to be properly enclosed within them.
 
 KNOWN ISSUE: While hosting this on github pages the default links are broken as mkdocs adds up "../" to all links. So It's better to have a dedicated domain for it like it worked with vercel deployment.

Services
- Audit service
- Authentication service
- Bpmn service
- Chat service
- Feature toggle service
- In mail service
- Notification service
- Ocr s3 service
- Ocr service
- Payment service
- Reporting service
- Scheduler service
- Search service
- User tenant service
- Video conferencing service

**Packages**
- Cache
- Core
- Feature toggle

Closes #1192

2023-01-11 13:42 UTC, jamescrowley321 approved these changes

2023-01-11 14:09 UTC, akshatdubeysf requested changes

2023-01-11 14:09 UTC, akshatdubeysf commented on export-typedocs.sh
> +lerna exec --scope '{@sourceloop/core,@sourceloop/audit-service,@sourceloop/authentication-service,@sourceloop/feature-toggle,@sourceloop/bpmn-service,@sourceloop/chat-service,@sourceloop/feature-tog
Why not write a TS/JS script? that would be easier to maintain and understand? We could have logic to read all packages so addition of a service or package doesn't require updating this script (assuming we also have an option to filter out the non-required services/packages within this script)

2023-01-11 14:09 UTC, akshatdubeysf commented on services/authentication-service/README.md
> +<table>
This same document is also rendered in npm page for this service, would this table work there?

2023-01-11 15:10 UTC, akshatdubeysf commented on services/authentication-service/README.md
> +<table>
Then this should be fine 🙂

2023-01-11 15:21 UTC, shubhamp-sf commented on export-typedocs.sh
> +lerna exec --scope '{@sourceloop/core,@sourceloop/audit-service,@sourceloop/authentication-service,@sourceloop/feature-toggle,@sourceloop/bpmn-service,@sourceloop/chat-service,@sourceloop/feature-tog
Surely it would but I feel `.sh` file is a better place when we just need to run some commands one after another.
The only down side is maintaining bulky scope parameter, I will see if this can be stripped out elegantly.

What do you think about adding additional `command` besides bootstrap etc. in `lerna.json`? and just running `lerna run export-typedocs` here or in root `package.json`?

2023-01-11 15:47 UTC, akshatdubeysf commented on export-typedocs.sh
> +lerna exec --scope '{@sourceloop/core,@sourceloop/audit-service,@sourceloop/authentication-service,@sourceloop/feature-toggle,@sourceloop/bpmn-service,@sourceloop/chat-service,@sourceloop/feature-tog
But these are not simple independent scripts na? If a new service is added, it would have to be manually added to every single script, a manual work that can be avoided. Even if lerna allows writing a command, that would still require you to add the list manually, for each sub command or script. Considering all other automations are in js/ts, why do you feel an `.sh` script would be better?  And even if you want to stick to `sh`, you can write this script in a way to avoid manual rework.

2023-01-11 16:08 UTC, akshatdubeysf commented on export-typedocs.sh
> +lerna exec --scope '{@sourceloop/core,@sourceloop/audit-service,@sourceloop/authentication-service,@sourceloop/feature-toggle,@sourceloop/bpmn-service,@sourceloop/chat-service,@sourceloop/feature-tog
In the script you can write logic to read some custom properties from the service/packages package.json na? You write code to read all services/packages and filter them out based on these package.json properties 🙂

2023-01-11 16:18 UTC, shubhamp-sf commented on export-typedocs.sh
> +lerna exec --scope '{@sourceloop/core,@sourceloop/audit-service,@sourceloop/authentication-service,@sourceloop/feature-toggle,@sourceloop/bpmn-service,@sourceloop/chat-service,@sourceloop/feature-tog
Are ha... 

Boss you're so smart! 😎

Will do this. 👍

2023-01-16 12:54 UTC, shubhamp-sf commented on export-typedocs.sh
> +lerna exec --scope '{@sourceloop/core,@sourceloop/audit-service,@sourceloop/authentication-service,@sourceloop/feature-toggle,@sourceloop/bpmn-service,@sourceloop/chat-service,@sourceloop/feature-tog
Done.

2023-01-16 14:21 UTC, shubhamp-sf commented on export-typedocs.sh
> +lerna exec --scope '{@sourceloop/core,@sourceloop/audit-service,@sourceloop/authentication-service,@sourceloop/feature-toggle,@sourceloop/bpmn-service,@sourceloop/chat-service,@sourceloop/feature-tog
I created [export-typedocs.ts](https://github.com/sourcefuse/loopback4-microservice-catalog/pull/1193/files#diff-de1112299a30d65543ae0366c47b252f204fd9d02fd927154f212265211bc240) if you want to review.

An execution overview of `export-typedocs.ts` would be this:
1. It runs the command `lerna ls` to get a list of all public packages.
2. It iterates through each package in the retrieved packages.
3. For each package, it attempts to import the package's package.json file where it reads the optional field `typedoc`.
For API references to work, packages have similar to below object in their package.json file
```json
{
  "typedoc": {
    "config": {
      "entryPoints": [ "src/index.ts" ],
      "out": "services/authentication-service"
    },
    "settings": {
      "includeOpenAPIDoc": true
    }
  }
}
```
***This also eliminated the need of extra `typedoc.json` in every target package 🙂, thanks for the suggestion.***

Can we mark this as resolve now?

2023-01-16 15:16 UTC, jamescrowley321 commented on export-typedocs.sh
> +lerna exec --scope '{@sourceloop/core,@sourceloop/audit-service,@sourceloop/authentication-service,@sourceloop/feature-toggle,@sourceloop/bpmn-service,@sourceloop/chat-service,@sourceloop/feature-tog
@shubhamp-sf Can you add that command to the SL CLI and make sure the steps are documented? We can use this same technique elsewhere. Feel free to raise another PR for that.

2023-01-16 15:37 UTC, shubhamp-sf commented on export-typedocs.sh
> +lerna exec --scope '{@sourceloop/core,@sourceloop/audit-service,@sourceloop/authentication-service,@sourceloop/feature-toggle,@sourceloop/bpmn-service,@sourceloop/chat-service,@sourceloop/feature-tog
Sure.

2023-01-16 17:12 UTC, merged