feat(authentication-service): added express middleware in sequence
sourcefuse/loopback4-microservice-catalog pull request #120
Opened 2021-02-07 11:08 UTC by sf-kansara

RPMS-2771

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-02-07 19:51 UTC, samarpan-b requested changes

2021-02-07 19:51 UTC, samarpan-b commented on sandbox/auth-multitenant-example/src/application.ts
> +      morgan('MORGAN_LOG > :method :url :status'),
why morgan ? we have logger

2021-02-07 19:51 UTC, samarpan-b commented on services/authentication-service/src/sequence.ts
> +        const responseGenerated = await this.invokeMiddleware(
this line is important to be executed. Otherwise, it will throw weird errors for every API.

2021-02-08 04:39 UTC, sf-kansara commented on sandbox/auth-multitenant-example/src/application.ts
> +      morgan('MORGAN_LOG > :method :url :status'),
Morgan is to test feature of having response and non response generating express middlewares. Also adding other middlewares such as swagger stats should work with morgan.

2021-02-08 06:01 UTC, samarpan-b commented on services/authentication-service/src/sequence.ts
> +        const responseGenerated = await this.invokeMiddleware(
`await this.invokeMiddleware` This is needed. Else, APIs will fail.

2021-02-08 06:02 UTC, samarpan-b commented on sandbox/auth-multitenant-example/src/application.ts
> +      morgan('MORGAN_LOG > :method :url :status'),
But why use morgan and introduce another logger, when we already have a logger.

2021-02-08 06:08 UTC, sf-kansara commented on sandbox/auth-multitenant-example/src/application.ts
> +      morgan('MORGAN_LOG > :method :url :status'),
I'll remove it

2021-02-10 11:37 UTC, samarpan-b approved these changes

2021-02-10 11:37 UTC, merged