feat: signup request controller added
sourcefuse/loopback4-microservice-catalog pull request #121
Opened 2021-03-01 14:50 UTC by akshatdubeysf

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes RPMS-3023
authentication-service
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated

2021-03-02 06:01 UTC, sf-kansara requested changes

2021-03-02 06:01 UTC, sf-kansara commented on services/authentication-service/src/models/signup-with-token-dto.model.ts
> +export class SignupWithTokenDto<T> extends Model {
This model may not be needed

2021-03-02 06:32 UTC, akshatdubeysf commented on services/authentication-service/src/controllers/signup-request.controller.ts
> +    req: SignupRequestDto,
Fixed

2021-03-02 06:33 UTC, akshatdubeysf commented on services/authentication-service/src/controllers/signup-request.controller.ts
> +  @post('/auth/signupWithToken', {
Done

2021-03-02 06:33 UTC, akshatdubeysf commented on services/authentication-service/src/controllers/signup-request.controller.ts
> +  @post(`auth/createInviteToken`, {
Done

2021-03-02 06:50 UTC, akshatdubeysf commented on services/authentication-service/src/controllers/signup-request.controller.ts
> +      email: req.email,
Added a data field in signup request dto, this can be used to pass any extra information, and that information can be saved to token using the presignup provider.

2021-03-02 06:51 UTC, akshatdubeysf commented on services/authentication-service/src/models/signup-with-token-dto.model.ts
> +export class SignupWithTokenDto<T> extends Model {
Removed

2021-03-02 09:59 UTC, sf-kansara approved these changes

2021-03-05 16:07 UTC, samarpan-b approved these changes

2021-03-05 16:20 UTC, merged