Workflow Library Angular 13 migration
sourcefuse/loopback4-microservice-catalog pull request #1219
Opened 2023-01-20 09:01 UTC by GurpreetChhabraSF

- [x] Workflow Library Angular 13 migration

Fixes # (issue)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] Performed a self-review of my own code

2023-01-22 14:20 UTC, akshatdubeysf requested changes

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/builder/builder.component.ts
> +    '../../assets/icons/icomoon/style.css',
Is this the ideal way to this?

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/builder/builder.component.ts
> +  eActionGroups: BaseGroup<E>[] = [];
What is this? use a better name or create actionGroups as a map with if and else keys and values of types BaseGroup

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/builder/builder.component.ts
> +  showElseBlock = true;
Leave a comment that this will have to be refactored

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/builder.service.ts
> +    this.addElseIntoMainFlow(elseStatement, statement);
Leave a comment that this will have to be refactored to be more flexible

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/builder.service.ts
> +    switch (trigger.workflowNode.constructor.name) {
Arre this is hard coding the start element options, the Trigger Node of a particular type should have this information i.e. type of starting element.

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/builder.service.ts
> +      currentNode = this.nodes.getNodeByName(
Leave a comment that this will have to be refactored

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/elements/gateways/e-gateway.element.ts
> +export class EGatewayElement extends BpmnElement {
Better naming

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/elements/gateways/gateway.element.ts
> +  default: string;
What is the purpose of this property?

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/elements/tasks/read-column.task.ts
> +    @Inject('env') private env: ENV,
Use and injection token, and that should be documented

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/strategies/link/gateway-link.strategy.ts
> +      var selCol = selectedVals.split(',');
Can keep this as constants in a set of script bindings so they would be easy to replace

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/workflow-builder.module.ts
> +    // {provide: BPMN_NODES, useValue: ReadColumnValueAction, multi: true},
??

2023-01-22 14:20 UTC, akshatdubeysf commented on packages/workflow-ui/projects/workflow-ui/src/lib/workflow-builder.module.ts
> +    // {provide: BPMN_NODES, useValue: OnConditionChangeEvent, multi: true},
?

2023-01-22 17:21 UTC, GurpreetChhabraSF commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/builder.service.ts
> +    this.addElseIntoMainFlow(elseStatement, statement);
Done

2023-01-22 17:21 UTC, GurpreetChhabraSF commented on packages/workflow-ui/projects/workflow-ui/src/lib/builder/builder.component.ts
> +  showElseBlock = true;
Done

2023-01-22 17:21 UTC, GurpreetChhabraSF commented on packages/workflow-ui/projects/workflow-ui/src/lib/workflow-builder.module.ts
> +    // {provide: BPMN_NODES, useValue: ReadColumnValueAction, multi: true},
Removed

2023-01-22 17:21 UTC, GurpreetChhabraSF commented on packages/workflow-ui/projects/workflow-ui/src/lib/workflow-builder.module.ts
> +    // {provide: BPMN_NODES, useValue: OnConditionChangeEvent, multi: true},
Removed

2023-01-23 10:13 UTC, nileshkumar-sf commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/elements/gateways/gateway.element.ts
> +  default: string;
Used as an id of the flow from gateway to the default end element to prevent the creation of excessive flows.

2023-01-25 09:09 UTC, nileshkumar-sf commented on packages/workflow-ui/projects/workflow-ui/src/lib/builder/builder.component.ts
> +  eActionGroups: BaseGroup<E>[] = [];
updated

2023-01-25 09:09 UTC, nileshkumar-sf commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/builder.service.ts
> +    switch (trigger.workflowNode.constructor.name) {
updated

2023-01-25 09:11 UTC, nileshkumar-sf commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/builder.service.ts
> +      currentNode = this.nodes.getNodeByName(
updated

2023-01-25 09:12 UTC, nileshkumar-sf commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/elements/gateways/e-gateway.element.ts
> +export class EGatewayElement extends BpmnElement {
updated

2023-01-27 09:05 UTC, GurpreetChhabraSF commented on packages/workflow-ui/projects/workflow-ui/src/lib/builder/builder.component.ts
> +    '../../assets/icons/icomoon/style.css',
No. But for importing icons in library, this is the only solution for now. Will try to figure out an alternative.

2023-01-27 09:06 UTC, GurpreetChhabraSF commented on packages/workflow-ui/projects/workflow-ui/src/lib/services/bpmn/elements/tasks/read-column.task.ts
> +    @Inject('env') private env: ENV,
Done for all tasks and added a document also. Will explain in more detail and example app

2023-06-21 05:36 UTC, closed without merging