docs(user-tenant-service): updates the documentation
sourcefuse/loopback4-microservice-catalog pull request #1248
Opened 2023-01-25 10:58 UTC by sumiter92

## Description

adds the openapi md files and fix the documentation.

Fixes #1201 

## Type of change

Please delete options that are not relevant.

- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] Code conforms with the style guide

2023-02-13 12:57 UTC, yeshamavani commented on services/user-tenant-service/src/application.ts
> +}
??

2023-03-06 05:27 UTC, yeshamavani requested changes

2023-03-06 05:27 UTC, yeshamavani commented on services/user-tenant-service/README.md
> +A Loopback Microservice primarily used for managing user-tenants along with authentication service.
can you add more details about what exactly the service does

2023-06-21 05:45 UTC, shubhamp-sf commented
Changes included in this PR of openapi spec are already done and docs content is being tracked here: #1440

2023-06-21 05:45 UTC, closed without merging