fix(cache): change clearCache function implementation and add some types
sourcefuse/loopback4-microservice-catalog pull request #1251
Opened 2023-01-26 09:48 UTC by barleendhaliwal

## Description

Approach for deletion:
- store insertion time for each key along with payload
- on call of clear cache function store the epoch time in a key in redis. key: ${this.prefix}_DELETION_TIME
- when user requests for something which is present in redis - check the deletion time from this key. if insertion time of requested key <= deletion time delete that key from redis.

Fixes gh-0

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-01-29 08:17 UTC, akshatdubeysf requested changes

2023-01-29 08:17 UTC, akshatdubeysf commented on packages/cache/src/strategies/redis/redis-cache-strategy.ts
> +  ): Promise<RedisConnectorExecuteReturnType> {
Why not take a generic type instead of using as in the parent if the return type is decided by us?

2023-01-29 08:17 UTC, akshatdubeysf commented on packages/cache/src/strategies/redis/redis-cache-strategy.ts
> +          (result as CacheEntity<M>).insertionTime <=
This would fetch the entire cached data, right? why not do this in a script as we discussed? The script would take a key and can return data only if the key is still valid

2023-04-06 06:31 UTC, barleendhaliwal commented on packages/cache/src/strategies/redis/redis-cache-strategy.ts
> +  ): Promise<RedisConnectorExecuteReturnType> {
done

2023-04-06 06:46 UTC, akshatdubeysf commented on packages/cache/src/strategies/redis/redis-cache-strategy.ts
> +          (result as CacheEntity<M>).insertionTime <=
I will do this 🙁

2023-04-06 07:04 UTC, merged