chore(user-onboarding): downgarde user onboarding angular version from 14 to 13
sourcefuse/loopback4-microservice-catalog pull request #1278
Opened 2023-02-06 10:44 UTC by Tyagi-Sunny

downgrade user onboarding angular version from 14 to 13

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1277 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-06 12:45 UTC, yeshamavani requested changes

2023-02-06 12:45 UTC, yeshamavani commented on packages/user-onboarding/package.json
>      "jasmine-spec-reporter": "~5.0.0",
where are the corresponding package-lock.json file changes?

2023-02-06 12:45 UTC, yeshamavani commented on packages/user-onboarding/projects/user-onboarding-lib/package.json
>      "lib": {
same.

2023-05-08 07:45 UTC, yeshamavani approved these changes

2023-05-08 08:42 UTC, shubhamp-sf commented on packages/cli/README.md
Redundant change respective to this PR.

2023-05-08 08:42 UTC, shubhamp-sf approved these changes

2023-05-08 14:42 UTC, yeshamavani commented on packages/cli/README.md
should not be of any issue

2023-05-08 14:51 UTC, shubhamp-sf commented on packages/cli/README.md
And anyway I don't think It is good to change other unrelated package's content (that too just the formatting which will anyway be written back by oclif).

2023-05-09 06:06 UTC, merged