feat(import-service): add import service
sourcefuse/loopback4-microservice-catalog pull request #1282
Opened 2023-02-08 11:14 UTC by Surbhi-sharma1

add import service

GH--1281

## Description

Added Import service

Fixes #1281 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-12 12:12 UTC, akshatdubeysf requested changes

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/services/excel.service.ts
> +      sheet['!rows']?.forEach((row: any, index: number) => {
again, no any

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/services/excel.service.ts
> +      while (currentOutlineLevel <= maxOutlineLevel) {
This function could easily run of memory for large files

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/services/excel.service.ts
> +          (rowData: any, index: number) => {
any 🙁

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/services/excel.service.ts
> +        rowOutlineLevel[index] = row.level;
leave a comment to explain why we need this variable

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/services/excel.service.ts
> +            if (rowOutlineLevel[index + 1] === currentOutlineLevel) {
wrong way to filter out first row

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/services/excel.service.ts
> +        for (let i = 0; i < currentLevelRowData.length; i += batchSize) {
Can write a generator function to improve the quality and readability of this code

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/providers/receive-message-listener.provider.ts
> +    setInterval(() => {
Can improve this code

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/providers/receive-message-listener.provider.ts
> +    setInterval(() => {
What is the purpose of this, also could be written in a better way.

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/providers/receive-message-listener.provider.ts
> +import {ackQueueUrl, client, dataQueueUrl} from './send-message.provider';
dataQueueUrl should be in a common place

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/providers/receive-message-listener.provider.ts
> +        this.saveData(recordData);
This method is provider by the user so the parameter structure should be readable and easy to understand

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/providers/receive-message-listener.provider.ts
> +      client.send(
What if the delete fails?

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/providers/receive-message-listener.provider.ts
> +        client.send(new SendMessageCommand(input));
What if this fails?

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/providers/send-message.provider.ts
> +  async sendMessageLister(levelWiseBatch: MessageData[][]) {
spelling

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/providers/send-message.provider.ts
> +              DataType: 'String',
??

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/src/providers/send-message.provider.ts
> +              StringValue: 'Import from Excel Data',
??

2023-02-12 12:12 UTC, akshatdubeysf commented on services/import-service/README.md
> +export class MyApplication extends BootMixin(ServiceMixin(RepositoryMixin(RestApplication))) {
This needs to actually explain the working and usage na?

2023-02-13 05:46 UTC, Surbhi-sharma1 commented on services/import-service/README.md
> +export class MyApplication extends BootMixin(ServiceMixin(RepositoryMixin(RestApplication))) {
ok Sir 
will do all the changes

2023-03-15 07:57 UTC, Surbhi-sharma1 commented on services/import-service/src/controllers/file-upload.controller.ts
> +  @post('/fileupload', {
done.

2023-03-15 07:57 UTC, Surbhi-sharma1 commented on services/import-service/src/controllers/file-upload.controller.ts
> +      // Set public re,ad permissions
done

2023-03-15 07:58 UTC, Surbhi-sharma1 commented on services/import-service/src/controllers/file-upload.controller.ts
> +        const fileName = fileSplitArr.splice(-1, 1).join('_');
done

2023-03-15 07:58 UTC, Surbhi-sharma1 commented on services/import-service/src/providers/receive-message-listener.provider.ts
> +import {ackQueueUrl, client, dataQueueUrl} from './send-message.provider';
done

2023-03-15 07:59 UTC, Surbhi-sharma1 commented on services/import-service/src/providers/send-message.provider.ts
> +  async sendMessageLister(levelWiseBatch: MessageData[][]) {
corrected

2023-03-15 08:01 UTC, Surbhi-sharma1 commented on services/import-service/src/services/excel.service.ts
> +        for (let i = 0; i < currentLevelRowData.length; i += batchSize) {
done

2024-05-02 05:19 UTC, closed without merging