feat(authentication-service): add SAML passport authentication
sourcefuse/loopback4-microservice-catalog pull request #1284
Opened 2023-02-10 13:27 UTC by RaghavaroraSF

## Description
Added SAML passport authentication

Fixes # GH-1283

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-13 10:53 UTC, yeshamavani commented on services/authentication-service/package.json
> +    "apidocs": "./node_modules/.bin/widdershins --search false --language_tabs 'javascript:JavaScript:request' 'javascript--nodejs:Node.JS' --summary openapi.json -o openapi.md",
??

2023-02-13 10:53 UTC, yeshamavani commented on services/authentication-service/package.json
> +    "jsonwebtoken": "^8.5.1",
why are we downgrading 
this is a vulnerable version.

2023-02-13 10:53 UTC, yeshamavani commented on services/authentication-service/package.json
> +    "loopback4-authentication": "file:loopback4-authentication-7.3.1.tgz",
can not add this here.

2023-02-13 10:53 UTC, yeshamavani commented on services/authentication-service/package.json
> +    "@loopback/build": "^9.0.3",
again why are we downgrading these 
take the latest pull

2023-02-13 10:53 UTC, yeshamavani commented on services/authentication-service/package.json
> +    "passport-azure-ad": {
no need of these overrides?

2023-02-13 10:53 UTC, yeshamavani commented on services/authentication-service/package.json
> -    }
??

2023-02-13 10:53 UTC, yeshamavani commented on services/authentication-service/src/__tests__/unit/saml-post-verify.provider.ts
> +      expect(result).to.be.eql(user);
??

2023-02-13 10:53 UTC, yeshamavani commented on services/authentication-service/src/modules/auth/providers/saml-verify.provider.ts
> +      if (!creds || creds.authId !== profile.id) {
what are we saving as authProvider ?

2023-02-13 10:53 UTC, yeshamavani commented on services/authentication-service/src/modules/auth/saml-login.controller.ts
> +  @post('/auth/saml', {
get and post API endpoint should be same.

2023-02-13 10:55 UTC, yeshamavani commented
lot of version downgrades in package.json file 
check those once

2023-02-14 11:00 UTC, RaghavaroraSF commented on services/authentication-service/package.json
> +    "loopback4-authentication": "file:loopback4-authentication-7.3.1.tgz",
resolved

2023-02-14 11:00 UTC, RaghavaroraSF commented on services/authentication-service/package.json
> +    "jsonwebtoken": "^8.5.1",
resolved

2023-02-14 11:01 UTC, RaghavaroraSF commented on services/authentication-service/package.json
> +    "@loopback/build": "^9.0.3",
resolved

2023-02-14 11:01 UTC, RaghavaroraSF commented on services/authentication-service/package.json
> +    "passport-azure-ad": {
resolved

2023-02-14 11:02 UTC, RaghavaroraSF commented on services/authentication-service/package.json
> +    "apidocs": "./node_modules/.bin/widdershins --search false --language_tabs 'javascript:JavaScript:request' 'javascript--nodejs:Node.JS' --summary openapi.json -o openapi.md",
resolved

2023-02-14 11:03 UTC, RaghavaroraSF commented on services/authentication-service/package.json
> -    }
resolved

2023-02-15 10:27 UTC, RaghavaroraSF commented on services/authentication-service/src/modules/auth/saml-login.controller.ts
> +  @post('/auth/saml', {
resolved

2023-02-16 05:06 UTC, RaghavaroraSF commented on services/authentication-service/src/modules/auth/providers/saml-verify.provider.ts
> +      if (!creds || creds.authId !== profile.id) {
resolved

2023-02-16 06:38 UTC, yeshamavani requested changes

2023-02-16 06:38 UTC, yeshamavani commented on services/authentication-service/src/modules/auth/saml-login.controller.ts
> +  @post('/auth/saml', {
the deprecated @get  and @post should be same 
but the call-back one will be a different one 
refer others you will understand.

2023-02-21 10:38 UTC, yeshamavani approved these changes

2023-02-21 10:38 UTC, yeshamavani commented
rebase the branch @RaghavaroraSF

2023-02-22 10:47 UTC, closed without merging