feat(audit-service): add export feature in audit service
sourcefuse/loopback4-microservice-catalog pull request #1325
Opened 2023-02-21 10:26 UTC by gautam23-sf

add export feature in audit service to export audit logs at a destination provided by user

GH-1324

## Description
add export feature in audit service to export audit logs at a destination provided by user

Fixes #1324 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-03 06:37 UTC, yeshamavani requested changes
Also add test cases

2023-03-03 06:37 UTC, yeshamavani commented on services/audit-service/src/controllers/export-logs.controller.ts
> +  @authorize({permissions: ['*']})
Add a permission here

2023-03-03 06:37 UTC, yeshamavani commented on services/audit-service/src/providers/DeleteExportAuditLogs.provider.ts
> +
move this to types.ts file

2023-03-03 06:37 UTC, yeshamavani commented on services/audit-service/src/providers/SaveExportAuditLogs.provider.ts
> +  //@SONAR_STOP@
why is this needed

2023-03-03 06:37 UTC, yeshamavani commented on services/audit-service/src/providers/SaveExportAuditLogs.provider.ts
> +export interface IExportLogsDestinationFn {
move to types.ts

2023-03-03 06:37 UTC, yeshamavani commented on services/audit-service/src/services/audit-log-export.service.ts
> +    private deleteAuditExportLogs: IdeleteLogs,
IdeleteLogs -- camel case

2023-03-03 06:37 UTC, yeshamavani commented on services/audit-service/src/providers/SaveExportAuditLogs.provider.ts
> +export class SaveExportAuditLogsProvider
what is the use of this provider

2023-03-03 06:37 UTC, yeshamavani commented on services/audit-service/src/services/audit-log-export.service.ts
> +    }
A step to download the logs is missing here

2023-03-05 12:59 UTC, gautam23-sf commented on services/audit-service/src/controllers/export-logs.controller.ts
> +  @authorize({permissions: ['*']})
Done

2023-03-05 13:00 UTC, gautam23-sf commented on services/audit-service/src/providers/DeleteExportAuditLogs.provider.ts
> +
Done

2023-03-05 13:00 UTC, gautam23-sf commented on services/audit-service/src/providers/SaveExportAuditLogs.provider.ts
> +  //@SONAR_STOP@
Removed.

2023-03-05 13:00 UTC, gautam23-sf commented on services/audit-service/src/providers/SaveExportAuditLogs.provider.ts
> +export interface IExportLogsDestinationFn {
Done

2023-03-05 13:00 UTC, gautam23-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +    private deleteAuditExportLogs: IdeleteLogs,
Done

2023-03-05 13:02 UTC, gautam23-sf commented on services/audit-service/src/providers/SaveExportAuditLogs.provider.ts
> +export class SaveExportAuditLogsProvider
This is only a dummy provider, actual provider user needs to write in his service to save the Export Logs at the desired destination.

2023-03-05 13:05 UTC, gautam23-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +    }
I think there is no requirement to download the logs, only user needs to save the Logs at the desired Destination(  as provided by the user)

2023-03-24 08:41 UTC, shubhamp-sf requested changes

2023-03-24 08:41 UTC, shubhamp-sf commented on services/audit-service/package.json
> +
remove this extra line-break

2023-03-24 08:41 UTC, shubhamp-sf commented on services/audit-service/src/__tests__/unit/save-export-audit-logs.provider.unit.ts
> +    }
Why not this: 
```suggestion
    const logger = {
      log: () => {},
      info: () => {},
      warn: () => {},
      error: () => {},
      debug: () => {},
    };
```

2023-03-24 08:41 UTC, shubhamp-sf commented on services/audit-service/src/controllers/export-logs.controller.ts
> +const basePath = '/exportLogs';
The base path should be in kebab case:
```suggestion
const basePath = '/export-logs';
```

2023-03-24 08:41 UTC, shubhamp-sf commented on services/audit-service/src/controllers/export-logs.controller.ts
> +  @get(`${basePath}`, {
Why not use it as is?
```suggestion
  @get(basePath, {
```

2023-03-24 08:41 UTC, shubhamp-sf commented on services/audit-service/src/providers/README.md
> +SaveExportAuditLogs.provider to be given by user and binded in the application.ts.
This README is of providers' directory as whole move the usage instruction in audit-service's readme.

2023-03-24 08:41 UTC, shubhamp-sf commented on services/audit-service/src/providers/delete-export-audit-logs.provider.ts
> +            }
Will this not throw error if files array contains a name of a directory since `unlinkSync` is used.

2023-03-24 08:41 UTC, shubhamp-sf commented on services/audit-service/src/controllers/export-logs.controller.ts
> +            },
Mismatch between swagger response type and the actual implementation of the function. As this method doesn’t return anything? (If that’s what intended, the method name should be renamed from `find` to something else like `exportToExcel`)

2023-04-10 08:10 UTC, gautam23-sf commented on services/audit-service/src/providers/delete-export-audit-logs.provider.ts
> +            }
changed the logic, now the code creates one folder and the files are created in that folder.

2023-04-10 08:19 UTC, shubhamp-sf commented
@gautam23-sf Please rebase and squash the commits as currently it has some redundant changes inside other services as well.

Also add some brief usage details in the readme file please?

2023-06-15 05:58 UTC, closed without merging