feat(authentication-service): added clientType column in auth client
sourcefuse/loopback4-microservice-catalog pull request #1357
Opened 2023-03-25 10:28 UTC by Tyagi-Sunny

make client secret non mandatory for public clients

MIGRATION CHANGE:
migration-20230323132703- added clientType column in auth client

BREAKING CHANGE:
added clientType column in auth client

GH-1356

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1356 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-03-25 13:40 UTC, samarpan-b requested changes

2023-03-25 13:40 UTC, samarpan-b commented on services/authentication-service/package.json
> +    "loopback4-authentication": "file:../../../loopback_package_update/loopback4-authentication/loopback4-authentication-7.5.1.tgz",
Fix this

2023-03-25 13:40 UTC, samarpan-b commented on services/authentication-service/tsconfig.json
> +    "experimentalDecorators": true,
Why this ?

2023-03-27 04:58 UTC, yeshamavani commented on services/authentication-service/package.json
> +    "loopback4-authentication": "file:../../../loopback_package_update/loopback4-authentication/loopback4-authentication-7.5.1.tgz",
once we release loopback4-authentication @Tyagi-Sunny  please change this.

2023-03-27 06:15 UTC, yeshamavani requested changes

2023-03-27 06:15 UTC, yeshamavani commented on services/authentication-service/src/models/auth-client.model.ts
> +  clientType: string;
refer the enum in loopback-auth package

2023-03-31 13:42 UTC, yeshamavani commented
change the description as it is not a breaking change

2023-04-05 06:33 UTC, yeshamavani commented
Update the readme file with all the necessary changes the user has to do to incorporate the feature

2023-04-07 09:28 UTC, yeshamavani approved these changes

2023-04-07 11:01 UTC, yeshamavani requested changes

2023-04-07 11:01 UTC, yeshamavani commented on sandbox/auth-ms-basic-example/src/datasources/redis.datasource.ts
> +export class RedisDataSource
why is this file needed

2023-04-07 11:06 UTC, shubhamp-sf commented on services/authentication-service/src/models/auth-secure-client.model.ts
Try extending it from the existing client model available.

2023-04-07 11:12 UTC, shubhamp-sf commented on services/authentication-service/src/modules/auth/providers/client-password-verify.provider.ts
> -          clientSecret,
Didn't need this removal as the secure provider is already bound in case of secureClient config.

2023-04-10 16:27 UTC, yeshamavani approved these changes

2023-04-10 16:32 UTC, merged