feat(core): prevent cross tenant operation across a…
sourcefuse/loopback4-microservice-catalog pull request #1374
Opened 2023-04-11 11:17 UTC by Tyagi-Sunny

## Description

added a mixin tenant that adds the following logic to a loopback repository -
    1 User of one tenant can not perform CRUD on entities of another tenant
    2 his above rule is not applied for a user belong to a master Tenant
added a decorator for applying above mixin with automatic service injection
added a permission for SuperAdmin
added relevant tests

Fixes #1373 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] https://github.com/shubhamp-sf/sourceloop-tenant-guard-example
- [ ] Test B

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-12 08:20 UTC, shubhamp-sf commented on packages/core/src/__tests__/integration/repo-with-guarded-tenant.decorator.decorator.ts
Put these tests in the nested folder named `tenant-guard` (same for unit and fixtures files as well). This is to ensure the saparation as we may have other component's test cases as well in future.

2023-04-12 08:23 UTC, shubhamp-sf commented on packages/core/src/components/tenant-guard/component.ts
@akshatdubeysf should `TenantGuardComponent` component also be bound by default in `CoreComponent`?
(as we do for `LoggerExtensionComponent` already).

2023-04-12 08:42 UTC, shubhamp-sf commented on packages/core/src/components/tenant-guard/component.ts
Oh okay, make sense.

@Tyagi-Sunny please include usage details about this guard in the readme please.

2023-04-12 09:21 UTC, samarpan-b commented on packages/core/src/components/tenant-guard/component.ts
Agree with @akshatdubeysf

2023-04-12 09:26 UTC, samarpan-b requested changes

2023-04-12 09:26 UTC, samarpan-b commented on packages/core/src/components/tenant-guard/component.ts
> +export class TenantGuardComponent implements Component {
Do we really need to name this component as TenantGuard ? Can we think of a better name ? It sounds too specific.

2023-04-12 09:26 UTC, samarpan-b commented on packages/core/src/components/tenant-guard/component.ts
> +    app.component(LoggerExtensionComponent);
Why are you attaching logger here ? Your component should only do its own stuff

2023-04-12 09:26 UTC, samarpan-b commented on packages/core/src/components/tenant-guard/component.ts
> +    this.services = [TenantGuardService];
why binding twice ?

2023-04-12 09:26 UTC, samarpan-b commented on packages/core/src/components/tenant-guard/services/tenant-guard.service.ts
> +    return user.tenantType === TenantType.MASTER;
IS this overridable ?

2023-04-12 09:41 UTC, akshatdubeysf commented on packages/core/src/components/tenant-guard/component.ts
> +    app.component(LoggerExtensionComponent);
It needs the logger in the binding, even if someone is using it without sourceloop/core, the logger should still work na?

2023-04-12 09:45 UTC, akshatdubeysf commented on packages/core/src/components/tenant-guard/component.ts
> +    this.services = [TenantGuardService];
Mistake, would remove the services array

2023-04-12 09:46 UTC, akshatdubeysf commented on packages/core/src/components/tenant-guard/services/tenant-guard.service.ts
> +    return user.tenantType === TenantType.MASTER;
Not this function specifically, but the class can be extended and bound again, just overriding this function

2023-04-12 10:07 UTC, samarpan-b commented on packages/core/src/components/tenant-guard/component.ts
> +    app.component(LoggerExtensionComponent);
Why binding to app ?

2023-04-12 10:08 UTC, samarpan-b commented on packages/core/src/components/tenant-guard/services/tenant-guard.service.ts
> +    return user.tenantType === TenantType.MASTER;
ok

2023-04-18 12:00 UTC, shubhamp-sf commented on packages/core/src/components/tenant-guard/decorators/tenant-guard.decorator.ts
> +      @inject(TenantGuardBindings.GuardService)
@akshatdubeysf this was done, can you re-view please?

2023-05-01 06:08 UTC, shubhamp-sf approved these changes

2023-05-01 06:09 UTC, shubhamp-sf commented on packages/core/src/components/tenant-guard/decorators/tenant-guard.decorator.ts
> +      @inject(TenantGuardBindings.GuardService)
@akshatdubeysf this was done, can you re-view please?

2023-05-09 04:13 UTC, shubhamp-sf commented on packages/core/src/components/tenant-guard/decorators/tenant-guard.decorator.ts
> +      @inject(TenantGuardBindings.GuardService)
@akshatdubeysf this was done, can you re-view please?

2023-05-10 08:52 UTC, akshatdubeysf requested changes

2023-05-10 08:52 UTC, akshatdubeysf commented on packages/core/src/components/tenant-utilities/keys.ts
> +export const TenantGuardNamespace = 'sourceloop.tenant.guard';
This should also be updated na

2023-05-10 13:24 UTC, akshatdubeysf approved these changes

2023-05-11 07:20 UTC, merged