feat(user-onboarding): add element support and script for building
sourcefuse/loopback4-microservice-catalog pull request #1377
Opened 2023-04-14 07:30 UTC by RaghavaroraSF

## Description

Add elements support to user-onboarding library
Added steps to build script to build and bundle the element files with the package

Fixes # (1352)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-19 10:16 UTC, yeshamavani requested changes

2023-07-19 10:16 UTC, yeshamavani commented on packages/user-onboarding/projects/user-onboarding-lib/bundle-element.js
> +    JSON.stringify(jsonObj, null, space),
the  .scss file mentioned in readme is not the part of final bundle

2023-07-19 10:16 UTC, yeshamavani commented on packages/user-onboarding/projects/user-onboarding-lib/bundle-element.js
> +async function elementsBundler() {
@deepika

2023-07-19 10:16 UTC, yeshamavani commented on packages/user-onboarding/projects/user-onboarding-lib/README.md
> +The web component accepts all the same inputs and services as the regular Angular Module, but instead of passing them through bindings and DI, you pass them as properties of the element as shown belo
show an example of how properties are passed.
how is the html and all the properties passed

2023-07-19 10:51 UTC, Deepika516 commented on packages/user-onboarding/projects/user-onboarding-lib/bundle-element.js
> +async function elementsBundler() {
i Can't not working with Ts keeping it with Js

2023-07-19 11:06 UTC, Deepika516 commented on packages/user-onboarding/projects/user-onboarding-lib/README.md
> +The web component accepts all the same inputs and services as the regular Angular Module, but instead of passing them through bindings and DI, you pass them as properties of the element as shown belo
as such everything is mentioned in above readme ,thats y i just mentioned the window part

2023-07-27 12:24 UTC, yeshamavani approved these changes

2023-07-28 11:01 UTC, shubhamp-sf approved these changes

2023-07-28 11:02 UTC, merged