feat(sequelize): add switchable sequelize support in all services
sourcefuse/loopback4-microservice-catalog pull request #1422
Opened 2023-05-18 09:01 UTC by shubhamp-sf

## TODO

- [ ] Move the sequelize--enable/disable scripts to `@sourceloop/cli` as commands.
- [ ] Do the similar changes for all services as already done for audit-service in this draft.
  - [ ] Extend the existing repositories and make them use the SequelizeCrudRepository.
  - [ ] Extends the existing controller and replace the repository injection.
  - [ ] In case some extra logic is used in repository (like there is in user-tenant-service) ensure it is kept common using a mixin for both the repositories (this draft already includes an example on how it can be done).
- [ ] Write unit tests to ensure the correct artifacts are used in both of the components.
- [ ] Write integrations tests to ensure the existing API behaviour is kept intact when switching to sequelize.
- [ ] Update documentation.

## Description

This PR adds another component in audit-service that overrides the repository and controller for based on sequelize configurations and uses directory import syntax to export it. Allowing users of this service to quickly switch the ORM when needed in backward compatible manner.

Fixes #1350

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [x] Tested in https://github.com/shubhamp-sf/audit-service-example

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-16 11:52 UTC, samarpan-b requested changes

2023-11-16 11:52 UTC, samarpan-b commented on services/audit-service/README.md
> +1. Change the import statements from `@sourceloop/audit-service` to `@sourceloop/audit-service/sequelize`. This can be done easily with your IDEs find and replace feature.
We need to support this via SL cli too. Add this as an option there too @yeshamavani .

2023-11-16 11:52 UTC, samarpan-b commented on services/audit-service/package.json
> +    "@loopback/sequelize": "^0.4.0",
Cant we make it optional dependency ? If someone is not using sequelize, why does he need to install it ?

2023-11-16 11:52 UTC, samarpan-b commented on services/audit-service/src/controllers/audit.controller.ts
> +    public auditLogRepository: AuditLogRepository | AuditLogSequelizeRepository,
I dont like this approach. Shouldn't we just expose appropriate controller as binding based upon a config at component level.

2023-11-16 11:52 UTC, samarpan-b commented on services/audit-service/src/services/export-to-csv.service.ts
> +    public auditLogRepository: AuditLogRepository | AuditLogSequelizeRepository,
Why ?

2023-11-16 11:52 UTC, samarpan-b commented on services/audit-service/src/services/sequelize/export-handler.service.ts
> +export class ExportHandlerProvider extends JugglerExportHandlerProvider {
Why this class for sequelize ? There are no repositories here

2023-11-17 06:49 UTC, Surbhi-sharma1 commented on services/audit-service/src/controllers/audit.controller.ts
> +    public auditLogRepository: AuditLogRepository | AuditLogSequelizeRepository,
I have binded sequelize controllers in its component  but this controller is extending the juggler audit controller and without it was getting type error.

2023-11-17 06:57 UTC, Surbhi-sharma1 commented on services/audit-service/src/services/export-to-csv.service.ts
> +    public auditLogRepository: AuditLogRepository | AuditLogSequelizeRepository,
Same type error for services as sequelize service is extending the existing juggler service.

2023-11-17 09:27 UTC, Surbhi-sharma1 commented on services/audit-service/src/services/sequelize/export-handler.service.ts
> +export class ExportHandlerProvider extends JugglerExportHandlerProvider {
Removed.

2023-11-17 09:28 UTC, Surbhi-sharma1 commented on services/audit-service/package.json
> +    "@loopback/sequelize": "^0.4.0",
Done

2023-11-20 17:16 UTC, yeshamavani commented on services/audit-service/src/controllers/audit.controller.ts
> +    public auditLogRepository: AuditLogRepository | AuditLogSequelizeRepository,
sequelize controller extends juggler controller and we need to update the type of it. and since currently the juggler controller only expects juggler repo as its type we need to provide both the types.
To avoid duplicate code we are just extending it rather than writing the entire code again.

2023-11-20 17:17 UTC, yeshamavani commented
@Surbhi-sharma1  code smell

2023-11-20 17:24 UTC, yeshamavani requested changes

2023-11-20 17:24 UTC, yeshamavani commented on .czferc.js
> +  {name: 'sequelize'},
??

2023-11-20 17:24 UTC, yeshamavani commented on services/audit-service/README.md
> +1. Change the import statements from `@sourceloop/audit-service` to `@sourceloop/audit-service/sequelize`. This can be done easily with your IDEs find and replace feature.
yes..

2023-11-20 17:24 UTC, yeshamavani commented on services/audit-service/src/sequelize.component.ts
> +    ];
services and providers binded correctly ?

2023-11-20 17:24 UTC, yeshamavani commented on services/audit-service/src/services/sequelize/audit-log-export.service.ts
why do we need this service 
no repository used

2023-11-20 17:24 UTC, yeshamavani commented on services/audit-service/src/services/sequelize/column-builder.service.ts
same .. do we really need this

2023-11-20 17:24 UTC, yeshamavani commented on services/audit-service/src/services/sequelize/query-selected-files.service.ts
same

2023-11-21 07:06 UTC, Surbhi-sharma1 commented on services/audit-service/src/sequelize.component.ts
> +    ];
Yes.

2023-11-21 07:07 UTC, Surbhi-sharma1 commented on services/audit-service/src/services/sequelize/audit-log-export.service.ts
Removed.

2023-11-21 07:07 UTC, Surbhi-sharma1 commented on services/audit-service/src/services/sequelize/column-builder.service.ts
Done with the changes

2023-11-21 07:07 UTC, Surbhi-sharma1 commented on services/audit-service/src/services/sequelize/query-selected-files.service.ts
removed this file

2023-12-05 09:48 UTC, yeshamavani requested changes

2023-12-05 09:48 UTC, yeshamavani commented on services/audit-service/README.md
> +2. Use the `SequelizeDataSource` in your audit datasource as the parent class. Refer [this](https://www.npmjs.com/package/@loopback/sequelize#step-1-configure-datasource) for more.
can you add an example here just like we have juggler DS.

2023-12-05 09:48 UTC, yeshamavani commented on services/audit-service/src/__tests__/utils/getBaseClass.ts
are we using this class now?

2023-12-06 12:31 UTC, samarpan-b approved these changes

2023-12-07 05:28 UTC, Surbhi-sharma1 commented
**Refering PR**  for Sequelize integration in Audit Service
https://github.com/sourcefuse/loopback4-microservice-catalog/pull/1824

2023-12-07 05:28 UTC, closed without merging