feat(authentication-service): maintain the entries for active users when a user login to the app
sourcefuse/loopback4-microservice-catalog pull request #1425
Opened 2023-05-23 17:41 UTC by yeshamavani

gh-1424

## Description

Whenever a user logs-in to the system we make an entry for the user in the active users table
Even if there is an error while adding the entry we do not throw an exception we just log this as this should not break the existing functionality.

Fixes #1424 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-24 07:10 UTC, samarpanB requested changes

2023-05-24 07:10 UTC, samarpanB commented on services/authentication-service/migrations/sqls/20230523175343-active-users-up.sql
> +CREATE TABLE main.active_users (
table name is wrong. It should be named as login_activity

2023-05-24 07:10 UTC, samarpanB commented on services/authentication-service/migrations/sqls/20230523175343-active-users-up.sql
> +		tenant_id				text NOT NULL,
tenant id may not be there for every app

2023-05-24 07:10 UTC, samarpanB commented on services/authentication-service/migrations/sqls/20230523175343-active-users-up.sql
> +		login_time				timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
We need to track more data like, browser, ip address (encrypted), success or error, etc. Refer this - https://www.databasezone.com/samples/User/index.htm#LoginAttempt

2023-05-24 07:10 UTC, samarpanB commented on services/authentication-service/src/controllers/active-users.controller.ts
> +export class ActiveUsersController {
This entire controller does not make sense at all. It cannot be active users. For active users u need to add BL as well.

2023-05-24 07:10 UTC, samarpanB commented on services/authentication-service/src/component.ts
> +    this.application.bind(AuthServiceBindings.ActorIdKey).to('id');
why 'id' ?

2023-05-24 07:10 UTC, samarpanB commented on services/authentication-service/src/models/active-users.model.ts
> +  settings: {strict: true},
remove this

2023-05-24 07:10 UTC, samarpanB commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      const actor = user[this.actorKey]?.toString() ?? '0';
We need to track access and refresh event separately

2023-05-25 06:58 UTC, yeshamavani commented on services/authentication-service/migrations/sqls/20230523175343-active-users-up.sql
> +		tenant_id				text NOT NULL,
then should we add the defaultTenantId?

2023-05-30 15:10 UTC, yeshamavani commented on services/authentication-service/src/controllers/active-users.controller.ts
> +export class ActiveUsersController {
done

2023-05-30 15:10 UTC, yeshamavani commented on services/authentication-service/src/component.ts
> +    this.application.bind(AuthServiceBindings.ActorIdKey).to('id');
default will be userId but the field is configurable.

2023-05-30 15:12 UTC, yeshamavani commented on services/authentication-service/src/models/active-users.model.ts
> +  settings: {strict: true},
done

2023-05-30 15:12 UTC, yeshamavani commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      const actor = user[this.actorKey]?.toString() ?? '0';
tracking access, relogin and logout separately

2023-06-01 09:02 UTC, samarpan-b requested changes

2023-06-01 09:02 UTC, samarpan-b commented on services/authentication-service/src/controllers/login-activity.controller.ts
> +    @param.path.string('range') range: string,
use enum for range

2023-06-01 09:02 UTC, samarpan-b commented on services/authentication-service/src/controllers/login-activity.controller.ts
> +        date = item.loginTime.toISOString().split('T')[0];
use moment for date-time calculations

2023-06-01 11:56 UTC, yeshamavani commented on services/authentication-service/src/controllers/login-activity.controller.ts
> +    @param.path.string('range') range: string,
done

2023-06-01 12:37 UTC, yeshamavani commented on services/authentication-service/src/modules/auth/logout.controller.ts
> +      console.log(e.toString());
not needed was for testing 
removed.

2023-06-02 05:21 UTC, yeshamavani commented on services/authentication-service/src/models/login-activity.model.ts
> +  tokenPayload?: object;
done

2023-06-02 05:21 UTC, yeshamavani commented on services/authentication-service/src/models/login-activity.model.ts
> +  ipAddress: string;
done

2023-06-02 07:41 UTC, yeshamavani commented on services/authentication-service/src/controllers/login-activity.controller.ts
> +        date = item.loginTime.toISOString().split('T')[0];
done

2023-06-02 10:13 UTC, samarpan-b commented on services/authentication-service/src/controllers/login-activity.controller.ts
> +        date = `${year}-${month}`;
You can use format here too

2023-06-02 10:13 UTC, samarpan-b commented on services/authentication-service/src/enums/login-type.enum.ts
> +export const enum ActiceUsersRange {
Spell check please

2023-06-02 10:15 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      const data: AnyObject = await this.getJwtPayload(user, authClient);
Why type added here ?

2023-06-02 10:16 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      this.markUserActivity(user, userTenant, {...data}, loginType);
Lets make this feature configurable. Take a boolean in component config and use that to check here

2023-06-02 10:19 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    if (encryptionKey) {
In next PR, move this encryption part to a provider and let consumer override it if needed.

2023-06-02 11:51 UTC, yeshamavani commented on sandbox/auth-ms-basic-example/package.json
> +    "i": "^0.3.7",
mistake

2023-06-02 12:53 UTC, yeshamavani commented on services/authentication-service/src/controllers/login-activity.controller.ts
> +        date = `${year}-${month}`;
done

2023-06-02 12:53 UTC, yeshamavani commented on services/authentication-service/src/enums/login-type.enum.ts
> +export const enum ActiceUsersRange {
done

2023-06-05 15:02 UTC, samarpan-b commented on sandbox/auth-ms-basic-example/package.json
> +    "i": "^0.3.7",
its still here

2023-06-05 18:22 UTC, samarpan-b approved these changes

2023-06-08 14:22 UTC, merged