fix(authentication-service): fix refresh token api creating access token with default tenant id.
sourcefuse/loopback4-microservice-catalog pull request #1431
Opened 2023-06-02 13:38 UTC by Surbhi-sharma1

fixed refresh token API creating access token with default tenant id.

GH-1430

## Description

- Added auth token switch API that will switch access token's tenant id with the required tenant id.

Fixes #1430 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-02 14:16 UTC, rashisf requested changes

2023-06-02 14:16 UTC, rashisf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      payload.authClient,
we need to pass tenant Id here as well which was the bug as after refreshing token, the new accessToken will again have the default tenant_id.

2023-06-02 14:16 UTC, rashisf commented on services/authentication-service/src/providers/jwt-payload.provider.ts
> +      tenantId?: string,
we can make this more generic if you want.
 You can use a free options parameter & there you can pass tenant_id as a property here

2023-06-05 04:54 UTC, Surbhi-sharma1 commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      payload.authClient,
Done

2023-06-05 08:14 UTC, samarpan-b requested changes

2023-06-05 08:14 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/login.controller.ts
> +  @post('/auth-token-switch', {
wrong url. It should be /auth/switch-token

2023-06-05 08:14 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      req,
only take tenantid here

2023-06-05 08:14 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    options?: JWTOptions,
Where is this interface ?

2023-06-05 09:12 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      payload.authClient,
Its in a separate parameter @rashisf

2023-06-05 09:15 UTC, Surbhi-sharma1 commented on services/authentication-service/src/modules/auth/login.controller.ts
> +  @post('/auth-token-switch', {
corrected its url.

2023-06-05 09:19 UTC, samarpan-b requested changes

2023-06-05 09:19 UTC, samarpan-b commented on services/authentication-service/src/providers/jwt-payload.provider.ts
> +      tenantId?: string,
We want it to be specific intentionally

2023-06-05 12:26 UTC, Surbhi-sharma1 commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      throw new HttpErrors.Unauthorized(AuthErrorKeys.InvalidCredentials);
Done.

2023-06-05 12:26 UTC, Surbhi-sharma1 commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      req.tenantId,
changes Done

2023-06-05 15:00 UTC, samarpan-b requested changes

2023-06-05 18:14 UTC, merged