feat(task-service): Task-1484 Task Service
sourcefuse/loopback4-microservice-catalog pull request #1487
Opened 2023-06-21 10:30 UTC by antriksha102

Task Service 

## Description

- [x] The requirement is to build a reusable, customisable and workflow based task service which creates some actionable tasks based upon various events happening via different micro-services in a distributed system.

Fixes # (issue)

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [x] Code conforms with the style guide

2023-08-21 08:35 UTC, shubhamp-sf requested changes

2023-08-21 08:35 UTC, shubhamp-sf commented on services/task-service/src/controllers/event-queue.controller.ts
> +    responses: {
Please specify concrete permissions, also other routes in this controller doesn't have auth enabled, are they supposed to be public routes?

2023-08-21 08:35 UTC, shubhamp-sf commented on services/task-service/src/controllers/task-service.controller.ts
> +}
Change the base URL to something that states an entity, (maybe just`/tasks` as baseUrl).

Also please use specific permissions for this route unless it's intended to be accessible for all.

2023-08-21 08:35 UTC, shubhamp-sf commented on services/task-service/src/keys.ts
> +  );
Please append `task` after all the BINDING_PREFIX literal.

Eg.

```ts
${BINDING_PREFIX}.task.custom_task.runner`,
```

2023-08-21 08:35 UTC, shubhamp-sf commented on services/task-service/src/models/event-workflow-mapping.model.ts
> +    type: 'string',
Please use `CoreEntity` as the extending class from `@sourceloop/core`.
This will ensure safe types without the useless constructor smell.
 Example: https://github.com/sourcefuse/loopback4-microservice-catalog/blob/8df9f0d1bf16d1354d883d225b068e9beeae9d6f/packages/cache/src/__tests__/acceptance/fixtures/product.model.ts#L10

2023-08-21 08:35 UTC, shubhamp-sf commented on services/task-service/src/models/event.model.ts
> +export class Events extends Entity {
Same here as well.

2023-08-21 08:35 UTC, shubhamp-sf commented on services/task-service/src/models/message.model.ts
> +  @property({
Is this a DTO?

2023-08-21 08:35 UTC, shubhamp-sf commented on services/task-service/src/models/task-work-flow-mapping.model.ts
> +  @property({
Please use `CoreEntity` as the extending class from `@sourceloop/core`.
This will ensure safe types without the useless constructor smell.
 Example: https://github.com/sourcefuse/loopback4-microservice-catalog/blob/8df9f0d1bf16d1354d883d225b068e9beeae9d6f/packages/cache/src/__tests__/acceptance/fixtures/product.model.ts#L10

2023-08-21 08:35 UTC, shubhamp-sf commented on services/task-service/src/models/tasks.model.ts
> +export class Tasks extends Entity {
Ditto.

2023-08-21 08:35 UTC, shubhamp-sf commented on services/task-service/src/services/camunda.service.ts
> +      method: 'GET',
Can we take this from binding config instead of ENV var?

Either-way please mention about configs in the README.

2023-08-21 13:35 UTC, akshatdubeysf commented on services/task-service/src/controllers/event-queue.controller.ts
> +      await this.eventQueueService.enqueueEvent(Events);
This seems to differ from the TDD, why is this part of the task service, and why is this expecting events over rest?

2023-08-21 13:36 UTC, akshatdubeysf commented on services/task-service/src/controllers/task-service.controller.ts
> +    Tasks: AnyObject,
Why?

2023-08-21 13:37 UTC, akshatdubeysf commented on services/task-service/src/controllers/task-service.controller.ts
> +    private readonly taskOpsService: TaskOperationService,
Can we rely on abstractions to make the code more flexible? So maybe have an interface for operation service and use that here, and bind a default class following that interface.

2023-08-21 13:40 UTC, akshatdubeysf commented on services/task-service/src/controllers/task-service.controller.ts
> +      await this.webhookService.addToSubscription(
The subscription only requires a URL? no secret/id? how would the consumer app ensure that the actual service is hitting there open endpoint?

2023-08-21 13:42 UTC, akshatdubeysf commented on services/task-service/src/models/event.model.ts
> +    required: true,
descriptions

2023-08-21 13:42 UTC, akshatdubeysf commented on services/task-service/src/models/event-workflow-mapping.model.ts
> +    name: 'event_key',
descriptions

2023-08-21 13:43 UTC, akshatdubeysf commented on services/task-service/src/models/event.model.ts
> +@model()
description

2023-08-21 13:44 UTC, akshatdubeysf commented on services/task-service/src/models/message.model.ts
> +    type: 'any',
you mean object? and is there no structure at all?

2023-08-21 13:44 UTC, akshatdubeysf commented on services/task-service/src/models/tasks.model.ts
> +  priority: string;
Priority is a string?

2023-08-21 13:47 UTC, akshatdubeysf commented on services/task-service/src/providers/connector.provider.ts
> +export class Connector implements Provider<EventQueueConnector> {
Name can be a bit more specific

2023-08-21 13:48 UTC, akshatdubeysf commented on services/task-service/src/providers/connector.provider.ts
> +    // Example: this.connector.disconnect(settings);
Looks like this should been an interface, not a class

2023-08-21 13:49 UTC, akshatdubeysf commented on services/task-service/src/repositories/event.repository.ts
> +export class EventRepository extends DefaultCrudRepository<
user modify crud repo

2023-08-21 13:49 UTC, akshatdubeysf commented on services/task-service/src/repositories/task.repository.ts
> +export class TaskRepository extends DefaultCrudRepository<
user modify crud repo

2023-08-21 13:51 UTC, akshatdubeysf commented on services/task-service/src/services/camunda.service.ts
> +    return this.http.postFormData<T>(`${this.baseUrl}/deployment/create`, form);
Why is all this here? shouldn't this be using the existing bpmn service? and for that it should be a simple rest wrapper?

2023-08-21 13:53 UTC, akshatdubeysf commented on services/task-service/src/services/event-processor.service.ts
> +    private readonly eventRepo: EventRepository,
all these should be abstractions ideally

2023-08-21 13:54 UTC, akshatdubeysf commented on services/task-service/src/models/event.model.ts
> +  @property({
Why is the class name plural?

2023-08-21 13:54 UTC, akshatdubeysf commented on services/task-service/src/models/tasks.model.ts
> +  @property({
Why is the classname plural?

2023-08-21 13:55 UTC, akshatdubeysf commented on services/task-service/src/services/event-queue.service.ts
> +    connection.onEvent((event: Events) => {});
What?

2023-08-21 14:02 UTC, akshatdubeysf commented on services/task-service/src/services/event-queue.service.ts
> +        }
now why is this specific to SQS? and if it is, nothing the class name suggests that.

2023-08-21 14:03 UTC, akshatdubeysf commented on services/task-service/src/services/task-db.service.ts
> +    await this.taskRepo.create({
Why? why not just override methods in the repository?

2023-08-21 14:09 UTC, akshatdubeysf commented on services/task-service/src/services/task-operation.service.ts
> +          await this.workflowOpsService.execWorkflow(
await in a loop?

2023-08-21 14:09 UTC, akshatdubeysf commented on services/task-service/src/services/task-operation.service.ts
> +        await this._registerOrUpdateCommand(task, {key, payload, name, id});
awaiting in a loop?

2023-08-21 14:10 UTC, akshatdubeysf commented on services/task-service/src/services/task-operation.service.ts
> +    const tpf = this._createTaskProcessorFunction(data.payload, task);
better variable name

2023-08-21 14:13 UTC, akshatdubeysf commented on services/task-service/src/services/task-operation.service.ts
> +        if (type === TaskServiceNames.UPDATE && cmd) {
I am confused, why do we have workers for BPMN here?

2023-08-21 14:15 UTC, akshatdubeysf commented on services/task-service/src/services/webhook.service.ts
> +          await this.httpService.post(url, data);
again, await in a loop

2023-08-21 14:21 UTC, akshatdubeysf commented on services/task-service/src/models/event.model.ts
> +  payload: AnyObject;
Shouldn't this be generic

2023-08-23 14:04 UTC, rahulvsf commented on services/task-service/src/models/tasks.model.ts
> +  priority: string;
yes, this priority is not camunda specific

2023-08-23 14:05 UTC, rahulvsf commented on services/task-service/src/models/message.model.ts
> +    type: 'any',
yes object. and it is dynamic

2023-08-23 14:05 UTC, rahulvsf commented on services/task-service/src/models/event.model.ts
> +  @property({
resolved

2023-08-23 14:05 UTC, rahulvsf commented on services/task-service/src/models/tasks.model.ts
> +  @property({
resolved

2023-08-23 14:06 UTC, rahulvsf commented on services/task-service/src/services/task-operation.service.ts
> +        await this._registerOrUpdateCommand(task, {key, payload, name, id});
resolved

2023-08-23 14:07 UTC, rahulvsf commented on services/task-service/src/services/webhook.service.ts
> +          await this.httpService.post(url, data);
resolved

2023-08-23 14:07 UTC, rahulvsf commented on services/task-service/src/models/event.model.ts
> +  payload: AnyObject;
not really, because the consumer will not define any types

2023-08-23 14:08 UTC, rahulvsf commented on sandbox/task-example/README.md
> +
writing in readme

2023-08-23 14:08 UTC, rahulvsf commented on services/task-service/README.md
> +### Working and Flow
readme in progress

2023-08-23 14:09 UTC, rahulvsf commented on services/task-service/package.json
> +  "description": "Task microservice",
added

2023-08-23 14:10 UTC, rahulvsf commented on services/task-service/src/component.ts
> +    });
not required, removed

2023-08-23 14:10 UTC, rahulvsf commented on services/task-service/src/controllers/event-queue.controller.ts
> +    responses: {
enabled auth and added permission

2023-08-23 14:11 UTC, rahulvsf commented on services/task-service/src/models/event-workflow-mapping.model.ts
> +    type: 'string',
changed

2023-08-23 14:11 UTC, rahulvsf commented on services/task-service/src/models/event.model.ts
> +export class Events extends Entity {
changed

2023-08-23 14:11 UTC, rahulvsf commented on services/task-service/src/models/message.model.ts
> +  @property({
yes, changed

2023-08-23 14:11 UTC, rahulvsf commented on services/task-service/src/models/task-work-flow-mapping.model.ts
> +  @property({
changed

2023-08-23 14:11 UTC, rahulvsf commented on services/task-service/src/models/tasks.model.ts
> +export class Tasks extends Entity {
changed

2023-08-23 14:13 UTC, rahulvsf commented on services/task-service/src/controllers/task-service.controller.ts
> +    Tasks: AnyObject,
changed to DTO

2023-08-23 14:13 UTC, rahulvsf commented on services/task-service/src/controllers/task-service.controller.ts
> +      await this.webhookService.addToSubscription(
added api secret / key

2023-08-23 14:13 UTC, rahulvsf commented on services/task-service/src/controllers/task-service.controller.ts
> +    } catch (e) {
yes, it should

2023-08-23 14:13 UTC, rahulvsf commented on services/task-service/src/models/event.model.ts
> +    required: true,
added

2023-08-23 14:13 UTC, rahulvsf commented on services/task-service/src/models/event-workflow-mapping.model.ts
> +    name: 'event_key',
added

2023-08-23 14:13 UTC, rahulvsf commented on services/task-service/src/models/event.model.ts
> +@model()
added

2023-08-23 14:14 UTC, rahulvsf commented on services/task-service/src/services/task-operation.service.ts
> +          await this.workflowOpsService.execWorkflow(
resolved to promises

2023-08-31 06:59 UTC, samarpan-b commented on services/task-service/src/commands/task-processor.command.ts
> +export class TaskProcessorCommand implements ICommand {
I dont understand this command. And why is this having injected params ? That is causing it to tight couple.

2023-08-31 07:01 UTC, samarpan-b commented on services/task-service/src/controllers/api-key.controller.ts
> +  @post('/api-keys')
We need application client details as payload in this. A POST API without body doesn't make sense

2023-09-04 05:26 UTC, rahulvsf commented on services/task-service/src/services/task-operation.service.ts
> +    const tpf = this._createTaskProcessorFunction(data.payload, task);
done

2023-09-04 05:31 UTC, rahulvsf commented on services/task-service/src/repositories/task.repository.ts
> +export class TaskRepository extends DefaultCrudRepository<
done

2023-09-04 05:31 UTC, rahulvsf commented on services/task-service/src/repositories/event.repository.ts
> +export class EventRepository extends DefaultCrudRepository<
done

2023-09-04 05:33 UTC, rahulvsf commented on services/task-service/src/keys.ts
> +  );
done

2023-09-04 05:38 UTC, rahulvsf commented on services/task-service/src/services/task-db.service.ts
> +    await this.taskRepo.create({
to keep the db operations seperate

2023-09-04 05:42 UTC, rahulvsf commented on services/task-service/src/providers/connector.provider.ts
> +export class Connector implements Provider<EventQueueConnector> {
done

2023-09-04 05:47 UTC, rahulvsf commented on services/task-service/src/providers/base-bpmn-runner.provider.ts
> +  abstract getWorkerFunctions(): Record<string, ProccessorFunction>;
done

2023-09-04 05:48 UTC, rahulvsf commented on services/task-service/migrations/sqls/20230808104436-init-up.sql
> +    modified_on         timestamptz DEFAULT current_timestamp NOT NULL,
currently we do not need this table

2023-09-04 05:49 UTC, rahulvsf commented on services/task-service/src/services/event-queue.service.ts
> +    connection.onEvent((event: Events) => {});
this is just a sample implementation for reference

2023-09-04 06:04 UTC, rahulvsf commented on services/task-service/src/controllers/task-service.controller.ts
> +}
done

2023-09-04 06:05 UTC, rahulvsf commented on services/task-service/src/controllers/event-queue.controller.ts
> +      await this.eventQueueService.enqueueEvent(Events);
it is part of task service, as we should ideally expose a connector to send over events.

2023-09-04 06:07 UTC, rahulvsf commented on services/task-service/src/providers/base-bpmn-runner.provider.ts
> +export abstract class BaseBpmnRunner implements Provider<TaskReturnMap> {
no, we don't bind it. fixed

2023-09-04 11:23 UTC, rahulvsf commented on services/task-service/src/services/event-queue.service.ts
> +        }
changed the class name, currently supports sqs

2023-09-04 11:30 UTC, rahulvsf commented on services/task-service/src/providers/connector.provider.ts
> +    // Example: this.connector.disconnect(settings);
interface already exists

2023-09-05 06:04 UTC, rahulvsf commented on services/task-service/package.json
> +    "@sourceloop/core": "^8.0.3",
updated

2023-09-05 06:04 UTC, rahulvsf commented on services/task-service/package.json
> +    "body-parser": "^1.20.0",
we don't need this

2023-09-05 06:07 UTC, rahulvsf commented on services/task-service/package.json
> +    "@loopback/service-proxy": "^6.1.1",
updated

2023-09-12 05:12 UTC, rahulvsf commented on services/task-service/src/controllers/api-key.controller.ts
> +  @post('/api-keys')
done

2023-09-14 13:30 UTC, rahulvsf commented on services/task-service/src/commands/task-processor.command.ts
> +export class TaskProcessorCommand implements ICommand {
This command basically runs the service tasks through node workers. It needs the params to call processTask method so that it can process the bpmn further ahead. The logic written by the consumer app through our exposed provider is plugged into this TaskProcessorCommand so that it can run that logic, for example - fetching users / assigning tasks etc.

2023-09-25 05:01 UTC, shubhamp-sf approved these changes
LGTM

2023-09-25 10:10 UTC, antriksha102 commented on services/task-service/src/services/camunda.service.ts
> +  baseUrl: string | undefined = '';
Why undefined here?

2023-09-25 12:04 UTC, samarpan-b requested changes

2023-09-25 14:35 UTC, rahulvsf commented on services/task-service/migration.js
> +const type = 'OIDC';
done

2023-09-25 14:35 UTC, rahulvsf commented on services/task-service/README.md
> +# [@sourceloop/task-service](https://github.com/sourcefuse/loopback4-microservice-catalog/tree/master/services/audit-service)
updated

2023-09-25 14:36 UTC, rahulvsf commented on services/task-service/src/services/camunda.service.ts
> +  baseUrl: string | undefined = '';
because `IWorkflowServiceConfig.workflowEngineBaseUrl` is of type `string | undefined`

2023-09-25 14:37 UTC, rahulvsf commented on services/task-service/src/enums/permission-key.enum.ts
> +  StartListening = 'StartListening',
done

2023-09-25 14:37 UTC, rahulvsf commented on services/task-service/src/controllers/api-key.controller.ts
> +  @post('/api-keys', {security: OPERATION_SECURITY_SPEC, responses: {}})
updated

2023-09-25 14:37 UTC, rahulvsf commented on services/task-service/src/controllers/event-queue.controller.ts
> +  @post(`${baseUrl}/enqueue-event`, {
changed

2023-09-25 14:37 UTC, rahulvsf commented on services/task-service/src/controllers/event-queue.controller.ts
> +  @get(`${baseUrl}/health-check`, {
changed

2023-09-25 14:38 UTC, rahulvsf commented on services/task-service/src/commands/task-processor.command.ts
> +export class TaskProcessorCommand implements ICommand {
added

2023-09-25 14:39 UTC, rahulvsf commented on services/task-service/src/models/event-workflow-mapping.model.ts
> +  name: 'event_workflow_mapping',
changed

2023-09-25 14:39 UTC, rahulvsf commented on services/task-service/src/models/event-workflow-mapping.model.ts
> +export class EventWorkflowMapping extends CoreEntity<EventWorkflowMapping> {
changed

2023-09-25 14:39 UTC, rahulvsf commented on services/task-service/src/models/event-workflow-mapping.model.ts
> +  createdBy?: string;
updated

2023-09-26 14:40 UTC, rahulvsf commented on services/task-service/src/controllers/event-queue.controller.ts
> +  async healthCheck(): Promise<AnyObject> {
updated

2023-09-26 14:41 UTC, rahulvsf commented on services/task-service/src/services/event-queue.service.ts
> +  async startListening(): Promise<void> {
it is actually connecting only. we don't need this for now

2023-09-26 14:41 UTC, rahulvsf commented on services/task-service/src/services/event-queue.service.ts
> +  async stopListening(): Promise<void> {
it is just disconnecting. updated.

2023-09-26 14:42 UTC, rahulvsf commented on services/task-service/src/services/event-queue.service.ts
> +    // Start listening to the SQS queue for incoming events
removed the SQS name from comment. Yes, consumer can use other queue, but we had used SQS so it remained in the comments.

2023-09-26 14:42 UTC, rahulvsf commented on sandbox/task-example/Dockerfile
> +FROM node:16-slim
updated

2023-09-26 14:42 UTC, rahulvsf commented on sandbox/task-example/package.json
> +    "@sourceloop/task-service": "file:sourceloop-task-service-0.0.1.tgz",
updated

2023-09-26 14:42 UTC, rahulvsf commented on sandbox/task-example/package.json
> +    "node": "16 || 18 || 19"
updated

2023-09-26 18:45 UTC, samarpan-b commented on services/task-service/src/models/task-work-flow-mapping.model.ts
> +  name: 'task_workflow_mappings',
same naming convention should be here too

2023-09-26 18:53 UTC, samarpan-b requested changes

2023-09-26 18:53 UTC, samarpan-b commented on services/task-service/src/services/event-queue.service.ts
> +            await this.eventProcessorService.processEvent(event);
This is still wrong. Move this inner function to a separate function and then return that function from map without async. and then use promise all.

2023-09-26 18:53 UTC, samarpan-b commented on services/task-service/src/services/task-db.service.ts
> +  public async addTaskToDB(task: Task) {
this function is doing nothing extra. We can directly use repo create function. No need of this method at all.

2023-09-26 18:53 UTC, samarpan-b commented on services/task-service/src/services/task-db.service.ts
> +  public async updateTask(key: string, task: Task) {
call this updateTaskStatus

2023-09-26 18:53 UTC, samarpan-b commented on services/task-service/src/services/task-operation.service.ts
> +            await this.taskDbService.addTaskToDB(task);
same issue. move all of this inner fn stuff to separate fn.

2023-09-27 03:20 UTC, rahulvsf commented on services/task-service/src/models/task-work-flow-mapping.model.ts
> +  name: 'task_workflow_mappings',
updated

2023-09-27 03:20 UTC, rahulvsf commented on services/task-service/src/services/task-db.service.ts
> +  public async addTaskToDB(task: Task) {
updated

2023-09-27 03:20 UTC, rahulvsf commented on services/task-service/src/services/task-db.service.ts
> +  public async updateTask(key: string, task: Task) {
updated

2023-09-27 03:20 UTC, rahulvsf commented on services/task-service/src/services/task-operation.service.ts
> +            await this.taskDbService.addTaskToDB(task);
updated

2023-09-27 03:21 UTC, rahulvsf commented on services/task-service/src/services/event-queue.service.ts
> +            await this.eventProcessorService.processEvent(event);
made a separate fn

2023-09-27 05:01 UTC, samarpan-b commented on services/task-service/src/controllers/task-service.controller.ts
> +    private readonly taskOpsService: TaskOperationService,
Please do these abstractions as suggested by @akshatdubeysf in a separate PR. For now, I am approving this with a condition that these abstractions will be added in next 30 days.

2023-09-27 05:01 UTC, samarpan-b approved these changes

2023-10-03 14:56 UTC, rahulvsf commented on services/task-service/src/controllers/task-service.controller.ts
> +    private readonly taskOpsService: TaskOperationService,
Yes, will raise a separate PR

2023-10-04 15:22 UTC, merged