feat(audit-service): export feature added
sourcefuse/loopback4-microservice-catalog pull request #1500
Opened 2023-06-23 11:50 UTC by arpit1503khanna

## Description
export feature added

Fixes # GH-1449

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-23 12:44 UTC, shubhamp-sf requested changes

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/component.ts
> +      ExportLogsController,
Merge this into audit controller.

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/component.ts
> +    this.providers[ColumnBuilderServiceBindings.BUILD_COLUMN.key] =
```suggestion
    this.providers[ColumnBuilderServiceBindings.COLUMN_BUILDER.key] =
```

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/controllers/audit.controller.ts
>        })) as Job;
Why `as Job`?

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/controllers/export-logs.controller.ts
> +        operation: 'EXPORT',
Change this to enum.

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/controllers/export-logs.controller.ts
> +      })) as Job;
```suggestion
      }));
```

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/controllers/export-logs.controller.ts
> +  async find(
```suggestion
  async export(
```

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/controllers/export-logs.controller.ts
> +  ): Promise<object> {
be more specific.

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/enums/operation-key.enum.ts
> +  Query = 'QUERY',
Capitalize the keys

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/keys.ts
> +  export const BUILD_COLUMN = BindingKey.create<ColumnBuilderFn>(
reflect the name change here too

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +    return async (data: any[]) => {
Don't use any

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +    const targetDirectory = path.join(targetDirectoryPath, '/Export-logs/');
```suggestion
    const targetDirectory = path.join(targetDirectoryPath, '/export-logs/');
```

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +    const fileName = `auditLog_records${new Date().toISOString()}.xlsx`;
```suggestion
    const fileName = `auditlog-records${new Date().toISOString()}.xlsx`;
```

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +    const worksheetName = 'auditlogs';
```suggestion
    const worksheetName = 'Audit Logs';
```

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +    const worksheetColumnNames = Object.keys(data[0]);
Handle empty data cases.

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +    fs.mkdir(targetDirectory, error =>
wait for it be completed.

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/services/column-builder.service.ts
> +  async columnBuilder(auditLogs: AuditLog[]): Promise<any[]> {
Don't use any.

2023-06-23 12:44 UTC, shubhamp-sf commented on services/audit-service/src/types.ts
> +export type ColumnBuilderFn = (auditLogs: AuditLog[]) => Promise<any[]>;
Any can be avoided here.

2023-06-24 13:13 UTC, shubhamp-sf requested changes

2023-06-24 13:13 UTC, shubhamp-sf commented on services/audit-service/src/services/job-processing.service.ts
>        await this.jobRepository.updateById(jobId, newJob);
Don't we just need to update the status? Why pass all other options as well?

2023-06-24 13:13 UTC, shubhamp-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +    const fileName = `auditLog-records${new Date().toISOString()}.xlsx`;
```suggestion
    const fileName = `audit-logs-${new Date().toISOString()}.xlsx`;
```

2023-06-24 13:13 UTC, shubhamp-sf commented on services/audit-service/src/keys.ts
> +    `${BINDING_PREFIX}.audit.columnBuild`,
```suggestion
    `${BINDING_PREFIX}.audit.columnBuilder`,
```

2023-06-24 13:13 UTC, shubhamp-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +        ? this.logger.error('Error in Export Logs Directory')
```suggestion
        ? this.logger.error(`An error occurred while creating export logs directory: ${error.toString()}`)
```

2023-06-24 13:13 UTC, shubhamp-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +        ? this.logger.error('Error in Export Logs Directory')
If the directory creation is failed, why is execution not being stopped?

Currently it'll just log the message and continue to prepare the excel and try writing that file.

2023-06-24 13:13 UTC, shubhamp-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +      throw new Error('Path to target directory not defined');
```suggestion
      throw new Error('Path to the target directory to export the file is not defined.');
```

2023-06-24 13:13 UTC, shubhamp-sf commented on services/audit-service/src/controllers/export-logs.controller.ts
> +      return {message: 'File exported successfully'};
```suggestion
      return {message: 'Audit logs exported successfully.'};
```

2023-06-24 19:00 UTC, arpit1503khanna commented on services/audit-service/src/services/audit-log-export.service.ts
> +    const worksheetColumnNames = Object.keys(data[0]);
Actually I was handling it in the job processing service , from where this export service is actually called. But I have made the requested change in the exportService

2023-06-24 19:02 UTC, arpit1503khanna commented on services/audit-service/src/component.ts
> +      ExportLogsController,
When I did that , swagger did not displayed controller corresponding to Archive and Export controller

2023-06-25 05:28 UTC, shubhamp-sf commented on services/audit-service/src/services/audit-log-export.service.ts
> +    const worksheetColumnNames = Object.keys(data[0]);
Handling it there doesn't solves the issue, The edge case you need to handle is if data is present but have no values. Simply an empty array.

Currently you're doing it like this
```ts
if (!data) {
      return;
}
```

Which doesn't solves it as empty array will still be truthy.

2023-06-27 05:06 UTC, shubhamp-sf requested changes

2023-06-27 05:06 UTC, shubhamp-sf commented on services/audit-service/src/controllers/export-logs.controller.ts
> +        description: 'Array of AuditLog model instances',
Wrong description.

2023-06-27 05:09 UTC, shubhamp-sf commented on services/audit-service/src/component.ts
> +      ExportLogsController,
Then try to fix it, there must be some configuration issues.

2023-06-27 05:09 UTC, arpit1503khanna commented on services/audit-service/src/services/audit-log-export.service.ts
> +    const fileName = `auditLog-records${new Date().toISOString()}.xlsx`;
done

2023-06-27 05:10 UTC, arpit1503khanna commented on services/audit-service/src/__tests__/fixtures/providers/column-builder.service.ts
> +
done

2023-06-27 05:11 UTC, arpit1503khanna commented on services/audit-service/src/services/audit-log-export.service.ts
> +    const worksheetColumnNames = Object.keys(data[0]);
done

2023-06-27 05:15 UTC, arpit1503khanna commented on services/audit-service/README.md
> +
done

2023-06-27 05:15 UTC, arpit1503khanna commented on services/audit-service/README.md
> +NOTE: The destination path specified for the exported file in the `env` file must exist.
done

2023-06-27 05:17 UTC, arpit1503khanna commented on services/audit-service/src/__tests__/helpers/db.helper.ts
> +  // ColumnBuilderProvider,
done

2023-06-27 05:18 UTC, arpit1503khanna commented on services/audit-service/src/__tests__/unit/export-log.controller.unit.ts
> +describe('POST /audit-logs/archive', () => {
done

2023-06-27 05:19 UTC, arpit1503khanna commented on services/audit-service/src/__tests__/helpers/db.helper.ts
> +// import {logger} from 'handlebars';
done

2023-06-27 05:21 UTC, arpit1503khanna commented on services/audit-service/src/controllers/export-logs.controller.ts
> +        description: 'Array of AuditLog model instances',
done

2023-07-04 12:26 UTC, shubhamp-sf approved these changes

2023-07-04 12:26 UTC, merged