feat(survey-service): adds survey entities crud
sourcefuse/loopback4-microservice-catalog pull request #1510
Opened 2023-06-26 12:31 UTC by abhijeetrai5

## Description

Adds crud for survey entities
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-29 14:40 UTC, shubhamp-sf requested changes
Apart from these please include some test cases for this service.

2023-06-29 14:40 UTC, shubhamp-sf commented on services/survey-service/README.md
Mention more details about this service, what it provides how the typical API flow look like. What are different terms such as template in this service's context refer to, etc.

Also include the OpenAPI spec link at the bottom.

2023-06-30 05:05 UTC, yeshamavani commented on services/survey-service/src/repositories/survey-responder.repository.ts
> +    const existingReponderCount = await super.count({
typo

2023-07-03 03:54 UTC, Swati0077 commented on services/survey-service/package.json
> +    "jsdom": "^19.0.0",
In survey we have a field called surveyText . It's input is taken in editor.(We used CK editor in CLM)
Thats why for validation purpose we needed to parse it.

2023-07-03 04:12 UTC, Swati0077 commented on services/survey-service/src/controllers/option.controller.ts
> +    const existingOption = await this.optionsRepository.findOne({
It is just for validation purpose.
Here, we are just checking if the option we are going to update exists in the table or not.
If not we throw the error.

2023-07-03 04:15 UTC, Swati0077 commented on services/survey-service/src/controllers/question-template.controller.ts
> +      id,
because we needed count and deleteAll returns the count.
(to check if that entity is deleted or not adn throw error if required)
Delete by Id returns nothing.

2023-07-03 04:16 UTC, Swati0077 commented on services/survey-service/src/controllers/section.controller.ts
> +    if (updatedCount.count === 0) {
because we needed count and updateAll returns the count.
(to check if that entity isupdated or not and throw error if required)
update by Id returns nothing.

2023-07-03 04:30 UTC, Swati0077 commented on services/survey-service/src/controllers/survey-question.controller.ts
> +      },
because we needed count and updateAll returns the count.
(to check if that entity is updated or not and throw error if required)
update by Id returns nothing.

2023-07-03 04:30 UTC, Swati0077 commented on services/survey-service/src/controllers/survey-question.controller.ts
> +      },
because we needed count and updateAll returns the count.
(to check if that entity isupdated or not and throw error if required)
update by Id returns nothing.

2023-07-03 04:37 UTC, Swati0077 commented on services/survey-service/src/controllers/survey.controller.ts
> +    const deleteCount = await this.surveyRepository.deleteAll({
because we needed count and deleteAll returns the count for validation purpose.
(to check if that entity is deleted or not and throw error if required)
delete by Id returns nothing.

2023-07-03 04:39 UTC, Swati0077 commented on services/survey-service/src/controllers/survey-question.controller.ts
> +      // eslint-disable-next-line @typescript-eslint/no-floating-promises
For validation purpose it is being explicity checked.

2023-07-03 05:08 UTC, Swati0077 commented on services/survey-service/src/controllers/section.controller.ts
> +    if (updatedCount.count === 0) {
We are using updateAll .because we are doing it for a specific survey.
We need to provide surveyId in where clause.
If we don't do that then user can update sections with other surveyId

2023-07-03 05:32 UTC, Swati0077 commented on services/survey-service/src/controllers/section.controller.ts
> +    if (updatedCount.count === 0) {
We use updateAll function because we make sure that we are updating sections of a particular survey only.
so surveyId needs to be added to where clause.

2023-07-03 05:34 UTC, Swati0077 commented on services/survey-service/src/controllers/survey-question.controller.ts
> +      },
We use updateAll function because we make sure that we are updating surveyQuestions of a particular survey only.
so surveyId needs to be added to where clause.

2023-07-03 05:35 UTC, Swati0077 commented on services/survey-service/src/controllers/survey-question.controller.ts
> +      },
We use updateAll function because we make sure that we are updating surveyQuestions of a particular survey only.
so surveyId needs to be added to where clause.

2023-07-03 05:37 UTC, Swati0077 commented on services/survey-service/src/controllers/survey-responder.controller.ts
> +  async checkIfResponderAddedInActiveCycle(surveyResponder: SurveyResponder) {
done

2023-07-03 05:37 UTC, Swati0077 commented on services/survey-service/src/controllers/survey.controller.ts
> +    const deleteCount = await this.surveyRepository.deleteAll({
done

2023-07-03 05:37 UTC, Swati0077 commented on services/survey-service/src/repositories/survey-responder.repository.ts
> +    const existingReponderCount = await super.count({
done

2023-07-03 05:37 UTC, Swati0077 commented on services/survey-service/src/controllers/question-template.controller.ts
> +      id,
done

2023-07-03 05:38 UTC, Swati0077 commented on services/survey-service/src/controllers/option.controller.ts
> +    const existingOption = await this.optionsRepository.findOne({
changed

2023-07-03 08:14 UTC, Swati0077 commented on services/survey-service/package.json
> +    "node": "14 || 16 || 17 || 18"
done

2023-07-03 08:14 UTC, Swati0077 commented on services/survey-service/package.json
> +  "author": "Swati0077 <swati.prashar@sourcefuse.com>",
done

2023-07-14 07:52 UTC, shubhamp-sf commented on services/survey-service/README.md
> +Learn more at https://loopback.io/doc/en/lb4/Life-cycle.html
remove these lines or comment them out it's conflicting with code highlighting

2023-07-14 07:52 UTC, shubhamp-sf commented on services/survey-service/README.md
> +  import {SurveyServiceComponent} from '@sourceloop/audit-service';
```suggestion
  import {SurveyServiceComponent} from '@sourceloop/survey-service';
```

2023-07-14 07:57 UTC, shubhamp-sf commented on services/survey-service/src/controllers/ping.controller.ts
remove this file

2023-07-14 09:26 UTC, Swati0077 commented on services/survey-service/README.md
> +  import {SurveyServiceComponent} from '@sourceloop/audit-service';
done

2023-07-14 09:26 UTC, Swati0077 commented on services/survey-service/README.md
> +Learn more at https://loopback.io/doc/en/lb4/Life-cycle.html
commented

2023-07-14 14:12 UTC, shubhamp-sf approved these changes

2023-07-14 14:15 UTC, merged