feat(authentication-service): add filter to include or exclude active users
sourcefuse/loopback4-microservice-catalog pull request #1518
Opened 2023-06-27 08:49 UTC by yeshamavani

gh-1517

## Description

Provide a flag to mark whether we would like to include or exclude the user. Also a array where we can pass the list of users whom we want to include/exclude.

Fixes #1517 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-03 04:43 UTC, samarpan-b requested changes

2024-01-03 04:43 UTC, samarpan-b commented on services/authentication-service/src/controllers/login-activity.controller.ts
> +      if (this.actorKey === 'id') {
what is this.actorKey ?

2024-01-03 04:43 UTC, samarpan-b commented on services/authentication-service/src/controllers/login-activity.controller.ts
> +    let actorIds: string[] = [];
Can we make this function as a provider so that consumers can configure it also, if they want ?

2024-01-03 05:41 UTC, yeshamavani commented on services/authentication-service/src/controllers/login-activity.controller.ts
> +      if (this.actorKey === 'id') {
since we wanted the actor column to be configurable user can set the actionKey to be id== userId
or userTenantId or any other field in AuthUser

2024-01-03 05:42 UTC, yeshamavani commented on services/authentication-service/src/controllers/login-activity.controller.ts
> +    let actorIds: string[] = [];
sure

2024-01-03 06:27 UTC, samarpan-b commented on services/authentication-service/src/controllers/login-activity.controller.ts
> +      if (this.actorKey === 'id') {
but why is it a class variable ?

2024-03-20 06:03 UTC, yeshamavani commented
Raised another PR with same changes as this one is very old and uses lerna and not npm workspaces.
https://github.com/sourcefuse/loopback4-microservice-catalog/pull/2049

2024-03-20 06:03 UTC, closed without merging