fix(authentication-service): submission of encrypted password in auth…
sourcefuse/loopback4-microservice-catalog pull request #1593
Opened 2023-08-03 04:47 UTC by Surbhi-sharma1

…entication service api

submission of encrypted password in authentication service api

GH-1592

## Description

Fixes #1592 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-03 06:48 UTC, yeshamavani requested changes

2023-08-03 06:48 UTC, yeshamavani commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      }
assign default value to old/newpassword from the request body and if the decryption key is present override it with the decrypted once

2023-08-03 06:48 UTC, yeshamavani commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      }
same

2023-08-03 06:48 UTC, yeshamavani commented on services/authentication-service/src/repositories/user.repository.ts
> +    let Password: string;
camel case

2023-08-03 10:13 UTC, Surbhi-sharma1 commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      }
Done

2023-08-03 10:13 UTC, Surbhi-sharma1 commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      }
Done

2023-08-03 10:13 UTC, Surbhi-sharma1 commented on services/authentication-service/src/repositories/user.repository.ts
> +    let Password: string;
Done

2023-08-08 05:44 UTC, yeshamavani requested changes
please implement it through a provider

2023-08-09 05:40 UTC, shubhamp-sf approved these changes

2023-08-09 07:12 UTC, yeshamavani commented
@Surbhi-sharma1  code smell

2023-08-09 10:49 UTC, merged