feat(chore): migrate to use npm workspaces
sourcefuse/loopback4-microservice-catalog pull request #1684
Opened 2023-09-08 05:54 UTC by Surbhi-sharma1

MIGRATION CHANGE:
migration-20211003143854- migrate to use npm workspaces

BREAKING CHANGE:
lerna bootstrap command will not be needed as npm  workspaces will  manage the same functionality.

GH-1673

## Description
Migrate to use npm workspaces

Fixes #1673 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-22 08:39 UTC, Surbhi-sharma1 commented on sandbox/chat-notification-socketio-example/services/notifications-service/src/application.ts
> -      useCustomPushProvider: true,
updated version in sandbox notification example

2023-09-22 08:39 UTC, Surbhi-sharma1 commented on package.json
> +  ]
Done

2023-09-25 16:37 UTC, yeshamavani approved these changes

2023-10-30 08:00 UTC, samarpan-b requested changes

2023-10-30 08:00 UTC, samarpan-b commented on services/audit-service/src/services/job-processing.service.ts
> +          // eslint-disable-next-line @typescript-eslint/prefer-nullish-coalescing
remove this disable eslint and fix the issue

2023-10-30 08:00 UTC, samarpan-b commented on services/bpmn-service/package.json
> +        "node": "16 || 17 || 18"
`"engines": {
    "node": "16 || 18 || 20"
  },`

2023-10-30 08:00 UTC, samarpan-b commented on services/user-tenant-service/src/__tests__/acceptance/tenant-group.controller.acceptance.ts
> +      PermissionKey.ViewGroupList,
Why this change ?

2023-10-30 08:00 UTC, samarpan-b commented on services/user-tenant-service/src/enums/permission-key.enum.ts
> +  CreateGroup = 'CreateGroup',
why this change ?

2023-10-30 08:23 UTC, Surbhi-sharma1 commented on services/user-tenant-service/src/__tests__/acceptance/tenant-group.controller.acceptance.ts
> +      PermissionKey.ViewGroupList,
Was getting lint issue of duplicate enum values

2023-10-30 08:35 UTC, samarpan-b commented on services/user-tenant-service/src/enums/permission-key.enum.ts
> +  CreateGroup = 'CreateGroup',
ok

2023-10-30 08:36 UTC, samarpan-b commented on services/user-tenant-service/src/__tests__/acceptance/tenant-group.controller.acceptance.ts
> +      PermissionKey.ViewGroupList,
ok

2023-10-31 10:49 UTC, shivamSF requested changes

2023-10-31 12:53 UTC, Surbhi-sharma1 commented on .prettierrc
> +{
ok

2023-10-31 12:54 UTC, Surbhi-sharma1 commented on package.json
> +    "packages/core/",
Ocr-parser is  excluded as its having angular dependency

2023-11-02 08:08 UTC, shivamSF approved these changes

2023-11-02 08:24 UTC, Surbhi-sharma1 commented on packages/cli/tsconfig.json
> +      "./node_modules/@types",
@types/jasmine and mocha was giving path related issues  in Cli build.

2023-11-02 08:38 UTC, samarpan-b approved these changes

2023-11-02 08:40 UTC, merged