fix(cli):  lambda files should only be generated if opted for cdk
sourcefuse/loopback4-microservice-catalog pull request #1699
Opened 2023-09-15 15:19 UTC by Tyagi-Sunny

lambda files should only be generated if opted for cdk

gh-1698

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-18 05:47 UTC, yeshamavani requested changes

2023-09-18 05:47 UTC, yeshamavani commented on packages/cli/src/generators/microservice/index.ts
> +      );
remove name

2023-09-18 06:08 UTC, Tyagi-Sunny commented on packages/cli/src/generators/microservice/index.ts
> +      );
done

2023-09-21 05:18 UTC, yeshamavani commented on packages/cli/src/generators/microservice/index.ts
> +      );
??
if this file is not needed then why are we creating it first place 
it should be created only if the user opts for it

2023-09-21 05:34 UTC, Tyagi-Sunny commented on packages/cli/src/generators/microservice/index.ts
> +      );
The file is located in the 'service/migration' folder. Migrations are copied from there. So, whether a user opts for CDK  or not, 'lambda.js' will be created in the 'package/migration/example-service' directory. The reason for keeping 'lambda.js' in the 'service/migration' folder is that 'lambda.js' is a fixed file required for running migrations on Lambda.

2023-09-22 05:29 UTC, yeshamavani approved these changes

2023-09-22 05:29 UTC, merged