refactor(user-tenant-service): update
sourcefuse/loopback4-microservice-catalog pull request #1703
Opened 2023-09-21 06:40 UTC by Tyagi-Sunny

update

MIGRATION CHANGE:
migration-20220607063927- update
migration-20220804102718- update
migration-20220906105133- update
migration-20210318100600- update
migration-20230905130235- update

gh-1696

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-21 14:54 UTC, yeshamavani commented on services/user-tenant-service/src/controllers/tenant.controller.ts
> +    ],
why two permissions of update and update own
does this allow to make updates cross tenant

2023-09-21 14:54 UTC, yeshamavani commented on services/user-tenant-service/src/controllers/user-credentials-user.controller.ts
> +  }
??

2023-10-04 06:50 UTC, yeshamavani commented
update the PR title and description

2023-10-04 06:58 UTC, yeshamavani commented on services/user-tenant-service/CHANGELOG.md
This file should not be deleted

2023-10-04 06:58 UTC, yeshamavani commented on services/user-tenant-service/README.md
??

2023-10-04 06:58 UTC, yeshamavani commented on services/user-tenant-service/database.json
??

2023-10-04 06:58 UTC, yeshamavani commented on services/user-tenant-service/src/component.ts
> +    private application: Application,
RestApplication

2023-10-06 10:21 UTC, akshatdubeysf requested changes

2023-10-06 10:21 UTC, akshatdubeysf commented on services/user-tenant-service/src/interceptors/tenant-interceptor.interceptor.ts
> +          'Access to different Tenant Not Allowed-',
why the hypen?

2023-10-06 10:21 UTC, akshatdubeysf commented on services/user-tenant-service/src/interceptors/user-tenant-interceptor.interceptor.ts
> +      const userTenantId = invocationCtx.args[0];
again same question, how do you know first argument would be userTenantId?

2023-10-06 10:21 UTC, akshatdubeysf commented on services/user-tenant-service/src/repositories/user.repository.ts
> +    super(User, dataSource);
Model should be replaceable

2023-10-06 11:24 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/__tests__/acceptance/tenant-group.controller.acceptance.ts
> -  it('return a group object when id is sent', async () => {
The test cases were not removed; they were deleted, and new ones were created. Some test case names are the same, so they are appearing as modified on GitHub because they were originally associated with the old logic.

2023-10-06 11:31 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/__tests__/acceptance/tenant-group.controller.acceptance.ts
> +    token = jwt.sign(testUser, 'test_secret', {
ok sir

2023-10-06 11:45 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/user-signup.controller.ts
> -﻿// Copyright (c) 2023 Sourcefuse Technologies
yes

2023-10-06 11:49 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/user-tenant.controller.ts
> +        description: 'Array of Tenant User is a part of',
descriptions of all apis, will be modified

2023-10-06 11:49 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/tenant-user.controller.ts
> +        description: 'Array of Tenant has many User',
ok sir

2023-10-06 11:51 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      // Add pre-invocation logic here
These interceptors are used so that, user should not enter id of group from different tenant

2023-10-06 11:53 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      const groupId = invocationCtx.args[0];
yes sir,
baseURL is '/groups/{id}/user'

2023-10-06 11:54 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      const groupRecord = groups.find(
ok sir

2023-10-06 11:56 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/tenant-interceptor.interceptor.ts
> +          'Access to different Tenant Not Allowed-',
baseUrl id /tenants/{id}/roles,
this does not allow user to enter id of different tenant

2023-10-06 12:03 UTC, akshatdubeysf commented on services/user-tenant-service/src/__tests__/acceptance/tenant-group.controller.acceptance.ts
> -  it('return a group object when id is sent', async () => {
Can you link to the code where you have test for this case or the one for update?

2023-10-06 12:03 UTC, akshatdubeysf commented on services/user-tenant-service/src/controllers/user-signup.controller.ts
> -﻿// Copyright (c) 2023 Sourcefuse Technologies
Was this part of the requirement? Then add it in the PR description

2023-10-06 12:04 UTC, akshatdubeysf commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      // Add pre-invocation logic here
Arre what is the purpose of this comment?

2023-10-06 12:05 UTC, rashisf commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +    role.tenantId = id ?? '';
this code should not exist here. Let the tenant guard service handle it

2023-10-06 12:07 UTC, akshatdubeysf commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      const groupId = invocationCtx.args[0];
If that is the case for all apis in the controller that this is fine, but leave a comment in comment on top of this line about why you are using 0 here

2023-10-06 12:08 UTC, rashisf commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +  @authenticate(STRATEGY.BEARER, {
what if one does not want roles based on tenants? Can't we handle this in way that will let the user decide?
IMO, no need to add tenantId in the roles basePath. User should configure the tenant related stuff in the service itself.

2023-10-06 12:08 UTC, rashisf commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +  @authenticate(STRATEGY.BEARER, {
what if one does not want roles based on tenants? Can't we handle this in way that will let the user decide?
IMO, no need to add tenantId in the roles basePath. User should configure the tenant related stuff in the service itself.

2023-10-06 12:45 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +  @authenticate(STRATEGY.BEARER, {
roles are created with in a tenant, as users belongs to one tenant and not allowed to interfere with other tenants. that's why roles that will be assigned to users will also be tenant specific

2023-10-09 06:14 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +    role.tenantId = id ?? '';
tenant guard service is not handling it

2023-10-09 06:14 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      const groupId = invocationCtx.args[0];
ok sir

2023-10-09 06:15 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      // Add pre-invocation logic here
they are auto generated, through lb4 interceptor

2023-10-09 06:16 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +import {
added in all files

2023-10-09 06:16 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/tenant.controller.ts
> +  @get(`${baseUrl}/count`, {security: OPERATION_SECURITY_SPEC, responses: {}})
ok sir

2023-10-09 06:29 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/repositories/user.repository.ts
> +    super(User, dataSource);
we are thinking to handle that case in such a way that, once user opt for user tenant service, then cli will generate this as whole in user's project, from their he/she can edit whatever they want.

2023-10-09 06:36 UTC, akshatdubeysf commented on services/user-tenant-service/src/repositories/user.repository.ts
> +    super(User, dataSource);
Then what's the point of creating a component class?

2023-10-09 06:37 UTC, akshatdubeysf commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      // Add pre-invocation logic here
Arre but you don't need them na? remove them

2023-10-09 07:01 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/repositories/user.repository.ts
> +    super(User, dataSource);
that needs change in cli, for now we were making the service more generic. once cli change will be done, then we will made the required changes

2023-10-09 07:02 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      // Add pre-invocation logic here
ok sir

2023-10-09 07:17 UTC, akshatdubeysf commented on services/user-tenant-service/src/repositories/user.repository.ts
> +    super(User, dataSource);
So the user can still use it as a component na? In that case the model should be replaceable

2023-10-09 10:55 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/__tests__/acceptance/tenant-group.controller.acceptance.ts
> -  it('return a group object when id is sent', async () => {
added sir

2023-10-09 10:57 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/repositories/user.repository.ts
> +    super(User, dataSource);
ok sir, made the user injectable

2023-10-13 06:35 UTC, akshatdubeysf commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      const groupId = invocationCtx.args[0];
I still don't see a comment explaining this in the code

2023-10-13 06:49 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      const groupId = invocationCtx.args[0];
added

2023-10-13 06:51 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      const groupRecord = groups.find(
done sir,removed the second query, as tenant Guard is applied on group Repository, so , we do not need to add tenantId here again.

2023-10-13 06:52 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/group-tenant.interceptor.ts
> +      // Add post-invocation logic here
removed

2023-10-13 06:53 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/user-tenant-interceptor.interceptor.ts
> +      const userTenantId = invocationCtx.args[0];
same reason as for groupTenant interceptor, this interceptors are applied to methods in which the userTenantId is a parameter within the API endpoint

2023-10-13 06:55 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +        description: 'Array of Tenant has many Role',
descriptions modified

2023-10-13 06:57 UTC, samarpan-b commented on services/user-tenant-service/src/interceptors/user-tenant-interceptor.interceptor.ts
> +      const userTenantId = invocationCtx.args[0];
@Tyagi-Sunny you should add a comment here. @akshatdubeysf is right. It is not self-explanatory. Or rather u can also pick arguments based off keys I believe. But that can be done later on. For now add comments.

2023-10-13 06:58 UTC, samarpan-b commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +    role.tenantId = id ?? '';
@rashisf its a different case.

2023-10-13 06:59 UTC, samarpan-b commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +  @authenticate(STRATEGY.BEARER, {
roles will always be based upon tenants. roles cant exist without tenants. Thats how multi-tenancy works. If roles are same across all tenants, then one can seed them for all new tenants during onboarding process.

2023-10-13 06:59 UTC, samarpan-b commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +  @authenticate(STRATEGY.BEARER, {
roles will always be based upon tenants. roles cant exist without tenants. Thats how multi-tenancy works. If roles are same across all tenants, then one can seed them for all new tenants during onboarding process.

2023-10-13 07:49 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/__tests__/acceptance/tenant-role.controller.acceptance.ts
> -  it('return a role objet when id is sent', async () => {
added role update case

2023-10-13 07:51 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/__tests__/acceptance/user-tenant.controller.acceptance.ts
> -﻿// Copyright (c) 2023 Sourcefuse Technologies
this controller is not required, so removed this test

2023-10-13 07:51 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/user-signup.controller.ts
> -﻿// Copyright (c) 2023 Sourcefuse Technologies
added

2023-10-13 07:53 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/interceptors/user-tenant-interceptor.interceptor.ts
> +      const userTenantId = invocationCtx.args[0];
added

2023-10-13 11:49 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/component.ts
> +    this.application
ok sir, used

2023-10-17 13:14 UTC, merged