fix(authentication-service): added a post route for keycloak login due to a possible security issue
sourcefuse/loopback4-microservice-catalog pull request #176
Opened 2021-04-26 13:35 UTC by akshatdubeysf

## Description

Possible security issue if secret is passed via query params, hence added a post route for keycloak
login

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [X] Performed a self-review of my own code
- [X] Code conforms with the style guide

2021-04-26 14:37 UTC, samarpan-b requested changes

2021-04-26 14:37 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    responses: {
add description to this API

2021-04-26 14:51 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    responses: {
Done

2021-04-27 18:44 UTC, samarpan-b requested changes

2021-04-27 18:44 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/login.controller.ts
> +
remove space and use deprecated for open api schema

2021-04-27 18:44 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/login.controller.ts
> +  async postloginViaKeycloak(
rename postLoginViaKeycloak

2021-04-30 06:47 UTC, sf-kansara commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      .map(key => `${key}=${req.body[key]}`)
Should we only pass `client_id`?

2021-04-30 06:48 UTC, sf-kansara commented on services/authentication-service/src/modules/auth/login.controller.ts
> +          schema: {type: 'object'},
We can have a minimal `jsonSchema` here.

2021-04-30 06:57 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      .map(key => `${key}=${req.body[key]}`)
You mean instead of req we pass only the client_id and return a string for that? Instead of mapping over the whole body? I did this just to be consistent with the other method does the same thing for query params.

2021-04-30 07:04 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +          schema: {type: 'object'},
Added.

2021-04-30 07:53 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      .map(key => `${key}=${req.body[key]}`)
yes. we only need to honor client id. refer -> https://github.com/sourcefuse/rakuten-pms-api/commit/6cd905231d549bcfd42f705a244bc9befd2944e7

2021-04-30 07:54 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      .map(key => `${key}=${req.body[key]}`)
Oh got it, will do it.

2021-04-30 08:12 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      .map(key => `${key}=${req.body[key]}`)
Done

2021-04-30 09:30 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +const keycloakBodyGen = (req: Request) => {
Oh right.

2021-04-30 09:32 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +const keycloakBodyGen = (req: Request) => {
But one is works for query params and the other for body?

2021-04-30 12:31 UTC, samarpan-b approved these changes

2021-04-30 12:33 UTC, merged