refactor(task-service): remove bpmn code, add abstraction layer
sourcefuse/loopback4-microservice-catalog pull request #1814
Opened 2023-11-20 13:51 UTC by rahulvsf

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-12-04 07:11 UTC, akshatdubeysf requested changes

2023-12-04 07:11 UTC, akshatdubeysf commented on services/task-service/src/interfaces/event-queue-service.interface.ts
> +  healthCheck(): Promise<HealthResponse>;
what is the purpose of this healthCheck?

2023-12-04 07:11 UTC, akshatdubeysf commented on services/task-service/src/interfaces/event-queue-service.interface.ts
> +  enqueueEvent(event: Partial<Event>): Promise<void>;
The queue only has a function for adding events in queue? no way to listen for events?

2023-12-04 07:11 UTC, akshatdubeysf commented on services/task-service/src/interfaces/task-operation-service.interface.ts
> +  taskUpdateFlow: (taskKey: string, payload?: AnyObject) => Promise<void>;
again what is the purpose of this function? add a description above every interface function if possible

2023-12-04 07:11 UTC, akshatdubeysf commented on services/task-service/src/interfaces/task-operation-service.interface.ts
> +    payload?: AnyObject,
Why any object? shouldn't this be generic?

2023-12-04 07:11 UTC, akshatdubeysf commented on services/task-service/src/interfaces/utility-service.interface.ts
> +  transformObject(obj?: AnyObject): AnyObject;
again, use generics

2023-12-04 07:11 UTC, akshatdubeysf commented on services/task-service/src/interfaces/utility-service.interface.ts
> +  generateApiKeyAndSecret(clientApp: ClientAppDTO): {
no inline type

2023-12-04 07:11 UTC, akshatdubeysf commented on services/task-service/src/providers/workflow.provider.ts
> +export class WorkflowProvider implements Provider<WorkflowManagerExtended> {
Why do even need this provider? if it has no actual implementation?

2023-12-04 07:11 UTC, akshatdubeysf commented on services/task-service/src/repositories/event.repository.ts
> -    @inject.getter(AuthenticationBindings.CURRENT_USER)
? how would it getting created by and modified by?

2023-12-04 07:11 UTC, akshatdubeysf commented on services/task-service/src/services/event-queue.service.ts
> +    private readonly eventProcessorService: EventProcessorServiceInterface,
This implementation still assumes a particular structure for the connection class

2023-12-04 07:11 UTC, akshatdubeysf commented on services/task-service/src/services/task-operation.service.ts
> +        key,
tenant id?

2023-12-04 07:11 UTC, akshatdubeysf commented
@rahulvsf sonar

2023-12-29 13:32 UTC, samarpan-b commented
Closing it in favour of #1839

2023-12-29 13:32 UTC, closed without merging