Gh 1806
sourcefuse/loopback4-microservice-catalog pull request #1829
Opened 2023-12-07 22:17 UTC by karuneshsf

## Description
Implemented notification grouping feature as follows

1. added feature to group many notification to one notification
2. added feature to have sleep time for recipient(s)
3. added feature to draft notification
4. added feature to send notification without drafting if it is critical
5. added feature to group many notification as one notification

Fixes # (issue)
GH-1806
## Type of change
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?
- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-12-12 11:13 UTC, yeshamavani commented
PR title

2023-12-12 11:22 UTC, samarpan-b requested changes

2023-12-12 11:22 UTC, samarpan-b commented on packages/cli/README.md
> +@sourceloop/cli/6.0.0 darwin-arm64 node-v16.15.0
why this change ?

2023-12-12 11:22 UTC, samarpan-b commented on .vscode/settings.json
> +    "Notif"
why ?

2023-12-12 11:22 UTC, samarpan-b commented on packages/core/locales/en.json
> +	"The key 'repositories.UserNotificationSettingsRepository' is not bound to any value in context RequestContext-NJzgVogAQu2g51aqkFd2OA-92 (context": " RequestContext-NJzgVogAQu2g51aqkFd2OA-92, bindin
revert the changes in this file please

2023-12-12 11:22 UTC, samarpan-b commented on sandbox/chat-notification-pubnub-example/services/notifications-service/src/application.ts
> +import { BootMixin } from '@loopback/boot';
Fix please

2023-12-12 11:22 UTC, samarpan-b commented on services/notification-service/migrations/sqls/20231128083406-alter-db-to-support-multiple-notification-as-one-notification-up.sql
> +ADD COLUMN IF NOT EXISTS  is_draft boolean default FALSE;
why do we need this is_draft column ?

2023-12-12 11:22 UTC, samarpan-b commented on services/notification-service/migrations/sqls/package.json
> +{
revert pls

2023-12-12 11:22 UTC, samarpan-b commented on services/notification-service/src/controllers/user-notification-settings.controller.ts
> +    if (currentUser.id !== userNotificationSettings.userId) {
remove this check for now

2023-12-12 11:22 UTC, samarpan-b commented on services/notification-service/src/controllers/user-notification-settings.controller.ts
> +  private async _verifyOwned(
No need to check for current user for now

2023-12-12 11:22 UTC, samarpan-b commented on services/notification-service/src/providers/notification-user-settings.service.ts
> +            element.isDraft = false;
This should be in notif-user table

2023-12-12 11:22 UTC, samarpan-b commented on services/notification-service/src/services/process-notification.service.ts
> +const maxBodyLen = 1000;
move this to process.env

2023-12-12 11:22 UTC, samarpan-b commented on services/notification-service/src/services/process-notification.service.ts
> +    notif = await this.insertDataInDb(notification);
Use transactions. Do rollback if anything fails

2023-12-12 11:22 UTC, samarpan-b commented on services/notification-service/src/services/process-notification.service.ts
> +      notif = await this.insertDataInDb(notification);
This seems to be happening twice

2023-12-29 12:31 UTC, samarpan-b commented on .vscode/settings.json
> +    "source.organizeImports": "explicit"
revert this

2023-12-29 12:32 UTC, samarpan-b commented on sandbox/chat-notification-pubnub-example/services/notifications-service/package.json
> +    "@sourceloop/core": "^10.0.0",
revert pls

2023-12-29 12:35 UTC, samarpan-b commented on services/notification-service/package.json
> +    "db:migrate": "../../node_modules/db-migrate/bin/db-migrate up --config './database.json'",
revert this please

2023-12-29 12:36 UTC, samarpan-b commented on services/notification-service/src/__tests__/acceptance/helper.ts
> +  process.env.TEST_ENV = '1';
process.env.NODE_ENV = 'test';

2023-12-29 12:38 UTC, samarpan-b commented on services/notification-service/src/controllers/notification.controller.ts
> +  @post(`${basePath}/group/{groupKey}`, {
```suggestion
  @post(`${basePath}/groups/{groupKey}`, {
```

2023-12-29 12:43 UTC, samarpan-b commented on services/notification-service/src/services/process-notification.service.ts
> +      process.env.TEST_ENV !== '1'
```suggestion
      process.env.NODE_ENV !== 'test'
```

2023-12-29 14:43 UTC, yeshamavani commented
apart from comments looks good to me

2024-01-02 07:51 UTC, samarpan-b commented
CI is failing

2024-01-03 04:31 UTC, samarpan-b requested changes

2024-01-03 05:29 UTC, samarpan-b approved these changes

2024-01-03 06:55 UTC, yeshamavani approved these changes

2024-01-03 06:56 UTC, merged