feat(task-service): complete reimplementation of task service
sourcefuse/loopback4-microservice-catalog pull request #1839
Opened 2023-12-12 08:34 UTC by akshatdubeysf

## Description

- complete reimplementation of task service to make it more readable, maintable and extensible
- added support for a kafka connection
- added implementation and support of sub tasks

MIGRATION CHANGE:
migration-20230809101404- basic setup of task service db migration-20230809100541- basic setu of example db migration-20230808104436- basic setup of task service db

Fixes GH-1785

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [X] Performed a self-review of my own code
- [X] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-12-29 14:16 UTC, samarpan-b requested changes

2023-12-29 14:16 UTC, samarpan-b commented on services/task-service/src/interfaces/i-sub-task-service.ts
> +  updateList(taskId: string, processInstanceId: string): Promise<void>;
why is it called updateList ? why not just update ?

2023-12-29 14:16 UTC, samarpan-b commented on services/task-service/src/interfaces/index.ts
> +export * from './i-incoming-connector';
Dont we need i-connector interface too ?

2023-12-29 14:16 UTC, samarpan-b commented on services/task-service/src/repositories/task.repository.ts
> +export class TaskRepository extends DefaultCrudRepository<
Dont we need softcrudrepo here ?

2023-12-29 14:16 UTC, samarpan-b commented on services/task-service/src/types.ts
> +  TaskService = 'task-service',
why is task service a source ?

2023-12-29 14:30 UTC, akshatdubeysf commented on services/task-service/src/constant.ts
> +export const SYSTEM_USER = {
As there is no user in the context of a streamed event, we need to bind some user in the context which is created in this file as a constant

2023-12-29 14:30 UTC, akshatdubeysf commented on services/task-service/src/interfaces/i-sub-task-service.ts
> +  updateList(taskId: string, processInstanceId: string): Promise<void>;
Because it does not update a single task, but all the subtasks lists in the parent task

2023-12-29 14:31 UTC, akshatdubeysf commented on services/task-service/src/interfaces/index.ts
> +export * from './i-incoming-connector';
no, that would just be a combination of i-incoming-connector and i-outgoing-connector

2023-12-29 14:32 UTC, akshatdubeysf commented on services/task-service/src/types.ts
> +  TaskService = 'task-service',
It is a source for outgoing events na?

2024-01-02 07:48 UTC, samarpan-b commented on services/task-service/src/constant.ts
> +export const SYSTEM_USER = {
Why in constant ? Shouldn't this come from env ?

2024-01-02 07:49 UTC, samarpan-b commented on services/task-service/src/interfaces/i-sub-task-service.ts
> +  updateList(taskId: string, processInstanceId: string): Promise<void>;
then can we call it updateChildTasks ?

2024-01-02 07:49 UTC, samarpan-b commented on services/task-service/src/interfaces/index.ts
> +export * from './i-incoming-connector';
What about connect and disconnect methods ?

2024-01-02 07:50 UTC, samarpan-b commented on services/task-service/src/types.ts
> +  TaskService = 'task-service',
ok, got it.

2024-01-10 13:35 UTC, Swati0077 requested changes

2024-01-10 13:35 UTC, Swati0077 commented on sandbox/task-example/migrations/sqls/20230809100541-init-up.sql
> +    id                  uuid DEFAULT md5(random()::text || clock_timestamp()::text)::uuid NOT NULL,
name property missing

2024-01-10 13:35 UTC, Swati0077 commented on services/task-service/src/commands/create-task.command.ts
> +      const tasksWithWorkflow = JSON.parse(variables.tasks) as Task[];
please change it to variables.task.values

2024-01-10 13:36 UTC, Swati0077 commented
Please export models and repositories as well from index.ts of task service @akshatdubeysf

2024-01-10 13:40 UTC, Swati0077 commented on services/task-service/src/controllers/task.controller.ts
> +}
missing delete APIs

2024-01-10 13:40 UTC, Swati0077 requested changes

2024-01-10 13:40 UTC, Swati0077 commented on services/task-service/src/controllers/task-user-task.controller.ts
> +}
missing delete APIs

2024-01-15 05:08 UTC, akshatdubeysf commented on services/task-service/src/commands/end-task.command.ts
> +      await await job.complete(this.parameters.task);
removed

2024-01-15 05:09 UTC, akshatdubeysf commented on services/task-service/src/constant.ts
> +export const SYSTEM_USER = {
It was already using env but moved it to a binding now.

2024-01-15 05:09 UTC, akshatdubeysf commented on services/task-service/src/interfaces/i-event-adapter.ts
> +export interface IEventAdapter<T, S> {
added

2024-01-15 05:11 UTC, akshatdubeysf commented on services/task-service/src/interfaces/i-sub-task-service.ts
> +  updateList(taskId: string, processInstanceId: string): Promise<void>;
Because the service name is already`'IUserTaskService` na?

2024-01-15 05:12 UTC, akshatdubeysf commented on services/task-service/src/interfaces/index.ts
> +export * from './i-incoming-connector';
connect and disconnect method are not concerns of the `task-service`, the user can implement or omit them as per there requirement.

2024-01-15 05:12 UTC, akshatdubeysf commented on services/task-service/src/repositories/task.repository.ts
> +export class TaskRepository extends DefaultCrudRepository<
added

2024-01-15 05:12 UTC, akshatdubeysf commented on sandbox/task-example/migrations/sqls/20230809100541-init-up.sql
> +    id                  uuid DEFAULT md5(random()::text || clock_timestamp()::text)::uuid NOT NULL,
added

2024-01-15 05:12 UTC, akshatdubeysf commented on services/task-service/src/commands/create-task.command.ts
> +      const tasksWithWorkflow = JSON.parse(variables.tasks) as Task[];
added

2024-01-15 05:12 UTC, akshatdubeysf commented on services/task-service/src/controllers/task.controller.ts
> +}
added

2024-01-15 05:12 UTC, akshatdubeysf commented on services/task-service/src/controllers/task-user-task.controller.ts
> +}
added

2024-01-15 05:41 UTC, akshatdubeysf commented
coverage -
<img width="584" alt="Screenshot 2024-01-15 at 11 04 59" src="https://github.com/sourcefuse/loopback4-microservice-catalog/assets/77672713/63c701ca-0d1d-4c24-b9fe-9e775c8b9467">

2024-01-17 12:28 UTC, samarpan-b approved these changes

2024-01-17 12:40 UTC, merged