feat(reporting service): complete reimplemntation
sourcefuse/loopback4-microservice-catalog pull request #1843
Opened 2023-12-13 13:35 UTC by SouravSF

## Description
reimplementation of Reporting MS, The implementation includes primarliy following features 

-  Data Ingestion
- DataSources
- DataSets
- Widgets
- Dashboard

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ *] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ *] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-12-27 08:53 UTC, akshatdubeysf requested changes

2023-12-27 08:53 UTC, akshatdubeysf commented on services/reporting-service/src/services/store-adapter.service.ts
> +export class StoreAdapterService {
is this being used anywhere?

2023-12-27 08:53 UTC, akshatdubeysf commented on services/reporting-service/src/services/data-sets.service.ts
> +    this.queryObjectValidator = new QueryObjectValidator();
why is this not fetched throught DI

2023-12-27 08:53 UTC, akshatdubeysf commented on services/reporting-service/src/utils/sql-query-builder.utils.ts
> +export class SQLQueryBuilder {
this should be a strategy na?

2023-12-27 08:53 UTC, akshatdubeysf commented on services/reporting-service/src/utils/sql-query-builder.utils.ts
> +export class SQLQueryBuilder {
Why is this not part of DI?

2023-12-27 08:53 UTC, akshatdubeysf commented on services/reporting-service/src/utils/validate-ingest-report-record.ts
> +export const validateIngestReportRecord = (
This should be a service and tested na?

2023-12-27 08:53 UTC, akshatdubeysf commented on services/reporting-service/src/__tests__/acceptance/dashboard.controller.acceptance.ts
> +import {RestApplication} from '@loopback/rest';
tests for services and providers seem to be missing

2023-12-27 08:53 UTC, akshatdubeysf commented on services/reporting-service/README.md
> +Microservice for handling chat between users and user groups.
?

2023-12-27 08:53 UTC, akshatdubeysf commented on services/reporting-service/src/types.ts
> +export interface ReportingServiceComponentOptions {}
is this used anywhere?

2023-12-27 08:55 UTC, akshatdubeysf commented on services/reporting-service/src/services/data-sets.service.ts
> +      (await this.isDuplicate(dataSet.dataSetQueryHash))
Why are we checking for query hash? two queries for different tenants could be exactly same na? or for two different users?

2023-12-27 09:04 UTC, akshatdubeysf requested changes

2023-12-27 09:04 UTC, akshatdubeysf commented on services/reporting-service/src/strategies/sequelize/base-sequelize.ts
> +    throw new Error(METHOD_NOT_IMPLEMENTED);
shouldn't all these methods be abstract?

2023-12-27 09:04 UTC, akshatdubeysf commented on services/reporting-service/src/strategies/sequelize/base-sequelize.ts
> +    throw new Error(METHOD_NOT_IMPLEMENTED);
and some of them should have the common implementation that is shared across strategies?

2023-12-27 09:04 UTC, akshatdubeysf commented on services/reporting-service/src/strategies/sequelize/psql-sequelize-strategy.ts
> +    const deleteQuery = `DELETE FROM ${dataSource} WHERE ${identifier} = :identifierValue`;
avoid string interpolation, use parameters instead of these

2023-12-27 09:04 UTC, akshatdubeysf commented on services/reporting-service/src/factories/data-type-convertion.factory.ts
> +  async convertToDataType(
is this really a factory?

2023-12-28 09:45 UTC, SouravSF commented on services/reporting-service/migrations/sqls/20231213101318-init-script-up.sql
> +	id                   integer DEFAULT nextval('core.state_tracking_aggregation_id_seq'::regclass) NOT NULL  ,
this table was created using DBSchema but I later decided not to use, will be removed in the next commit

2023-12-28 10:28 UTC, SouravSF commented on services/reporting-service/src/adapters/sequelize.adapter.ts
> +      case 'postgres':
not sure what you talking about

2023-12-28 10:37 UTC, SouravSF commented on services/reporting-service/src/controllers/data-sources.controller.ts
> +    const dataSources = await this.dataSourcesService.listdataSources();
had done some console log earlier so.. , would be removed in next commit

2023-12-28 10:54 UTC, SouravSF commented on services/reporting-service/src/decorators/custom-type-converter.decorator.ts
> +export function handleCustomTypeConvert(convertType: string) {
suggest

2023-12-28 11:03 UTC, SouravSF commented on services/reporting-service/src/factories/data-store-adapter.factory.ts
> +   */
this is a factory, it doesn't need to have a state, no state means no requirement of the object so static is an acceptable approach

2023-12-28 11:04 UTC, akshatdubeysf commented on services/reporting-service/src/adapters/sequelize.adapter.ts
> +      case 'postgres':
A similar condition is present in sequelize adapter as well. You could achieve the same effect with binding strategies on condition.

2023-12-28 11:18 UTC, SouravSF commented on services/reporting-service/src/factories/data-store-adapter.factory.ts
> +        return new SequelizeAdapter(
DataAdapters play a central role in the component functioning, I wanted to control the installation of this object & so have decided to go the factory route.

2023-12-28 11:29 UTC, SouravSF commented on services/reporting-service/src/factories/data-type-convertion.factory.ts
> +  async convertToDataType(
no, not a factory but it falls under that in the sense that it is an enabler to type mapping.

2023-12-28 11:32 UTC, SouravSF commented on services/reporting-service/src/factories/data-type-convertion.factory.ts
> +        `../enums/dataTypes/${databaseType}DataTypes`
these are going to be the ones supported by the relevant Data store, so there won't be such a case. If the component supports the Data store then it would have its supported mapping present.

2023-12-28 11:33 UTC, SouravSF commented on services/reporting-service/src/interfaces/any-val.interface.ts
> +export type AnyVal = any;
I have only used it where I feel its necessary, I see your comments for the same at multiple places I will re-review those.

2023-12-28 11:34 UTC, SouravSF commented on services/reporting-service/src/interfaces/cdc.interface.ts
> +  currentValue: Record<string, AnyVal>;
Not sure what you are referring to in the first comment, while for the second part its a necessity.

2023-12-29 00:50 UTC, SouravSF commented on services/reporting-service/src/interfaces/sql-data-store.config.interface.ts
> +  type: DbName.POSTGRES | DbName.MYSQL;
User wont add another DB, the component has to support another for this to work, this is as designed.

2023-12-29 01:23 UTC, SouravSF commented on services/reporting-service/src/services/store-adapter.service.ts
> +export class StoreAdapterService {
no this is a deprecated code, it's been pushed by mistake and will be removed in the next commit. I created it a couple of weeks back while experimenting with observers

2023-12-29 01:35 UTC, SouravSF commented on services/reporting-service/src/services/report-ingestion-messaging.service.ts
> +    this.init().catch(error => {
lb4 creates the instance of this service. this works

2023-12-29 01:36 UTC, SouravSF commented on services/reporting-service/src/types.ts
> +export interface ReportingServiceComponentOptions {}
this file is an automatically generated file, I didn't use it and didn't remove it earlier as I saw the previous version also had an empty one, Have removed it now.

2023-12-29 01:40 UTC, SouravSF commented on services/reporting-service/src/__tests__/acceptance/dashboard.controller.acceptance.ts
> +import {RestApplication} from '@loopback/rest';
I have added only a few, the ARC team can add more detailed cases.

2023-12-29 03:12 UTC, SouravSF commented on services/reporting-service/src/adapters/sequelize.adapter.ts
> +      case 'postgres':
this is sequalize adapter only, if you are talking about switch cases then, I think you are confused. you must be talking about the switch case in data  store adapter factory switch case and comparing it with this one, the purpose of data store adapter is to select a correct adapter, while the purpose of the switch here is to select the correct strategy for the ones with sequalize  adapter.

2024-01-02 08:31 UTC, SouravSF commented on services/reporting-service/src/services/default-listener.service.ts
> +  async processMessage(
through report Ingestion mapping service

2024-01-03 05:38 UTC, samarpan-b commented on services/reporting-service/src/factories/data-store-adapter.factory.ts
> +      case 'sqs':
Why is SQS a data store type ? Your description of class mentions this. /* The `DataStoreAdapterFactory` class is responsible for creating a database adapter based on the
specified database type. */

2024-01-03 05:46 UTC, samarpan-b requested changes

2024-01-03 05:46 UTC, samarpan-b commented on services/reporting-service/src/adapters/sequelize.adapter.ts
> +    switch (this.options.databaseType) {
This switch case is repeated in line 40 of data-store-adpater factory class too. Why doing this at 2 places ?

2024-01-03 05:46 UTC, samarpan-b commented on services/reporting-service/src/factories/data-store-adapter.factory.ts
> +export class DataStoreAdapterFactory {
We should use DI here and let it be injected as singleton and then we wont need static method. Making this part of DI allows us to follow LB4 standards and best practice. Singleton classes are recommended and preferred over static any which ways because of their advantages around OOP. Read this - https://stackoverflow.com/a/519536 and https://stackoverflow.com/a/12367609

2024-01-03 05:46 UTC, samarpan-b commented on services/reporting-service/src/factories/data-type-convertion.factory.ts
> +/* The `DataTypeConvertionFactory` class is responsible for converting a data type from a specific
As per comment it does seem to be a factory. Its an adapter. Please use adapter pattern here with standard i-adapter interface we have in core.

2024-01-03 05:46 UTC, samarpan-b commented on services/reporting-service/src/interfaces/any-val.interface.ts
> +export type AnyVal = any;
Please use AnyObject provided by LB4. Remove this please.

2024-01-04 08:47 UTC, SouravSF commented on services/reporting-service/src/factories/data-store-adapter.factory.ts
> +      case 'sqs':
@samarpan-b  DataStore can be anything, it can be a DB supported by sequalize, it can be a s3 bucket, it can be  SQS. After a DataStore Object is created then in present case we move to SequalizeAdapter for the DataStoreTypes that are supported by Sequalize in present case postgres. that is why you see switch inside Sequalize, both the switches have separate purposes. the naming of the property above should have been dataStoreType instead of databaseType. I hope this answers your Qz

2024-01-25 05:00 UTC, akshatdubeysf commented on services/reporting-service/src/decorators/custom-type-converter.decorator.ts
> +export function handleCustomTypeConvert(convertType: string) {
should be something like `customTypeConverter`

2024-01-25 05:36 UTC, akshatdubeysf commented on services/reporting-service/src/providers/data-store-object.provider.ts
> +    if (this.isSequelizeConfig(this.config)) {
why the if conditions?

2024-01-25 05:36 UTC, akshatdubeysf commented on services/reporting-service/src/observers/report-service-initializer.ts
> +    @inject('repositories.IngestionMappingsRepository')
use @repositories?

2024-01-25 05:36 UTC, akshatdubeysf commented on services/reporting-service/src/mappings/data-types/mysql-data-types.ts
> +const conversionUtils = new GenericConversionUtils();
why not part of DI?

2024-01-25 05:36 UTC, akshatdubeysf commented on services/reporting-service/src/__tests__/acceptance/dashboard.controller.acceptance.ts
> +import {RestApplication} from '@loopback/rest';
@samarpan-b need to assign someone for this

2024-01-31 09:51 UTC, SouravSF commented on services/reporting-service/src/controllers/dashboard.controller.ts
> +    const enhancedDashboards = dashboards.map(dashboard => {
@akshatdubeysf can you get these done in next minor version

2024-01-31 09:51 UTC, SouravSF commented on services/reporting-service/src/controllers/dashboard.controller.ts
> +    const widgetIds = dashboardWidgets.map(dw => dw.widgetId);
@akshatdubeysf can you get these done in next minor version

2024-01-31 09:57 UTC, SouravSF commented on services/reporting-service/src/interfaces/data-store-adapter.interface.ts
> +  listDataSourceColumns(dataSource: string): Promise<ColumnForDataSource[]>;
this would be very data adapter centric so it has to be written for each strategy

2024-01-31 09:57 UTC, SouravSF commented on services/reporting-service/src/interfaces/data-store-adapter.interface.ts
> +  listdataSources(): Promise<DataSourceList[]>;
this would be very data adapter centric so it has to be written for each strategy

2024-01-31 10:06 UTC, SouravSF commented on services/reporting-service/src/interfaces/ingestion-handler.interface.ts
> +    DBO: DataStoreAdapter,
As discussed the motive of this is to give limited flexibility to the component user to update the ingestion object while still ensuring that the saving part is done through the ingestion process, in an attempt to ensure data delivery guarantee, however, I still would need to handle the guarantee stuff through event mechanism.

2024-01-31 10:09 UTC, SouravSF commented on services/reporting-service/src/services/data-sets.service.ts
> +      (await this.isDuplicate(dataSet.dataSetQueryHash))
this allows flexibility to choose properties

2024-01-31 10:09 UTC, akshatdubeysf commented on services/reporting-service/src/controllers/dashboard.controller.ts
> +    const enhancedDashboards = dashboards.map(dashboard => {
someone  can be assigned by @samarpan-b for this, resolving for now

2024-01-31 10:10 UTC, akshatdubeysf commented on services/reporting-service/src/controllers/dashboard.controller.ts
> +    const widgetIds = dashboardWidgets.map(dw => dw.widgetId);
someone will be assigned by @samarpan-b for this

2024-01-31 10:12 UTC, akshatdubeysf commented on services/reporting-service/src/interfaces/ingestion-handler.interface.ts
> +    DBO: DataStoreAdapter,
ok, this will be resolved in a separate version after discussion, resolving for now

2024-01-31 11:53 UTC, samarpan-b commented on services/reporting-service/src/__tests__/acceptance/dashboard.controller.acceptance.ts
> +import {RestApplication} from '@loopback/rest';
@SouravSF we will need test case coverage of services and providers at least before merging this PR. Its imperative being OSS.

2024-02-13 10:29 UTC, SouravSF commented on services/reporting-service/src/__tests__/acceptance/dashboard.controller.acceptance.ts
> +import {RestApplication} from '@loopback/rest';
added test cases

2024-02-19 04:59 UTC, akshatdubeysf approved these changes

2024-02-20 07:02 UTC, yeshamavani requested changes

2024-02-20 07:10 UTC, samarpan-b commented on services/reporting-service/migrations/sqls/20231213101318-init-script-up.sql
@yeshamavani for now this will support postgresql only

2024-02-20 11:22 UTC, yeshamavani approved these changes

2024-02-20 11:30 UTC, samarpan-b approved these changes

2024-02-20 11:31 UTC, merged