feat(task-service): add mysql db migrations
sourcefuse/loopback4-microservice-catalog pull request #1864
Opened 2023-12-22 08:01 UTC by sf-sahil-jassal

add support for mysql db by creating seperate
directories for mysql and pg migrations

MIGRATION CHANGE:
migration-20231222070515- add seperate directory for mysql migrations

gh-1836

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-12-29 13:49 UTC, yeshamavani requested changes

2023-12-29 13:49 UTC, yeshamavani commented on services/task-service/migrations/mysql/migrations/sqls/20231222070515-init-up.sql
> +    type                VARCHAR(255),
can we change all of these to text

2023-12-29 13:49 UTC, yeshamavani commented on services/task-service/migrations/mysql/migrations/package.json
not needed

2023-12-29 13:49 UTC, yeshamavani commented on services/task-service/migrations/mysql/migrations/sqls/package.json
not needed

2023-12-29 17:02 UTC, sf-sahil-jassal commented on services/task-service/migrations/mysql/migrations/sqls/20231222070515-init-up.sql
> +    type                VARCHAR(255),
in psql migrations, only VARCHAR was written for these columns. So, I changed to that.

2024-01-01 07:23 UTC, yeshamavani approved these changes

2024-01-01 07:24 UTC, merged