feat(authentication-service): provide support for authenticated issuance of access token using refresh token
sourcefuse/loopback4-microservice-catalog pull request #1877
Opened 2023-12-29 13:16 UTC by arpit1503khanna

## Description

1. Provide support for authenticated issuance of access token using refresh token during login(implemented for google/keycloak)
2. Revoke access token if the user has logged out(implemented for google)
Fixes #1263 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-12-29 13:35 UTC, rashisf commented on services/authentication-service/src/providers/user-validation.provider.ts
> +          method: 'post',
we can break this into multiple functions.
Even better, we can also have different providers for different auth strategies that user can override

2023-12-29 13:58 UTC, yeshamavani requested changes

2023-12-29 13:58 UTC, yeshamavani commented on services/authentication-service/src/providers/user-validation.provider.ts
> +          method: 'post',
will also help in improving readability

2023-12-29 13:58 UTC, yeshamavani commented on services/authentication-service/openapi.json
> +          },
/auth/demo  -- ??

2023-12-29 13:58 UTC, yeshamavani commented on services/authentication-service/openapi.md
> +  "refreshToken": "string",
??

2023-12-29 14:04 UTC, arpit1503khanna commented on services/authentication-service/openapi.json
> +          },
Will fix it

2023-12-29 14:13 UTC, arpit1503khanna commented on services/authentication-service/openapi.md
> +  "refreshToken": "string",
Will fix it

2024-01-01 11:23 UTC, yeshamavani commented on services/authentication-service/src/providers/types.ts
> +
can we use a single type since they all have same parameters?

2024-01-01 11:23 UTC, yeshamavani commented on services/authentication-service/src/providers/user-validation.provider.ts
> +    token?: string,
what is this token 
what is its use?

2024-01-01 11:46 UTC, arpit1503khanna commented on services/authentication-service/src/providers/user-validation.provider.ts
> +    token?: string,
It can be removed, its just provided incase the user wants it for some implementation in their code.

2024-01-01 12:56 UTC, yeshamavani commented on services/authentication-service/src/providers/types.ts
> +
again cant we use single type ?

2024-01-01 14:09 UTC, yeshamavani approved these changes

2024-01-01 14:09 UTC, merged