feat(search-service): add sequelize support in search service
sourcefuse/loopback4-microservice-catalog pull request #1883
Opened 2024-01-02 15:06 UTC by Surbhi-sharma1

add sequelize support in search service

GH-1350

## Description

add sequelize support in search service

Fixes #1350

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-10 12:50 UTC, yeshamavani approved these changes

2024-01-22 07:53 UTC, Surbhi-sharma1 commented
https://github.com/loopbackio/loopback-next/issues/10312
Raised an issue related to this PR in loopback/next sequelize extension

2024-03-14 07:29 UTC, yeshamavani commented
Will be merged after the sequelize version is updated in all services.

2024-03-22 05:40 UTC, Surbhi-sharma1 commented
https://github.com/sourcefuse/loopback4-microservice-catalog/pull/2047
will be merged after this PR

2024-03-22 05:41 UTC, Surbhi-sharma1 commented
> [loopbackio/loopback-next#10312](https://github.com/loopbackio/loopback-next/issues/10312) Raised an issue related to this PR in loopback/next sequelize extension
the above mentioned  PR is merged

2024-03-28 06:32 UTC, yeshamavani commented
@Surbhi-sharma1 version updates are done you can rebase this PR please test your changes in loopback-sequelize are working fine 
once that is done we can merge this pR

2024-04-05 06:29 UTC, yeshamavani requested changes

2024-04-05 06:29 UTC, yeshamavani commented on services/search-service/migrations/pg/migrations/sqls/20240403122951-recent-search-down.sql
down script missing

2024-04-05 06:29 UTC, yeshamavani commented on services/search-service/migrations/pg/migrations/20240403122951-recent-search.js
add mysql scripts as well

2024-04-08 06:02 UTC, yeshamavani requested changes

2024-04-08 06:06 UTC, Surbhi-sharma1 commented on services/search-service/package.json
> +  "author": " <akshat.dubey@sourcefuse.com>",
okay

2024-04-08 13:00 UTC, akshatdubeysf requested changes

2024-04-08 13:00 UTC, akshatdubeysf commented on services/search-service/src/services/model.provider.ts
> +    return async (search: SearchQuery, queryBuilder: any) => {
why any?

2024-04-08 13:00 UTC, akshatdubeysf commented on services/search-service/src/repositories/sequelize/search-query.repository.ts
> +export class SearchQueryRepository extends SequelizeUserModifyCrudRepository<
why multiple copies of the repository?

2024-04-08 13:00 UTC, akshatdubeysf commented on services/search-service/src/services/model.provider.ts
> +) => Promise<{query: string; params: any[]}>; // NOSONAR
again, why any[]?

2024-04-08 13:00 UTC, akshatdubeysf commented on services/search-service/migrations/pg/migrations/sqls/20240403122951-recent-search-up.sql
> +ADD IF NOT EXISTS where_ json NOT NULL DEFAULT '{}';
what about services that have been using this library? they would have existing values in the where column?

2024-04-08 13:08 UTC, Surbhi-sharma1 commented on services/search-service/src/repositories/sequelize/search-query.repository.ts
> +export class SearchQueryRepository extends SequelizeUserModifyCrudRepository<
one  is for sequelize

2024-04-08 13:10 UTC, Surbhi-sharma1 commented on services/search-service/migrations/pg/migrations/sqls/20240403122951-recent-search-up.sql
> +ADD IF NOT EXISTS where_ json NOT NULL DEFAULT '{}';
will remove default value

2024-04-09 11:53 UTC, Surbhi-sharma1 commented on services/search-service/migrations/mysql/migrations/sqls/20231221041306-init-up.sql
> +CREATE PROCEDURE IF NOT EXISTS add_columns_if_not_exists(tableName VARCHAR(100), columnName VARCHAR(100), columnType VARCHAR(100))
IF NOT EXIST is not supported in mysql ,thats y created procedure.

2024-04-10 05:41 UTC, Surbhi-sharma1 commented on services/search-service/src/services/model.provider.ts
> +    return async (search: SearchQuery, queryBuilder: any) => {
Done with the changes

2024-04-15 06:49 UTC, Surbhi-sharma1 commented on services/search-service/src/repositories/sequelize/recent-search.repository.ts
> +  async create(query: SearchQuery, user?: IAuthUserWithPermissions) {
separate PR for implementing SOLID principles

2024-05-02 04:49 UTC, yeshamavani requested changes

2024-05-02 04:49 UTC, yeshamavani commented on services/search-service/migrations/mysql/migrations/sqls/20240405080334-recent-search-up.sql
> +END;
using the procedure first and creating it later 
how will this work

2024-05-02 04:56 UTC, yeshamavani commented on services/search-service/src/services/model.provider.ts
> +    return async (search: SearchQuery, queryBuilder: any) => {
used AnyObject

2024-05-02 04:58 UTC, yeshamavani commented on services/search-service/migrations/pg/migrations/sqls/20240403122951-recent-search-up.sql
> +ADD IF NOT EXISTS where_ json NOT NULL DEFAULT '{}';
??

2024-05-02 05:15 UTC, Surbhi-sharma1 commented on services/search-service/migrations/mysql/migrations/sqls/20240405080334-recent-search-up.sql
> +END;
Done

2024-05-02 07:40 UTC, akshatdubeysf commented on services/search-service/migrations/mysql/migrations/sqls/20231221041306-init-up.sql
> +CREATE PROCEDURE IF NOT EXISTS add_columns_if_not_exists(tableName VARCHAR(100), columnName VARCHAR(100), columnType VARCHAR(100))
But why do you need to create a permanent procedure for it?

2024-05-02 07:41 UTC, akshatdubeysf commented on services/search-service/src/repositories/sequelize/search-query.repository.ts
> +export class SearchQueryRepository extends SequelizeUserModifyCrudRepository<
This would result in copies of same implementation

2024-05-02 07:42 UTC, akshatdubeysf commented on services/search-service/migrations/pg/migrations/sqls/20240403122951-recent-search-up.sql
> +ADD IF NOT EXISTS where_ json NOT NULL DEFAULT '{}';
@Surbhi-sharma1 ?

2024-05-02 07:52 UTC, Surbhi-sharma1 commented on services/search-service/src/repositories/sequelize/search-query.repository.ts
> +export class SearchQueryRepository extends SequelizeUserModifyCrudRepository<
https://github.com/sourcefuse/loopback4-microservice-catalog/pull/2072
PR link for this

2024-05-02 07:53 UTC, Surbhi-sharma1 commented on services/search-service/migrations/pg/migrations/sqls/20240403122951-recent-search-up.sql
> +ADD IF NOT EXISTS where_ json NOT NULL DEFAULT '{}';
removed default value

2024-05-02 08:57 UTC, Surbhi-sharma1 commented on services/search-service/migrations/mysql/migrations/sqls/20231221041306-init-up.sql
> +CREATE PROCEDURE IF NOT EXISTS add_columns_if_not_exists(tableName VARCHAR(100), columnName VARCHAR(100), columnType VARCHAR(100))
Added Drop to remove the procedure after it has been created

2024-05-03 06:34 UTC, akshatdubeysf approved these changes

2024-05-13 08:59 UTC, merged