feat(authentication-service): added SAML example
sourcefuse/loopback4-microservice-catalog pull request #1912
Opened 2024-01-15 23:28 UTC by karuneshsf

## Description

added example for SAML

Fixes # (issue)
GH-1663
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Intermediate change (work in progress)

## How Has This Been Tested?
- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-17 15:01 UTC, yeshamavani commented on sandbox/oauth-example/src/providers/saml-verify.provider.ts
> +        where: {
?? 
a verify provider should first check if user present or not and then call signup if not present

2024-01-17 15:01 UTC, yeshamavani commented on services/authentication-service/src/models/index.ts
> +export * from './login-activity.model';
revert this change
causes unnecessary release

2024-02-02 06:40 UTC, karuneshsf commented on services/authentication-service/src/models/index.ts
> +export * from './login-activity.model';
This one is not change, the ordering of the file is only changed

2024-02-02 06:41 UTC, karuneshsf commented on sandbox/oauth-example/src/providers/saml-verify.provider.ts
> +        where: {
This is being done in same manner in all other providers as well, so followed same pattern

2024-02-02 06:41 UTC, karuneshsf commented on sandbox/oauth-example/src/providers/google-oauth2-verify.provider.ts
> +      });
Removed

2024-02-02 06:42 UTC, karuneshsf commented on sandbox/oauth-example/package.json
> +    "loopback4-authentication": "^9.0.2",
updated

2024-02-02 09:30 UTC, yeshamavani requested changes

2024-02-02 09:30 UTC, yeshamavani commented on services/authentication-service/src/models/index.ts
> +export * from './login-activity.model';
yes but still revert it 
will release the service with a minor version bump

2024-02-02 10:33 UTC, yeshamavani commented
Please rebase

2024-02-19 05:28 UTC, yeshamavani commented on sandbox/oauth-example/src/models/auth-user.model.ts
why is this model needed 
we have auth user in authentication-service

2024-03-13 11:00 UTC, karuneshsf commented on sandbox/oauth-example/src/models/auth-user.model.ts
removed it

2024-03-14 06:59 UTC, yeshamavani approved these changes

2024-03-14 06:59 UTC, merged