fix(authentication-service): provide support to manage tokens for user logging in via Azure
sourcefuse/loopback4-microservice-catalog pull request #1925
Opened 2024-01-18 12:28 UTC by arpit1503khanna

## Description

Provide support to manage tokens for user logging in via Azure

Fixes #1924 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-23 13:09 UTC, yeshamavani commented on services/authentication-service/src/providers/types.ts
> +  payload: AnyObject,
why mandatory
wont this affect other strategies

2024-01-23 13:16 UTC, arpit1503khanna commented on services/authentication-service/src/providers/types.ts
> +  payload: AnyObject,
But we are sure , that we will get req and payload.
Can u please elaborate further, how it can affect other strategies
@yeshamavani

2024-02-01 05:52 UTC, yeshamavani commented on services/authentication-service/src/providers/types.ts
> +  payload: AnyObject,
in services/authentication-service/src/providers/google-authentication.provider.ts its added as optional and here its mandatory

2024-03-14 10:13 UTC, yeshamavani requested changes

2024-03-14 10:13 UTC, yeshamavani commented on services/authentication-service/src/providers/azure-authentication.provider.ts
> +        'Content-Type': 'application/x-www-form-urlencoded',
use the const defined in '@sourceloop/core' for the content-type

2024-03-14 10:13 UTC, yeshamavani commented on services/authentication-service/src/providers/azure-authentication.provider.ts
> +        'Content-Type': 'application/x-www-form-urlencoded',
same changes for the remaining providers as well

2024-03-18 06:05 UTC, yeshamavani approved these changes

2024-03-18 06:06 UTC, yeshamavani commented
@arpit1503khanna check the sonar

2024-03-18 12:22 UTC, merged