feat(core): added dynamic tenant connector
sourcefuse/loopback4-microservice-catalog pull request #1953
Opened 2024-01-30 23:15 UTC by karuneshsf

added dynamic tenant connector

GH-1922

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-01 15:02 UTC, a-ganguly approved these changes
Added dynamic tenant connector

2024-02-02 10:16 UTC, yeshamavani requested changes

2024-02-02 10:16 UTC, yeshamavani commented on packages/core/src/keys.ts
> +import {SSMClientConfig} from '@aws-sdk/client-ssm';
??

2024-02-02 10:16 UTC, yeshamavani commented on packages/core/src/providers/custom-datasource.provider.ts
> +          });
a sequelize option also has ti be provided

2024-02-02 10:16 UTC, yeshamavani commented on packages/core/src/providers/custom-datasource.provider.ts
> +              name: 'pgdb',
name is confusing 
only postgres supported ?

2024-02-02 10:16 UTC, yeshamavani commented on packages/core/src/service-sequence.ts
> +      await this.processSiloStorage(context);
why a mandatory action for all

2024-02-02 10:16 UTC, yeshamavani commented on packages/core/src/datasources/auth-db.datasource.ts
why do we need this 
this should be from the application and not component

2024-02-09 11:56 UTC, karuneshsf commented on package.json
> +    "@sourceloop/core": "^11.0.2",
removed

2024-02-09 11:56 UTC, karuneshsf commented on packages/core/package.json
> +    "loopback4-dynamic-datasource": "^1.0.0",
Updated it

2024-02-09 11:56 UTC, karuneshsf commented on packages/core/src/component.ts
> +    this.application.component(Loopback4DynamicDatasourceComponent);
Done

2024-02-09 11:57 UTC, karuneshsf commented on packages/core/src/keys.ts
> +import {SSMClientConfig} from '@aws-sdk/client-ssm';
to get the datasource details from AWS ssm we are using thi spackage

2024-02-09 11:58 UTC, karuneshsf commented on packages/core/src/providers/custom-datasource.provider.ts
> +          });
We will need to update the dynamic data source package, this change is with respect to juggler only.

2024-02-09 11:58 UTC, karuneshsf commented on packages/core/src/providers/custom-datasource.provider.ts
> +              name: 'pgdb',
This is yet supporting only postgres

2024-02-09 11:59 UTC, karuneshsf commented on packages/core/src/service-sequence.ts
> +      await this.processSiloStorage(context);
Removed this, this logic has been shifted in main package using a newly added middleware

2024-02-09 13:49 UTC, a-ganguly approved these changes
Added dynamic tenant connector

2024-02-28 05:46 UTC, Surbhi-sharma1 commented on packages/core/src/services/tenant-identifier-helper.service.ts
> +    return tenantId == null ? null : {id: tenantId};
why do you need to return an object? why not directly return the string?

2024-02-28 06:16 UTC, samarpan-b requested changes
Approach is wrong at many places

2024-02-28 06:16 UTC, samarpan-b commented on packages/core/src/component.ts
> +    if (process.env.SAAS_MODEL === DataSourceModel.SILOED) {
Why SAAS MODEL ? These type of env vars causes confusion and tight coupling.

2024-02-28 06:16 UTC, samarpan-b commented on packages/core/src/component.ts
> +    this.application.bind('AwsSsmHelperService').toClass(AwsSsmHelperService);
Why tight couple with AWS SSM ? What if we want Vault ?

2024-02-28 07:19 UTC, akshatdubeysf requested changes

2024-02-28 07:19 UTC, akshatdubeysf commented on packages/core/src/component.ts
> +    if (process.env.SAAS_MODEL === DataSourceModel.SILOED) {
Why is this logic here?

2024-02-28 07:19 UTC, akshatdubeysf commented on packages/core/src/component.ts
> +      .bind('TenantIdentifierHelperService')
why bind like this instead of this.service or component services array?

2024-02-28 07:19 UTC, akshatdubeysf commented on packages/core/src/keys.ts
> +import {SSMClientConfig} from '@aws-sdk/client-ssm';
this adds a dependency on client-ssm even for packages that don't need it

2024-02-28 07:19 UTC, akshatdubeysf commented on packages/core/src/keys.ts
> +  secretAccessKey: string;
what if this is being provided through means other than env?

2024-02-28 07:19 UTC, akshatdubeysf commented on packages/core/src/providers/custom-datasource-identifier.provider.ts
> +      const tokenWithBearerString = requestCtx.request.headers?.authorization;
can't you just inject the request object in the service?

2024-02-28 07:19 UTC, akshatdubeysf commented on packages/core/src/providers/custom-datasource.provider.ts
> +export class CustomDatasourceProvider
Nothing in the name suggests this depends on SSM

2024-02-28 07:19 UTC, akshatdubeysf commented on packages/core/src/providers/custom-datasource.provider.ts
> +  implements Provider<DatasourceProviderFn>
What if we wanted to add more sources for DB config?

2024-02-28 07:19 UTC, akshatdubeysf commented on packages/core/src/service-sequence.ts
> +      // sonarignore:start
why?

2024-02-28 07:19 UTC, akshatdubeysf commented on packages/core/src/services/aws-ssm-helper.service.ts
> +    return await ssm
why?

2024-03-18 08:12 UTC, yeshamavani commented
Dependent on https://github.com/sourcefuse/loopback4-dynamic-datasource/pull/13

2024-03-18 09:24 UTC, yeshamavani commented on packages/core/src/providers/custom-datasource.provider.ts
> +          });
will be done separately

2024-03-18 09:25 UTC, yeshamavani commented on packages/core/src/providers/custom-datasource.provider.ts
> +              name: 'pgdb',
no all juggler sources supported, changed this

2024-03-18 09:26 UTC, yeshamavani commented on packages/core/src/services/tenant-identifier-helper.service.ts
> +    return tenantId == null ? null : {id: tenantId};
removed

2024-03-18 09:35 UTC, yeshamavani commented on packages/core/src/keys.ts
> +  secretAccessKey: string;
removed

2024-03-18 09:36 UTC, yeshamavani commented on packages/core/src/services/aws-ssm-helper.service.ts
> +    return await ssm
??

2024-03-18 09:37 UTC, yeshamavani commented on packages/core/src/providers/custom-datasource.provider.ts
> +  implements Provider<DatasourceProviderFn>
@dev-hitesh-gupta does the package support this

2024-03-18 09:38 UTC, yeshamavani commented on packages/core/src/services/aws-ssm-helper.service.ts
> +    return await ssm
??

2024-03-18 09:39 UTC, yeshamavani commented on packages/core/src/component.ts
> +    if (process.env.SAAS_MODEL === DataSourceModel.SILOED) {
where else should we add it

2024-03-20 08:01 UTC, yeshamavani commented on packages/core/src/component.ts
> +    this.application.bind('AwsSsmHelperService').toClass(AwsSsmHelperService);
can be overriden via service

2024-03-20 09:15 UTC, a-ganguly approved these changes
Added dynamic tenant connector with required changes discussed

2024-03-21 09:32 UTC, yeshamavani commented on packages/core/src/providers/custom-datasource.provider.ts
> +export class CustomDatasourceProvider
deleted this file

2024-03-21 10:10 UTC, yeshamavani commented on packages/core/src/services/aws-ssm-helper.service.ts
> +    return await ssm
removed

2024-03-26 07:47 UTC, yeshamavani commented on packages/core/src/component.ts
> +    if (process.env.SAAS_MODEL === DataSourceModel.SILOED) {
Now a separate component available users have to bind that

2024-03-26 07:47 UTC, yeshamavani commented on packages/core/src/component.ts
> +      .bind('TenantIdentifierHelperService')
done

2024-03-26 07:48 UTC, yeshamavani commented on packages/core/src/providers/custom-datasource.provider.ts
> +  implements Provider<DatasourceProviderFn>
returns an array now

2024-04-08 13:13 UTC, akshatdubeysf approved these changes

2024-04-08 13:46 UTC, yeshamavani approved these changes

2024-04-08 13:46 UTC, merged