feat(core): add provision in logs to save tenant information
sourcefuse/loopback4-microservice-catalog pull request #1967
Opened 2024-02-06 10:51 UTC by Surbhi-sharma1

add provision in logs to save tenant information

GH-1918

## Description
.

Fixes #1918 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-19 05:42 UTC, yeshamavani reviewed
update the readme as well

2024-02-19 05:42 UTC, yeshamavani commented on packages/core/src/service-sequence.ts
> +      console.log(request.headers?.authorization);
do we need this

2024-02-19 05:42 UTC, yeshamavani commented on packages/core/src/services/tenant-identifier-helper.service.ts
> +    return tenantId == null ? null : {id: tenantId};
??

2024-02-19 05:42 UTC, yeshamavani commented on packages/core/src/types.ts
> +}
where is this used?

2024-02-19 07:10 UTC, Surbhi-sharma1 commented on packages/core/src/service-sequence.ts
> +      console.log(request.headers?.authorization);
will remove it

2024-02-19 07:31 UTC, Surbhi-sharma1 commented on packages/core/src/types.ts
> +}
This will be used in swagger stats config as OnResponseFinish callback function

2024-02-27 13:45 UTC, yeshamavani commented on packages/core/src/services/tenant-identifier-helper.service.ts
> +    }
is there a way to save defaultTenantId incase tenantId is null ?

2024-02-27 14:11 UTC, samarpan-b commented on packages/core/src/services/tenant-identifier-helper.service.ts
> +    }
Why would we want that ? Thats wrong.

2024-02-27 14:24 UTC, akshatdubeysf requested changes

2024-02-27 14:24 UTC, akshatdubeysf commented on packages/core/src/service-sequence.ts
> +      let tenantId!: {id: string} | null;
what about secure sequence? or for some one using the middleware sequence?

2024-02-27 14:24 UTC, akshatdubeysf commented on packages/core/src/services/tenant-identifier-helper.service.ts
> +      return tenantId == null ? null : {id: tenantId};
why do you need to return an object? why not directly return the string?

2024-03-06 08:35 UTC, yeshamavani commented
@Surbhi-sharma1 can this be closed since you created another PR for this?

2024-03-11 05:31 UTC, yeshamavani commented on packages/core/README.md
> +  addTenantIdmiddleware: true,
why does user have to add two config for same thing ?

2024-03-11 06:28 UTC, samarpan-b requested changes

2024-03-11 06:28 UTC, samarpan-b commented on packages/core/package.json
> +    "@types/crypto-js": "^4.2.2",
we should add this to optionaldeps

2024-03-11 06:28 UTC, samarpan-b commented on packages/core/src/middlewares/add-tenantid-action.middleware.ts
> +        throw new HttpErrors.Unauthorized(AuthErrorKeys.InvalidCredentials);
error message is wrong and misleading. Why are we throwing an error here ? We can simply return null in these cases so that application does not start throwing errors just because of this. This key must not cause API to crash.

2024-03-11 06:28 UTC, samarpan-b commented on packages/core/src/middlewares/add-tenantid-action.middleware.ts
> +      request.headers['tenant-id'] = encryptedTenantId;
after adding this to header, whats happening ?

2024-03-11 06:35 UTC, Surbhi-sharma1 commented on packages/core/src/middlewares/add-tenantid-action.middleware.ts
> +      request.headers['tenant-id'] = encryptedTenantId;
whenever User will add to the config:
```
swaggerStatsConfig: {
    basePath: process.env.BASE_PATH ?? '',
    onResponseFinish: (
      req: IncomingMessage,
      res: ServerResponse<IncomingMessage>,
      reqResponse: AnyObject,
    ) => {
      addTenantId(req, res, reqResponse);
    },
  },
```
callback function will be called which decrypt the tenant id and add it to the reqResponse  using the function below

```
export function addTenantId(
  req: IncomingMessage,
  res: ServerResponse<IncomingMessage>,
  reqResponse: AnyObject,
) {
  if (!process.env.TENANT_SECRET_KEY) {
    throw new HttpErrors.Unauthorized(AuthErrorKeys.InvalidCredentials);
  }
  const encryptedTenantId = req.headers['tenant-id'];
  const secretKey = process.env.TENANT_SECRET_KEY as string;
  const decryptedTenantId = CryptoJS.AES.decrypt(
    encryptedTenantId as string,
    secretKey,
  ).toString(CryptoJS.enc.Utf8);
  reqResponse['tenant-id'] = decryptedTenantId;
}
```

2024-03-11 06:35 UTC, Surbhi-sharma1 commented on packages/core/package.json
> +    "@types/crypto-js": "^4.2.2",
ok Sir

2024-03-11 06:36 UTC, Surbhi-sharma1 commented on packages/core/src/middlewares/add-tenantid-action.middleware.ts
> +        throw new HttpErrors.Unauthorized(AuthErrorKeys.InvalidCredentials);
will change accordingly

2024-03-12 07:19 UTC, samarpan-b commented on packages/core/src/middlewares/add-tenantid-action.middleware.ts
> +      request.headers['tenant-id'] = encryptedTenantId;
where have you mentioned this ? Also why into swaggerStatsConfig ?

2024-03-12 07:46 UTC, Surbhi-sharma1 commented on packages/core/src/middlewares/add-tenantid-action.middleware.ts
> +      request.headers['tenant-id'] = encryptedTenantId;
I have mentioned it in readme file 
Swagger stats provides Onresponse Finish function that can be used for performing additional actions

2024-03-12 07:48 UTC, Surbhi-sharma1 commented on packages/core/src/middlewares/add-tenantid-action.middleware.ts
> +      request.headers['tenant-id'] = encryptedTenantId;
Currently working on using same config for adding middleware and addTenantId function to component file directly as mentioned by @yeshamavani

2024-03-14 07:31 UTC, Surbhi-sharma1 commented on packages/core/src/middlewares/add-tenantid-action.middleware.ts
> +      request.headers['tenant-id'] = encryptedTenantId;
Done with the changes

2024-03-14 11:12 UTC, a-ganguly requested changes

2024-03-14 11:14 UTC, Surbhi-sharma1 commented on packages/core/README.md
> +  reqResponse.tenantId = req.headers['tenant-id'];
updated its Readme as per the comment

2024-03-15 09:21 UTC, a-ganguly approved these changes
add provision in logs to save tenant information

2024-03-15 09:26 UTC, merged