feat(sandbox): Add an example of MFA authentication in sandbox
sourcefuse/loopback4-microservice-catalog pull request #2002
Opened 2024-02-21 12:44 UTC by arpit1503khanna

## Description
Add an example of MFA authentication in sandbox

Fixes #1973 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-26 09:13 UTC, yeshamavani commented
@arpit1503khanna  -- https://sonarcloud.io/project/issues?resolved=false&pullRequest=2002&id=sourcefuse_loopback4-microservice-catalog&open=AY3LsraK7m1cqhCYw4hH

2024-02-26 09:31 UTC, yeshamavani requested changes

2024-02-26 09:31 UTC, yeshamavani commented on sandbox/auth-mfa-google-example/.env.example
> +JWT_ISSUER=
if any extra env needed please add

2024-02-26 09:31 UTC, yeshamavani commented on sandbox/auth-mfa-google-example/src/application.ts
> +    /////// My Additions
better comment

2024-02-26 09:31 UTC, yeshamavani commented on sandbox/auth-mfa-google-example/src/application.ts
> +    this.bind(Strategies.Passport.LOCAL_STRATEGY_FACTORY.key).toProvider(
why local strategy needed

2024-02-26 09:31 UTC, yeshamavani commented on sandbox/auth-mfa-google-example/src/application.ts
> +    );
with the latest version of loopback4-authentication this should not be needed please check and confirm

2024-02-26 09:31 UTC, yeshamavani commented on sandbox/auth-mfa-google-example/src/opentelemetry-registry.ts
??

2024-02-26 09:31 UTC, yeshamavani commented on sandbox/auth-mfa-google-example/src/providers/mfa.provider.ts
> +// import { AuthUser } from '@sourceloop/authentication-service';
remove comments

2024-02-26 11:07 UTC, arpit1503khanna commented on sandbox/auth-mfa-google-example/src/application.ts
> +    this.bind(Strategies.Passport.LOCAL_STRATEGY_FACTORY.key).toProvider(
The curent configuration requires to give a local startegy

2024-02-26 11:33 UTC, arpit1503khanna commented on sandbox/auth-mfa-google-example/.env.example
> +JWT_ISSUER=
Not in this example

2024-02-26 11:35 UTC, arpit1503khanna commented on sandbox/auth-mfa-google-example/src/application.ts
> +    /////// My Additions
Done

2024-02-26 11:36 UTC, arpit1503khanna commented on sandbox/auth-mfa-google-example/src/application.ts
> +    );
Yes, not needed

2024-02-26 11:47 UTC, yeshamavani requested changes

2024-02-26 11:47 UTC, yeshamavani commented on sandbox/auth-mfa-google-example/src/application.ts
> +    this.bind(Strategies.Passport.LOCAL_STRATEGY_FACTORY.key).toProvider(
which API needed this?

2024-02-26 11:47 UTC, yeshamavani commented on sandbox/auth-mfa-google-example/src/application.ts
> +      method: OtpMethodType.OTP,
shouldnt this be google?
why binded twice

2024-03-18 11:09 UTC, yeshamavani commented
Cant be merge it.
MFA strategy needs changes google and otp

2024-03-18 11:09 UTC, closed without merging