fix(user-tenant-service): secure PATCH and PUT users API
sourcefuse/loopback4-microservice-catalog pull request #2005
Opened 2024-02-26 07:42 UTC by Tyagi-Sunny

secure PATCH and PUT users API

2004

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-26 07:56 UTC, samarpan-b requested changes

2024-02-26 07:56 UTC, samarpan-b commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +    const isAllowed =
Can we move this to a service class please ? Also we need to make sure that its overridable logic.

2024-02-26 07:56 UTC, samarpan-b commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
>      return this.roleRepository.deleteById(roleId);
A user should not be allowed to delete a role which contains permissions which he himself doesnt have.

2024-02-26 07:56 UTC, samarpan-b commented on services/user-tenant-service/src/services/user-operations.service.ts
> +    if (id === currentUser.id) {
why a blanket ban here ? A user should be able to edit his other profile details.

2024-02-26 10:08 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
>      return this.roleRepository.deleteById(roleId);
ok , noted

2024-02-26 10:13 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +    const isAllowed =
this only include crud operation directly from repository, do we create a separate service for it?

2024-02-26 10:14 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
>      return this.roleRepository.deleteById(roleId);
done

2024-02-27 06:17 UTC, samarpan-b commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +    const isAllowed =
create a tenant-operations service.

2024-02-27 06:23 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/controllers/tenant-role.controller.ts
> +    const isAllowed =
ok sir

2024-02-27 11:17 UTC, akshatdubeysf requested changes

2024-02-27 11:38 UTC, samarpan-b commented on services/user-tenant-service/src/services/user-operations.service.ts
> +    if (id === currentUser.id) {
Not allowed @akshatdubeysf . Another super admin will have to do that. Thats how a system will always have a super admin.

2024-02-27 11:45 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/services/user-operations.service.ts
> +    if (id === currentUser.id) {
updated sir

2024-02-27 12:31 UTC, akshatdubeysf commented on services/user-tenant-service/src/services/user-operations.service.ts
> +    if (id === currentUser.id) {
If we take example of something like GitHub or Slack, isn't that something that should be allowed?

2024-02-27 12:32 UTC, akshatdubeysf commented on services/user-tenant-service/src/services/user-operations.service.ts
> +    if (id === currentUser.id) {
Considering we are developing this for the community

2024-02-27 12:55 UTC, akshatdubeysf commented on services/user-tenant-service/src/services/user-operations.service.ts
> +    if (id === currentUser.id) {
@samarpan-b

2024-02-27 14:59 UTC, akshatdubeysf commented on services/user-tenant-service/src/services/user-operations.service.ts
> +    if (id === currentUser.id) {
Ok

2024-03-04 11:17 UTC, samarpan-b requested changes

2024-03-04 11:17 UTC, samarpan-b commented on services/user-tenant-service/src/services/tenant-operations.service.ts
> +    const isAllowed =
We also need to check if permission is true or not.

2024-03-04 11:18 UTC, samarpan-b commented on services/user-tenant-service/src/services/tenant-operations.service.ts
> +    const isAllowed =
add a test case for this too.

2024-03-05 05:13 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/services/tenant-operations.service.ts
> +    const isAllowed =
test case already added

2024-03-05 05:14 UTC, Tyagi-Sunny commented on services/user-tenant-service/src/services/tenant-operations.service.ts
> +    const isAllowed =
what's meaning of permission true

2024-03-05 05:16 UTC, samarpanB commented on services/user-tenant-service/src/services/tenant-operations.service.ts
> +    const isAllowed =
Ah this is from token. Then not needed.

2024-03-05 05:17 UTC, samarpanB approved these changes

2024-03-05 05:17 UTC, samarpan-b approved these changes

2024-03-12 07:15 UTC, akshatdubeysf approved these changes

2024-03-12 10:56 UTC, merged