feat(audit-service): multi tenant support
sourcefuse/loopback4-microservice-catalog pull request #2027
Opened 2024-03-08 13:41 UTC by Tyagi-Sunny

## Description

multi tenant support

MIGRATION CHANGE:
migration-20240803165830- multi tenant support
migration-20231222043349- multi tenant support
migration-20231222043401- multi tenant support
migration-20231222043416- multi tenant support
migration-20210423140543- multi tenant support
migration-20230608151724- multi tenant support
migration-20230608151805- multi tenant support

Fixes #1942 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-20 08:59 UTC, yeshamavani commented on services/audit-service/src/__tests__/integration/export-log.controller.unit.ts
> +import {Job} from '../../models/tenant-support';
@Tyagi-Sunny

2024-03-20 09:01 UTC, yeshamavani commented on services/audit-service/src/controllers/audit.controller.ts
> +        // tenantId: this.currentUser.tenantId, --- check it on multi tenant support
@Tyagi-Sunny

2024-03-20 10:40 UTC, Tyagi-Sunny commented on services/audit-service/src/__tests__/integration/export-log.controller.unit.ts
> +import {Job} from '../../models/tenant-support';
added

2024-03-20 10:40 UTC, Tyagi-Sunny commented on services/audit-service/src/component.ts
> +    }
ok

2024-03-27 06:42 UTC, yeshamavani commented
This and https://github.com/sourcefuse/loopback4-audit-log/pull/103/files are inter-related 
separate the changes of @sourceloop/core in another PR 
as that has to be released first

2024-04-01 13:48 UTC, yeshamavani commented on services/audit-service/package.json
> +    "@sourceloop/core": "file:/home/sunny.tyagi/Desktop/27_march_comments/loopback4-microservice-catalog/packages/core/sourceloop-core-13.0.0.tgz",
Dependency on https://github.com/sourcefuse/loopback4-microservice-catalog/pull/2063 and 
https://github.com/sourcefuse/loopback4-audit-log/pull/103

2024-04-01 13:48 UTC, yeshamavani commented on services/audit-service/src/__tests__/fixtures/dummy-application.ts
> +    this.component(AuditLogComponent);
why ?

2024-04-02 06:34 UTC, Tyagi-Sunny commented on services/audit-service/src/__tests__/fixtures/dummy-application.ts
> +    this.component(AuditLogComponent);
as we also need to dynamically change models in audit log package

2024-04-02 06:44 UTC, Tyagi-Sunny commented on services/audit-service/src/__tests__/fixtures/dummy-application.ts
> +    this.component(AuditLogComponent);
changed

2024-04-08 06:57 UTC, samarpan-b approved these changes

2024-04-09 10:48 UTC, yeshamavani requested changes

2024-04-09 10:48 UTC, yeshamavani commented on services/audit-service/src/controllers/audit.controller.ts
> +import {AuditLog, Job, MappingLog} from '../models/tenant-support';
check this

2024-04-10 07:07 UTC, Tyagi-Sunny commented on services/audit-service/src/controllers/audit.controller.ts
> +import {AuditLog, Job, MappingLog} from '../models/tenant-support';
checked

2024-04-10 07:13 UTC, yeshamavani approved these changes

2024-04-10 07:13 UTC, merged