feat(task-service): delete process instances on Camunda for deleted tasks
sourcefuse/loopback4-microservice-catalog pull request #2028
Opened 2024-03-11 04:50 UTC by Swati0077

## Description

1. Delete process instances on Camunda for deleted tasks.
2. Remove ? to mark externalId as mandatory field.
3. Add Camunda's process instances delete API to delete for process instances from Camunda 

Fixes GH-1972

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [x] Any dependent changes have been merged and published in downstream modules

2024-03-11 05:01 UTC, yeshamavani commented
Will be a breaking change

2024-03-11 05:24 UTC, samarpan-b requested changes

2024-03-11 05:24 UTC, samarpan-b commented on services/task-service/src/models/task.model.ts
> +  externalId: string;
Why are we changing this ? This will require DB migration as well, which I would like to avoid.

2024-03-11 05:24 UTC, samarpan-b commented on services/task-service/src/controllers/task.controller.ts
> +        this.camundaService
This needs to be done in deletebyid API as well. Also check if this should be done on task completion API or not.

2024-03-11 06:49 UTC, Swati0077 commented on services/task-service/src/models/task.model.ts
> +  externalId: string;
Yes, considering the wide variety of use cases and discussion with @akshatdubeysf  we can't limit this to be a mandatory field.
So I have changed to the existing code , making it non mandatory

2024-03-11 06:50 UTC, Swati0077 commented on services/task-service/src/controllers/task.controller.ts
> +        this.camundaService
Added for deleteByID as well..
For completion API , its already working fine.

2024-03-12 05:33 UTC, samarpan-b commented on services/task-service/src/services/camunda.service.ts
> +            query: {
skipCustomListeners should also be set to true

2024-03-12 05:34 UTC, samarpan-b commented on services/task-service/src/services/camunda.service.ts
> +            query: {
https://docs.camunda.org/manual/7.13/reference/rest/process-definition/delete-process-definition/#query-parameters

2024-03-12 06:37 UTC, Swati0077 commented on services/task-service/src/services/camunda.service.ts
> +            query: {
added

2024-03-12 06:48 UTC, samarpan-b approved these changes

2024-03-12 06:59 UTC, merged