feat(user-onboarding): base code for user-onboarding lib
sourcefuse/loopback4-microservice-catalog pull request #203
Opened 2021-05-11 12:47 UTC by vaibhavmauryasf

## Description
Base code of the user-onboarding client
Fixes # (issue)
https://github.com/sourcefuse/loopback4-microservice-catalog/issues/173
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [x] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-06-03 14:28 UTC, akshatdubeysf requested changes

2021-06-03 14:28 UTC, akshatdubeysf commented on packages/user-onboarding/README.md
> +# UserOnboarding
Add Readme on how to use, etc.

2021-06-03 14:28 UTC, akshatdubeysf commented on packages/user-onboarding/package.json
> +{
change it to something like @sourceloop/user-onboarding-client

2021-06-03 14:28 UTC, akshatdubeysf commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-service.service.ts
> +        classes: 'class-1 class-2',
are these required?

2021-06-03 14:28 UTC, akshatdubeysf commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-service.service.ts
> +        this.tourStoreService.saveState({tourId: tourInstance.tourId,state:{sessionId: this.tourStoreService.getSessionId(),step: tour.getCurrentStep().id}});
Looks like the code is not prettified, use something like [this](https://www.npmjs.com/package/prettier).

2021-06-03 14:28 UTC, akshatdubeysf commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-store-service.service.ts
> +    this.commandMap.delete("SaveTourCommand");
I don't think you need this line, as you are setting a value on this key just after this line.

2021-06-03 14:28 UTC, akshatdubeysf commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/user-onboarding-lib.component.ts
> +import { Component, OnInit } from '@angular/core';
This is not needed.

2021-06-03 14:28 UTC, akshatdubeysf commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/user-onboarding-lib.service.ts
> +import { Injectable } from '@angular/core';
??

2021-06-03 14:28 UTC, akshatdubeysf commented on packages/user-onboarding/projects/user-onboarding-lib/src/public-api.ts
> +export * from './models/StateParameters';
You don't need to export individual models if you have an index file in the models folder.

2021-06-03 14:29 UTC, akshatdubeysf commented
Also add a link to the user-onboarding issue.

2021-06-03 14:29 UTC, akshatdubeysf commented
Fix linting issues.

2021-06-03 14:39 UTC, vaibhavmauryasf commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-service.service.ts
> +        classes: 'class-1 class-2',
yes sir, like if someone wants to cancel the tour in between so there's a cross icon for that that's why cancelIcon is used and classes are regarding the theming of the tour

2021-06-03 14:45 UTC, vaibhavmauryasf commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-store-service.service.ts
> +    this.commandMap.delete("SaveTourCommand");
the line with the delete statement?

2021-06-07 05:24 UTC, akshatdubeysf commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-store-service.service.ts
> +    this.commandMap.delete("SaveTourCommand");
Yes

2021-06-07 05:30 UTC, vaibhavmauryasf commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-store-service.service.ts
> +    this.commandMap.delete("SaveTourCommand");
already fixed sir

2021-06-07 08:16 UTC, akshatdubeysf commented
Fixed spelling mistakes in readme.

2021-06-07 08:55 UTC, akshatdubeysf approved these changes

2021-06-07 11:10 UTC, akshatdubeysf approved these changes

2021-06-09 10:48 UTC, merged