feat(authentication-service): enable tenant aware metrics
sourcefuse/loopback4-microservice-catalog pull request #2044
Opened 2024-03-15 10:17 UTC by arpit1503khanna

## Description
Enable tenant aware metrics, to fetch tenant specific information from the login activity table

Fixes #1980 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-19 09:29 UTC, yeshamavani requested changes

2024-03-19 09:29 UTC, yeshamavani commented on services/authentication-service/src/models/user-view.model.ts
migrations for thsi view?

2024-03-19 09:29 UTC, yeshamavani commented on services/authentication-service/src/repositories/sequelize/user-view.repository.ts
Follow SOLID principles 
all the logic should not be a part of the repository
move to a separate service class

2024-03-19 09:29 UTC, yeshamavani commented on services/authentication-service/src/repositories/user-view.repository.ts
same
can create a common service

2024-03-19 09:30 UTC, yeshamavani reviewed
what about the changes for the auth/login and auth/token API

2024-03-22 13:25 UTC, yeshamavani requested changes

2024-03-22 13:25 UTC, yeshamavani commented on services/authentication-service/src/repositories/sequelize/login-activity.repository.ts
its better to move this logic to a service class, to avoid duplicate code for juggler and sequelize repo.

2024-03-22 13:36 UTC, arpit1503khanna commented on services/authentication-service/src/repositories/sequelize/login-activity.repository.ts
ok

2024-04-01 05:34 UTC, yeshamavani commented on services/authentication-service/src/modules/auth/providers/resource-owner-verify.provider.ts
> +    public userViewService: UserViewService,
do we really need these changes now 
using view insted of model ?

2024-04-01 06:04 UTC, arpit1503khanna commented on services/authentication-service/src/modules/auth/providers/resource-owner-verify.provider.ts
> +    public userViewService: UserViewService,
I suppose yes, because user model does not give the tenantId, which is why userView was created.
@yeshamavani

2024-04-01 06:06 UTC, yeshamavani commented on services/authentication-service/src/modules/auth/providers/resource-owner-verify.provider.ts
> +    public userViewService: UserViewService,
but that was needed when using the tenantGuard 
but since we dont use it now still needed ?

2024-04-01 10:28 UTC, arpit1503khanna commented on services/authentication-service/src/modules/auth/providers/resource-owner-verify.provider.ts
> +    public userViewService: UserViewService,
Ohkk, it's not needed. I'll make the necessary changes

2024-04-03 05:38 UTC, yeshamavani requested changes
we dont need the user view now remove the extra changes

2024-04-04 08:54 UTC, yeshamavani approved these changes

2024-04-04 10:36 UTC, a-ganguly approved these changes
Enable tenant aware metrics

2024-04-04 10:36 UTC, merged