feat(authentication-service): implement configurable hashing
sourcefuse/loopback4-microservice-catalog pull request #2048
Opened 2024-03-19 12:27 UTC by Surbhi-sharma1

implement configurable hashing

GH-2038

## Description

Configurable Hashing algorithm option

Fixes #2038 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-20 06:12 UTC, yeshamavani requested changes

2024-03-20 06:12 UTC, yeshamavani commented on services/authentication-service/package.json
> +    "bcrypt": "^5.0.1"
instead of this cant we move this to devdeps and remove the provider binding so if user wants to use bcrypt then only the dependency will be installed or else his preferred dependency will be used 
@samarpan-b @a-ganguly  any thoughts on this

2024-03-20 07:04 UTC, Surbhi-sharma1 commented on services/authentication-service/package.json
> +    "bcrypt": "^5.0.1"
In that case I will have to provide different hashing methods using providers but  need to provide default implementation for backward compatibility

2024-03-22 05:34 UTC, Surbhi-sharma1 commented on services/authentication-service/package.json
> +    "bcrypt": "^5.0.1"
Done with the changes

2024-03-22 06:01 UTC, a-ganguly approved these changes
implement configurable hashing

2024-03-22 10:38 UTC, yeshamavani approved these changes

2024-03-22 10:38 UTC, merged