fix(bpmn-service): added and changed permission for execute workflow api
sourcefuse/loopback4-microservice-catalog pull request #2060
Opened 2024-03-27 09:57 UTC by ajay-prajapati07

## Description

Added a new permission to execute workflow , and added it to the concerned API.

Fixes GH-2053

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-27 11:02 UTC, ajay-prajapati07 commented on services/bpmn-service/src/enums/permission-key.enum.ts
added a numeric permission

2024-03-28 06:27 UTC, yeshamavani approved these changes

2024-03-28 06:28 UTC, yeshamavani requested changes

2024-03-28 06:28 UTC, yeshamavani commented on services/bpmn-service/src/controllers/workflow.controller.ts
> +    permissions: [PermissionKey.ExecuteWorkflow],
that numeric permission will be added here as well

2024-03-29 05:47 UTC, ajay-prajapati07 commented on services/bpmn-service/src/controllers/workflow.controller.ts
> +    permissions: [PermissionKey.ExecuteWorkflow],
made required changes

2024-03-29 06:22 UTC, yeshamavani approved these changes

2024-03-29 06:22 UTC, merged