refactor(authentication-service): deprecate login token two in one api
sourcefuse/loopback4-microservice-catalog pull request #2068
Opened 2024-04-02 11:08 UTC by yeshamavani

gh-00

## Description

deprecate login token two in one api '/auth/login-token'

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-04-02 14:26 UTC, samarpan-b approved these changes

2024-04-02 14:26 UTC, samarpan-b requested changes

2024-04-02 14:26 UTC, samarpan-b commented on services/authentication-service/README.md
> +We would like to inform you that we have deprecated `'/auth/login-token'` due to security vulnerabilities. Your immediate action is required to transition away from its usage. We encourage you to tra
Dont add this on top. Add it to the bottom.

2024-04-03 14:11 UTC, yeshamavani commented on services/authentication-service/README.md
> +We would like to inform you that we have deprecated `'/auth/login-token'` due to security vulnerabilities. Your immediate action is required to transition away from its usage. We encourage you to tra
done

2024-04-08 13:47 UTC, merged