feat(reporting-service): supports subqueries, multilevel function, da…
sourcefuse/loopback4-microservice-catalog pull request #2071
Opened 2024-04-08 08:57 UTC by SouravSF

…taset filter, sql in dataset

MIGRATION CHANGE:
migration-20240408121519- adds new column data_set_query_sql in datasets table

BREAKING CHANGE:
updated StructuredQueryInterface

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-06 10:25 UTC, akshatdubeysf requested changes

2024-09-23 13:03 UTC, SouravSF commented on services/reporting-service/src/interfaces/structured-query.interface.ts
> +  on: WhereCondition | WhereCondition[];
The reason for allowing both a single WhereCondition and an array of WhereCondition[] in the JoinClause is to support both simple and complex join conditions. example: {
  type: 'INNER',
  source: 'users',
  on: { field: 'departmentId', operator: '=', value: 'department.id' }
} also for complex: {
  type: 'LEFT',
  source: 'orders',
  on: [
    { field: 'userId', operator: '=', value: 'users.id' },
    { field: 'orderStatus', operator: 'IN', value: ['delivered', 'shipped'] }
  ]
}  so this provides the flexibility that can be utilized by end users to create various combinations.

2024-09-23 13:03 UTC, SouravSF commented on services/reporting-service/src/providers/query-binding-object.provider.ts
> +    return new this.BindingManagerClass();
this has been updated

2024-09-23 13:04 UTC, SouravSF commented on services/reporting-service/src/services/data-sets.service.ts
> +    if (dataSet.dataSetQuerySQL && this.sqlValidator) {
Yes, this is by design only if a validator is added it will then check , else it will continue as is. I am now adding an info log to inform that they are missing a validator and they can attach it, if they need it.

2024-09-23 13:05 UTC, SouravSF commented on services/reporting-service/src/utils/query-binding-manager.ts
> +    const key = `param${this.index++}`;
added a uuid instead of integer. So the v4 would not create duplicates., this wouldnt have been an issue since i was anyways using it as transient context

2024-09-23 13:06 UTC, SouravSF commented on services/reporting-service/src/utils/sequelize-query.utils.ts
> +    const bindingManager = await this.app.get<QueryBinding>(
the default scope is always transient so the binding was done, but I have further added inScope with transient in component

2024-09-24 08:15 UTC, akshatdubeysf commented on services/reporting-service/src/interfaces/structured-query.interface.ts
> +  on: WhereCondition | WhereCondition[];
oki

2024-09-24 08:17 UTC, akshatdubeysf commented on services/reporting-service/src/providers/query-binding-object.provider.ts
> +    return new this.BindingManagerClass();
why do we even need this provider if it just takes a binding and returns it

2024-09-30 07:18 UTC, yeshamavani commented
Approved by @akshatdubeysf

2024-09-30 07:18 UTC, merged