feat(sandbox): add an auth MFA example
sourcefuse/loopback4-microservice-catalog pull request #2079
Opened 2024-04-29 07:20 UTC by arpit1503khanna

## Description
Add an auth MFA example in sandbox

Fixes #1973 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-07 07:21 UTC, yeshamavani requested changes

2024-05-30 07:07 UTC, Surbhi-sharma1 commented on sandbox/auth-mfa-example/package.json
> +  "author": "arpit1503khanna<arpit.khanna@sourcefuse.com>",
Done

2024-05-30 10:36 UTC, Surbhi-sharma1 commented on sandbox/auth-mfa-example/src/application.ts
> +
Removed Resource OwnerStrategy
local is required.

2024-05-30 10:36 UTC, Surbhi-sharma1 commented on sandbox/auth-mfa-example/src/application.ts
> +    this.bind(TenantUtilitiesBindings.GuardService).toClass(TenantGuardService);
Removed

2024-06-05 05:49 UTC, yeshamavani approved these changes

2024-06-05 05:53 UTC, merged