feat(audit-service): support for multiple actedon and actiongroup
sourcefuse/loopback4-microservice-catalog pull request #2116
Opened 2024-06-20 05:39 UTC by yeshamavani

gh-2115

## Description

now the archive API accepts a list of actedOn and actionGroup

Fixes #2115 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?
Created a sample application to test this particular feature.

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-20 07:03 UTC, yeshamavani commented on services/audit-service/src/services/job-processing.service.ts
> +            customFilter.actedOn = this.getFilter(condition.actedOn);
created another function to improve

2024-06-20 12:10 UTC, samarpan-b requested changes

2024-06-20 12:10 UTC, samarpan-b commented on services/audit-service/src/utils/file-check.ts
> +  return false;
This entire thing can be done in single statement.

2024-06-20 12:10 UTC, samarpan-b commented on services/audit-service/src/utils/file-check.ts
> +  return false;
This can be optimized further

2024-06-20 12:10 UTC, samarpan-b commented on services/audit-service/src/utils/file-check.ts
> +): boolean {
optimize these if-else blocks

2024-06-20 14:25 UTC, samarpan-b requested changes

2024-06-20 14:25 UTC, samarpan-b commented on services/audit-service/src/utils/file-check.ts
> +  );
```suggestion
  const {actedOn, actedOnList} = filterUsed;
  const customActedOnList = customFilter.actedOnList;
  actedOnList = actedOnList ?? [];
  
  if (!!actedOn) {
    actedOnList = [...new Set([...actedOnList, actedOn])];
  }
  
  return (
    !customActedOnList ||
    actedOnList.length === 0 || 
    haveCommonElements(customActedOnList, actedOnList)
  );
```

2024-06-20 14:25 UTC, samarpan-b commented on services/audit-service/src/utils/file-check.ts
> +  );
```suggestion
  const actionGroupList = filterUsed.actionGroupList;
  const customActionGroupList = customFilter.actionGroupList;
  return (
    !customActionGroupList ||
    !actionGroupList ||
    haveCommonElements(actionGroupList, customActionGroupList)
  );
```

2024-06-20 14:25 UTC, samarpan-b commented on services/audit-service/src/utils/file-check.ts
> +  return (
Do the same changes here too

2024-06-20 14:25 UTC, samarpan-b commented on services/audit-service/src/utils/file-check.ts
> +  return (
same changes

2024-06-21 09:10 UTC, samarpan-b requested changes

2024-06-21 09:10 UTC, samarpan-b commented on services/audit-service/src/utils/file-check.ts
> +  );
```suggestion
  return (
    !customActedOnList || actedOnList.length === 0 ||
    haveCommonElements(customActedOnList, actedOnList)
  );
```

2024-06-26 11:39 UTC, yeshamavani commented on services/audit-service/src/utils/file-check.ts
> +  );
done

2024-06-26 11:39 UTC, yeshamavani commented on services/audit-service/src/utils/file-check.ts
> +  return (
done

2024-06-26 11:39 UTC, yeshamavani commented on services/audit-service/src/utils/file-check.ts
> +  return (
done

2024-06-26 13:18 UTC, merged