fix(authentication-service):  added idp server controller for login and discovery endpoint
sourcefuse/loopback4-microservice-catalog pull request #2131
Opened 2024-07-10 06:27 UTC by prernagp

## Description

Added IDP server controller for login and discovery endpoint

Fixes # (issue) #2034 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated

2024-07-16 10:22 UTC, sfvishalgupta reviewed
I can not see all the endpoints mentioned here, https://docs.google.com/document/d/1r2v55eC5dbGBsA5ka_JQnzIIO80hdTqA6p8qCRKQmqU/edit
Also please specify and work on key rotation

2024-08-06 09:30 UTC, samarpan-b commented on services/authentication-service/package.json
> +    "start": "node -r source-map-support/register .",
why this ?

2024-08-07 08:54 UTC, samarpan-b commented on services/authentication-service/src/modules/auth/controllers/identity-server.controller.ts
> +    const token = auth?.replace(/bearer /i, '');
Cant we reuse existing code ?

2024-12-02 09:00 UTC, samarpan-b approved these changes

2024-12-02 11:16 UTC, yeshamavani requested changes

2024-12-02 11:16 UTC, yeshamavani commented on packages/core/src/components/bearer-verifier/providers/services-bearer-asym-token-verifier.ts
@prernagp dont we need to do similar changes to 'FacadesBearerAsymmetricTokenVerifyProvider' - packages/core/src/components/bearer-verifier/providers

2024-12-04 11:17 UTC, prernagp commented on packages/core/src/components/bearer-verifier/providers/services-bearer-asym-token-verifier.ts
done.

2024-12-04 12:08 UTC, yeshamavani commented on packages/core/src/components/bearer-verifier/repositories/revoked-token.repository.ts
> +    @inject(`datasources.${AuthDbSourceName}`)
Looks like done by mistake 
This is a key value store - redis 
should be 'AuthCacheSourceName'

2024-12-04 12:09 UTC, yeshamavani commented on packages/cli/README.md
Please revert this file

2024-12-05 08:49 UTC, merged