docs: add openapi spec docs in examples and improve the docs in services
sourcefuse/loopback4-microservice-catalog pull request #215
Opened 2021-05-19 21:30 UTC by sumiter92

## Description

Add openapi spec docs in examples and improve the documentation in services and examples.

Fixes # 211

## Type of change

Please delete options that are not relevant.

- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated

2021-05-20 11:00 UTC, samarpan-b commented
Not following conventional commit guidelines

2021-05-20 11:01 UTC, samarpan-b commented
https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/DEVELOPING.md#commit-message-guidelines

2021-05-21 07:19 UTC, samarpan-b commented
We also need to replace mention of loopback4-microservices-catalog with Sourceloop, all through the readmes. Also add link to https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/DEVELOPING.md in root readme

2021-05-26 05:43 UTC, samarpan-b requested changes

2021-05-26 05:43 UTC, samarpan-b commented on services/audit-service/README.md
> +Visit the [OpenAPI spec docs](../../sandbox/audit-ms-example/openapi.md)
why audit example ?

2021-05-26 05:43 UTC, samarpan-b commented on services/bpmn-service/README.md
> +Visit the [OpenAPI spec docs](../../sandbox/workflow-ms-example/openapi.md)
why ref to example ?

2021-06-03 12:45 UTC, sumiter92 commented on services/bpmn-service/README.md
> +Visit the [OpenAPI spec docs](../../sandbox/workflow-ms-example/openapi.md)
modified

2021-06-03 12:45 UTC, sumiter92 commented on services/audit-service/README.md
> +Visit the [OpenAPI spec docs](../../sandbox/audit-ms-example/openapi.md)
modified

2021-06-03 12:46 UTC, sumiter92 commented
> We also need to replace mention of loopback4-microservices-catalog with Sourceloop, all through the readmes. Also add link to https://github.com/sourcefuse/loopback4-microservice-catalog/blob/master/DEVELOPING.md in root readme

done

2021-06-04 17:39 UTC, merged