fix(search-service): export datasource name as expected by cli in search service
sourcefuse/loopback4-microservice-catalog pull request #2189
Opened 2024-10-28 06:21 UTC by Surbhi-sharma1

export datasource name as expected by cli in search service

GH-2136

## Description
export datasource name as expected by cli in search service

Fixes #2136 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2024-10-28 06:57 UTC, samarpan-b requested changes

2024-10-28 06:57 UTC, samarpan-b commented on services/search-service/src/keys.ts
> +export const DATASOURCE_NAME = 'SearchServiceDb';
Where is it used ?

2024-10-28 07:07 UTC, Surbhi-sharma1 commented on services/search-service/src/keys.ts
> +export const DATASOURCE_NAME = 'SearchServiceDb';
Exported datasourceName as required by the CLI to resolve the 'datasource name not exported' error while using search service. currently its exported as SearchServiceBindings.DATASOURCE_NAME .

2024-10-28 07:14 UTC, yeshamavani commented on services/search-service/src/keys.ts
> +export const DATASOURCE_NAME = 'SearchServiceDb';
the datasource key is required while we generate search service through cli 
for all the services it is directly exported but in search search-service it is exported via a 'SearchServiceBindings.DATASOURCE_NAME'

2024-11-19 10:31 UTC, yeshamavani commented
@Surbhi-sharma1 revert the package-lock file changes

2024-11-19 10:38 UTC, Surbhi-sharma1 commented
> @Surbhi-sharma1 revert the package-lock file changes

Done

2024-11-19 11:03 UTC, merged