feat(payment-service): adds payment-service feature
sourcefuse/loopback4-microservice-catalog pull request #257
Opened 2021-07-13 13:29 UTC by sumiter92

## Description

Adds payment-service that supports configurable multiple payment gateways. 

Fixes  #256 #212 

## Type of change

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] Code conforms with the style guide

2021-07-29 08:59 UTC, akshatdubeysf commented
@sumiter92 please look into the sonar issues as well.

2021-08-05 14:20 UTC, SouravSF commented on services/payment-service/src/controllers/transactions.controller.ts
> +      `http://localhost:3000/transactions/orderid/${newOrder.id}`,
why do we need a hardcoded redirect here?

2021-08-05 16:23 UTC, anujkalka requested changes
Needs lots of improvements, summary
1) DB need to be revisited, needs lots of improvement to caputre data
2) Use DB transactions on all payment operations. and rollback on errors
3) Exception handling not implemented anywhere
4) Returning HTML in api responses
5) Classes need to be restructured. it should not have gateway. name checks in code like if stripe do this if razor do ths.. this is not extendable. This can be improved using passing gateway object in constructer and calling functions from parent class .. 
6) striepe and razor classes should only have gateway related operations. All DB operations  shoudl be writen seperatly and can be called seperatly, as same data need to be stored with any payment gateway.

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/gateway.provider.ts
> +    if (payorder.paymentmethod === 'razorpay') {
This code is not generic, static checks for payment gateways.. insted of this, payment gateway should be provided argument in constructer and the generic method of this provider gateway would call the payment gateway's method via that constructer refrence.. This makes this class generic to be used with any payment gatewy. This gateway class would be initialized with specific payment gateway class when it is to be initilized

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/gateway.provider.ts
> +      if (gatewayType === 'stripe') {
Same,, static check of gateway should not be there.. not extandable

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/razorpay/razorpay.provider.ts
> +          return `<html>
Returning HTML. from API ??

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/razorpay/razorpay.provider.ts
> +          currency: 'INR',
Static currency ?

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/razorpay/razorpay.provider.ts
> +          await instance.orders.create(
1) Payment method class should only have functions related to payment gateway intraction
2) All db related operations should be handeled seperatly, as same wouldbe used in other payment gateways also.
3) While dealing with payment and database.. always use transactions.

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/razorpay/razorpay.provider.ts
> +                  <head><title>Order in-process. Please wait ...</title><style>.razorpay-payment-button{display:none;}</style></head>
Reason of returning HTML from API ?

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/razorpay/razorpay.provider.ts
> +            <head><title>Order in-process. Please wait ...</title><style>.razorpay-payment-button{display:none;}</style></head>
HTML

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/razorpay/razorpay.provider.ts
> +          `Select * FROM main.orders where metadata->>'razorpayOrderID'='${chargeResponse.razorpay_order_id}';`,
Reason of using SQL

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/razorpay/razorpay.provider.ts
> +          transactionId,
Use transactions whereever possible

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/razorpay/razorpay.provider.ts
> +        transaction.res.refundDetails = refund;
Excption handling

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/stripe/stripe.provider.ts
> +          <title>Stripe Payment Demo</title>
HTML should not be returned

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/src/providers/stripe/stripe.provider.ts
> +        const paymentId = await transaction?.res?.chargeResponse?.id;
Same comments as in razorpay
1) DB operations should be seperate from payment, as same operations are happenign ere
2) use DB transacions and rollback on failover
3) no exception handling
4) dont return HTML

2021-08-05 16:23 UTC, anujkalka commented on services/payment-service/migrations/sqls/20210722063857-init-up.sql
> +CREATE  TABLE main.orders (
DB need to be revisited if this is to be made generic, many important  fields are missing

2021-08-06 08:58 UTC, samarpan-b commented on services/payment-service/src/controllers/transactions.controller.ts
> +      `http://localhost:3000/transactions/orderid/${newOrder.id}`,
@sumiter92 this needs to come from DB or env

2021-08-19 09:19 UTC, sumiter92 commented on services/payment-service/src/controllers/transactions.controller.ts
> +      `http://localhost:3000/transactions/orderid/${newOrder.id}`,
done

2021-08-19 09:20 UTC, sumiter92 commented on services/payment-service/src/providers/gateway.provider.ts
> +    if (payorder.paymentmethod === 'razorpay') {
refactored done

2021-08-19 09:46 UTC, sumiter92 commented on services/payment-service/src/providers/razorpay/razorpay.provider.ts
> +          return `<html>
yes in one case we are returning, because card number was handled from payment gateway side and we are not storing card information , in frontend request , we are sending 302 temporary redirect to backend for payment and after successful payment , it can be redirected to frontend again with successurl through env and yes by default template is set but can be changed according to requirement and comes from db now

2021-08-19 09:47 UTC, sumiter92 commented on services/payment-service/src/providers/razorpay/razorpay.provider.ts
> +          currency: 'INR',
changed , now its dynamic

2021-08-19 09:47 UTC, sumiter92 commented on services/payment-service/src/providers/razorpay/razorpay.provider.ts
> +          await instance.orders.create(
this instance is of razorpay and create order on razorpay database , our order is created in transactions controller

2021-08-19 09:48 UTC, sumiter92 commented on services/payment-service/src/providers/stripe/stripe.provider.ts
> +          <title>Stripe Payment Demo</title>
refactored

2021-08-19 09:50 UTC, sumiter92 commented on services/payment-service/migrations/sqls/20210722063857-init-up.sql
> +CREATE  TABLE main.orders (
we are adding only payment related fields and storing different gateway response in json format in one column , if we want to add more column according to business needs we can extend these models

2021-08-19 09:50 UTC, sumiter92 commented on services/payment-service/src/controllers/transactions.controller.ts
> +    console.log(this.req.query, 'query');
removed

2021-08-19 10:04 UTC, sumiter92 commented on services/payment-service/src/providers/gateway.provider.ts
> +      if (gatewayType === 'stripe') {
done

2021-08-25 06:50 UTC, akshatdubeysf approved these changes

2021-08-25 06:50 UTC, akshatdubeysf commented on services/payment-service/package.json
> +  "name": "payment-service",
name should be @sourceloop/payment-service

2021-08-25 06:50 UTC, akshatdubeysf commented on services/payment-service/package.json
> +    "@types/uuid": "^8.3.1",
types should be in dev dependencies

2021-08-25 06:50 UTC, akshatdubeysf commented on services/payment-service/package.json
> +  }
add commitizen, husky hooks and commit lint.

2021-08-25 12:05 UTC, akshatdubeysf commented
@sumiter92 also look into the sonar issues.

2021-08-25 14:36 UTC, sumiter92 commented on services/payment-service/package.json
> +    "@types/uuid": "^8.3.1",
done

2021-09-03 08:25 UTC, merged