test(notification-service): added unit testcases
sourcefuse/loopback4-microservice-catalog pull request #264
Opened 2021-07-14 11:17 UTC by ashutosh-bansal-2136

gh-242

## Description

Unit test cases added.

Fixes #242 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-08-10 05:32 UTC, samarpan-b requested changes

2021-08-10 05:32 UTC, samarpan-b commented on services/notification-service/src/__tests__/unit/channel-manager.service.unit.ts
> +    channelManagerProvider = new ChannelManagerProvider();
can we add some default logic of channel manager in our test case

2021-08-10 05:32 UTC, samarpan-b commented on services/notification-service/src/__tests__/unit/notification-user.service.unit.ts
> +    notificationUserProvider = new NotificationUserProvider();
again do we have any default impl for this ?

2021-08-25 11:11 UTC, samarpan-b requested changes

2021-08-25 11:11 UTC, samarpan-b commented on services/notification-service/package.json
> +    "@types/jsonwebtoken": "^8.5.4",
types should be moved to dev deps.

2021-08-25 11:24 UTC, ashutosh-bansal-2136 commented on services/notification-service/src/__tests__/unit/channel-manager.service.unit.ts
> +    channelManagerProvider = new ChannelManagerProvider();
added acceptance test cases for adding mock provider

2021-08-25 11:24 UTC, ashutosh-bansal-2136 commented on services/notification-service/src/__tests__/unit/notification-user.service.unit.ts
> +    notificationUserProvider = new NotificationUserProvider();
added acceptance test cases for adding mock provider

2021-08-25 12:10 UTC, akshatdubeysf approved these changes

2021-08-25 12:10 UTC, akshatdubeysf commented on packages/core/locales/en.json
> +	"host is required": "host is required",
these changes are not needed.

2021-09-03 06:48 UTC, ashutosh-bansal-2136 commented on packages/core/locales/en.json
> +	"host is required": "host is required",
done

2021-09-03 08:13 UTC, merged