docs(schedular-service and video-conferencing-service): update README.md
sourcefuse/loopback4-microservice-catalog pull request #277
Opened 2021-07-22 12:04 UTC by ashutosh-bansal-2136

## Description

Added dbschema, api details, env and migrations in readme.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-07-22 13:58 UTC, samarpan-b requested changes

2021-07-22 13:58 UTC, samarpan-b commented on services/video-conferencing-service/README.md
> +### Environment Variables
Add flow diagram and database schema

2021-07-22 13:58 UTC, samarpan-b commented on services/video-conferencing-service/README.md
> +## APIs available (Currently Vonage is Supported)
move this to a separate docs.md

2021-07-22 13:58 UTC, samarpan-b commented on services/video-conferencing-service/README.md
> +`POST /session/{meetingLinkId}/token`
move these APIs to openapi.md

2021-07-26 11:12 UTC, samarpan-b approved these changes

2021-07-28 16:43 UTC, akshatdubeysf requested changes

2021-07-28 16:43 UTC, akshatdubeysf commented on services/scheduler-service/README.md
Working/Flow for schedular service readme?

2021-07-29 11:05 UTC, ashutosh-bansal-2136 commented on services/scheduler-service/README.md
added

2021-07-29 11:53 UTC, akshatdubeysf approved these changes

2021-08-02 09:29 UTC, merged