feat(sandbox): example of pubnub as a provider in notification service
sourcefuse/loopback4-microservice-catalog pull request #279
Opened 2021-07-23 14:36 UTC by yeshamavani

MIGRATION CHANGE:
migration-20210716062747- notification migration
migration-20210501132806- notification migration

gh-208

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-07-29 08:57 UTC, akshatdubeysf approved these changes

2021-07-29 08:57 UTC, akshatdubeysf commented on packages/core/locales/en.json
> +	"The `users` instance is not valid. Details": " `firstName` can't be blank (value: undefined).",
??

2021-07-29 08:57 UTC, akshatdubeysf commented on sandbox/pubnub-example/src/application.ts
> +    this.sequence(MySequence);
should only use the sequence from notification service.

2021-07-30 06:50 UTC, yeshamavani commented on sandbox/pubnub-example/src/application.ts
> +    this.sequence(MySequence);
Done the required changes

2021-08-10 05:19 UTC, samarpan-b requested changes

2021-08-10 05:19 UTC, samarpan-b commented on sandbox/pubnub-example/src/application.ts
> +      useCustomSequence: true,
why custom sequence true ?

2021-08-10 05:19 UTC, samarpan-b commented on sandbox/pubnub-example/src/application.ts
> +    this.bind(PubnubBindings.Config).to({
can you put some comments as docs here about each config you are providing ? also dont hard code these values.

2021-08-10 05:19 UTC, samarpan-b commented on sandbox/pubnub-example/migrations/sqls/20210716062747-init-up.sql
> +CREATE  TABLE main.notifications (
dont we need channels table ?

2021-08-12 13:32 UTC, yeshamavani commented on sandbox/pubnub-example/src/application.ts
> +      useCustomSequence: true,
that needs to be changed, missed that

2021-08-12 13:33 UTC, yeshamavani commented on sandbox/pubnub-example/migrations/sqls/20210716062747-init-up.sql
> +CREATE  TABLE main.notifications (
no i dont think so we need channel table

2021-08-25 11:13 UTC, samarpan-b commented on README.md
> +[![LoopBack](<https://github.com/strongloop/loopback-next/raw/master/docs/site/imgs/branding/Powered-by-LoopBack-Badge-(blue)-@2x.png>)](http://loopback.io/)
revert this

2021-08-25 11:15 UTC, yeshamavani commented on sandbox/pubnub-example/src/application.ts
> +      useCustomSequence: true,
done

2021-08-25 11:15 UTC, yeshamavani commented on sandbox/pubnub-example/migrations/sqls/20210716062747-init-up.sql
> +CREATE  TABLE main.notifications (
not needed

2021-08-25 14:06 UTC, yeshamavani commented on README.md
> +[![LoopBack](<https://github.com/strongloop/loopback-next/raw/master/docs/site/imgs/branding/Powered-by-LoopBack-Badge-(blue)-@2x.png>)](http://loopback.io/)
these are because of rebasing I haven't added any changes to this

2021-09-02 14:36 UTC, yeshamavani commented on sandbox/pubnub-example/src/application.ts
> +    this.bind(PubnubBindings.Config).to({
added comments  for config

2021-09-02 14:41 UTC, akshatdubeysf approved these changes

2021-09-02 14:42 UTC, merged