fix(authentication-service): added test cases
sourcefuse/loopback4-microservice-catalog pull request #316
Opened 2021-08-27 07:23 UTC by ashutosh-bansal-2136

gh-181

## Description

Added acceptance and unit test cases for authentication service

Fixes #181 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)
- [x] Tests

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-08-31 10:47 UTC, akshatdubeysf commented on services/authentication-service/src/__tests__/acceptance/signup-request.controller.acceptance.ts
> +    process.env.JWT_SECRET = 'test';
why this?

2021-09-01 11:02 UTC, akshatdubeysf requested changes

2021-09-02 10:21 UTC, ashutosh-bansal-2136 commented on services/authentication-service/src/__tests__/acceptance/logout.controller.acceptance.ts
> +  it('Should return 401 and token invalid on requesting with invalid auth token', async () => {
added those cases in login controller

2021-09-02 14:45 UTC, akshatdubeysf commented on services/authentication-service/src/__tests__/acceptance/logout.controller.acceptance.ts
> +  it('Should return 401 and token invalid on requesting with invalid auth token', async () => {
success case for logout scenario where token should be ideally revoked?

2021-09-03 04:22 UTC, ashutosh-bansal-2136 commented on services/authentication-service/src/__tests__/acceptance/logout.controller.acceptance.ts
> +  it('Should return 401 and token invalid on requesting with invalid auth token', async () => {
yes added them in login controller

2021-09-03 07:12 UTC, akshatdubeysf commented on services/authentication-service/src/__tests__/acceptance/logout.controller.acceptance.ts
> +  it('Should return 401 and token invalid on requesting with invalid auth token', async () => {
Why is test for logout controller in login controller acceptance?

2021-09-05 08:41 UTC, ashutosh-bansal-2136 commented on services/authentication-service/src/__tests__/unit/modules-provider/bearer-token-verify.provider.unit.ts
> +      expect(result).to.be.Promise();
Correction done

2021-09-05 08:41 UTC, ashutosh-bansal-2136 commented on services/authentication-service/src/__tests__/unit/google-pre-verify.provider.unit.ts
> +    it('checks if provider returns a function', async () => {
updated tests

2021-09-21 05:11 UTC, akshatdubeysf approved these changes

2021-09-21 07:17 UTC, merged