fix(video-conferencing-service):Added Reusability
sourcefuse/loopback4-microservice-catalog pull request #330
Opened 2021-09-06 09:13 UTC by parul147

## Description

issues: 

- the functions should be reusable rather than in the controller
- business logic if any should be moved to a provider for any change.
- update "crypto-random-string" package or use something else in place of it.

Fixes #307
1) Moved the functions in controller to the services(ChatArchiveService and ChatSessionService).
2) Created Provider for crypto-random-string.
3) Business Logic Moved to Services

## How Has This Been Tested?
-Performed Successful unit testing.

## Checklist:
- [x]  Performed a self-review of my own code
- [x] npm test passes on your machine
- [x] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-09-07 10:02 UTC, SouravSF commented on sandbox/video-conferencing-ms-example/src/application.ts
> +    options.rest.host = 'localhost';
revert this

2021-09-07 10:02 UTC, SouravSF commented on sandbox/video-conferencing-ms-example/src/application.ts
> +      schema: '.env',
revert this

2021-09-07 10:02 UTC, SouravSF commented on sandbox/video-conferencing-ms-example/src/datasources/pg.datasource.ts
> +  host: process.env.HOST,
revert these

2021-09-07 10:03 UTC, SouravSF commented on sandbox/pubnub-example/package.json
> +	"version": "0.0.1",
why did we remove scripts?

2021-09-07 10:03 UTC, SouravSF commented on sandbox/video-conferencing-ms-example/.env.example
> -DB_HOST=
why did we delete env example file?

2021-09-07 10:04 UTC, SouravSF commented on sandbox/pubnub-example/package.json.lerna_backup
> +{
the backup file should not be present

2021-09-07 10:09 UTC, SouravSF commented on sandbox/workflow-ms-example/package-lock.json
>  		},
why have u pushed package locks for stuff that you have not worked on? remove these changes

2021-09-07 10:09 UTC, SouravSF commented on sandbox/workflow-ms-example/package-lock.json
>  		},
multiple files

2021-09-07 10:19 UTC, parul147 commented on sandbox/video-conferencing-ms-example/src/application.ts
> +      schema: '.env',
reverting this

2021-09-07 10:28 UTC, parul147 commented on sandbox/video-conferencing-ms-example/src/datasources/pg.datasource.ts
> +  host: process.env.HOST,
reverting

2021-09-07 10:28 UTC, parul147 commented on sandbox/pubnub-example/package.json
> +	"version": "0.0.1",
I did not touch this file, checking this

2021-09-07 10:31 UTC, parul147 commented on sandbox/video-conferencing-ms-example/.env.example
> -DB_HOST=
got it back, had an complication earlier while testing the service

2021-09-08 03:55 UTC, SouravSF commented on sandbox/video-conferencing-ms-example/.env.example
> -DB_HOST=
I can still see missing vairiabels please add these

2021-09-09 13:58 UTC, yeshamavani reviewed
not needed

2021-09-09 13:58 UTC, yeshamavani commented on services/video-conferencing-service/tsconfig.json
> +   "experimentalDecorators":true,
not needed

2021-09-10 05:45 UTC, parul147 commented on services/video-conferencing-service/tsconfig.json
> +   "experimentalDecorators":true,
removed

2021-09-14 06:26 UTC, yeshamavani approved these changes

2021-09-22 12:56 UTC, parul147 commented on sandbox/pubnub-example/package.json
> +	"version": "0.0.1",
Files re-commited, issue rectified

2021-09-22 12:56 UTC, parul147 commented on sandbox/video-conferencing-ms-example/.env.example
> -DB_HOST=
added the missing variables

2021-09-22 12:57 UTC, parul147 commented on sandbox/pubnub-example/package.json.lerna_backup
> +{
done sir

2021-09-22 12:57 UTC, parul147 commented on sandbox/workflow-ms-example/package-lock.json
>  		},
commited the wrong way, re-commited and rectified the issue

2021-09-22 13:25 UTC, akshatdubeysf requested changes

2021-09-22 13:25 UTC, akshatdubeysf commented on services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-archive.controller.unit.ts
> -    auidtLogCreate = auditLogRepo.stubs.create;
Fix the variable name.

2021-09-22 13:25 UTC, akshatdubeysf commented on services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-session.controller.unit.ts
> +    const generatorProvider = createStubInstance(
These are not needed as you are passing a different generator, not through the provider.

2021-09-22 13:25 UTC, akshatdubeysf commented on services/video-conferencing-service/src/providers/vonage/vonage.provider.ts
>          try {
Remove try catch from here otherwise all the errors would be wrapped in a InternalServerError, even the BadRequest errors.

2021-09-22 13:25 UTC, akshatdubeysf commented on services/video-conferencing-service/src/component.ts
> +    this.bindings.push(
Multiple bindings can be added in one push.

2021-09-22 13:25 UTC, akshatdubeysf commented on services/video-conferencing-service/src/component.ts
> +        MeetingLinkIdGeneratorProvider,
Use the providers property for providers.

2021-09-22 13:25 UTC, akshatdubeysf commented
@parul147 also add the test coverage.

2021-09-23 12:03 UTC, parul147 commented on services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-session.controller.unit.ts
> +    const generatorProvider = createStubInstance(
I have removed the unnecessary  lines.

2021-09-23 12:17 UTC, parul147 commented on services/video-conferencing-service/src/component.ts
> +    this.bindings.push(
Made the required changes. added the bindings in one push.

2021-09-23 13:11 UTC, akshatdubeysf commented on services/video-conferencing-service/src/__tests__/unit/controllers/video-chat-archive.controller.unit.ts
> -    auidtLogCreate = auditLogRepo.stubs.create;
not an issue, my bad.

2021-09-24 11:12 UTC, SouravSF approved these changes

2021-09-24 11:12 UTC, SouravSF commented
@parul147 Please go through the code smells

2021-09-24 13:06 UTC, parul147 commented on services/video-conferencing-service/src/providers/vonage/vonage.provider.ts
>          try {
I have made the necessary changes.

2021-09-24 13:06 UTC, parul147 commented on services/video-conferencing-service/src/component.ts
> +        MeetingLinkIdGeneratorProvider,
done

2021-09-28 07:24 UTC, akshatdubeysf approved these changes

2021-09-28 07:39 UTC, merged