feat(sandbox): chat example
sourcefuse/loopback4-microservice-catalog pull request #333
Opened 2021-09-08 06:05 UTC by sunishka1

auth tables values added

MIGRATION CHANGE:
migration-20210421113036- auth tables setup
migration-20210421113146- auth table values added
migration-20210823080434- auth table roles added
migration-20210823081005- chat tables added
migration-20210823082119- tables moved to public
migration-20210501132806- auth tables setup

BREAKING CHANGE:
auth tables roles added

notification tables added

## Description
- An example has been added which uses chat service and notification service of sourceloop. This is mentioned in Issue No - 331.
- The microservices are working in complete sense. The facade is still in progress.
- Migrations for both services have been built separately for better understanding. 

Fixes #331 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-09-10 06:55 UTC, akshatdubeysf requested changes

2021-09-10 06:55 UTC, akshatdubeysf commented on sandbox/chat-example/facade/chat-notif-facade/src/models/notification-user.dto.ts
> +  @belongsTo(
Why belongs to relation in a DTO?

2021-09-10 06:55 UTC, akshatdubeysf commented on sandbox/chat-example/services/chat-auth-service/README.md
> +# auth-basic-example
name -> chat-auth-service

2021-09-10 06:55 UTC, akshatdubeysf commented on sandbox/chat-example/services/chat-auth-service/package.json
> +  "name": "@sourceloop/auth-ms-basic-example",
name

2021-09-10 06:55 UTC, akshatdubeysf commented on sandbox/chat-example/services/chat-auth-service/package.json
> +  "author": "Akshat Dubey <akshat.dubey@sourcefuse.com>",
??

2021-09-10 06:55 UTC, akshatdubeysf commented on sandbox/chat-example/services/chat-auth-service/.dockerignore
> +node_modules
remove node_modules from all docker ignores

2021-09-10 06:55 UTC, akshatdubeysf commented on sandbox/chat-example/services/chat-auth-service/public/index.html
> +  <title>auth-multitenant-example</title>
name

2021-09-10 06:55 UTC, akshatdubeysf commented on sandbox/chat-example/services/chat-auth-service/src/__tests__/acceptance/home-page.acceptance.ts
> +  let app: AuthMultitenantExampleApplication;
name

2021-09-10 06:55 UTC, akshatdubeysf commented on sandbox/chat-example/services/chat-auth-service/src/__tests__/acceptance/ping.controller.acceptance.ts
> +  let app: AuthMultitenantExampleApplication;
fix all the names in chat-auth-service

2021-09-10 06:55 UTC, akshatdubeysf commented on sandbox/chat-example/services/notification-service/src/datasources/auth-db.datasource.ts
> +  name: AuthDbSourceName,
Why these two again in notification service?

2021-09-10 06:55 UTC, akshatdubeysf commented on sandbox/chat-example/services/notification-service/src/application.ts
> +    this.component(AuthenticationServiceComponent);
Why authentication service bound in multiple microservices?

2021-09-10 06:56 UTC, akshatdubeysf commented
@sunishka1 also make the changes to run through docker compose.

2021-09-14 05:23 UTC, sunishka1 commented on sandbox/chat-example/services/notification-service/src/application.ts
> +    this.component(AuthenticationServiceComponent);
Because both the microservices needed authorization for their controllers.

2021-09-14 08:07 UTC, akshatdubeysf commented on sandbox/chat-example/services/notification-service/src/application.ts
> +    this.component(AuthenticationServiceComponent);
You need to use the authentication/authorization components for that, not he authentication *service* component.

2021-09-20 08:17 UTC, akshatdubeysf requested changes

2021-09-20 08:17 UTC, akshatdubeysf commented on sandbox/chat-example/services/notification-service/src/application.ts
> +    this.bind(NotificationBindings.PushProvider).toProvider(SocketIOProvider);
This should be using the pubnub provider, right?

2021-09-22 12:20 UTC, akshatdubeysf requested changes

2021-09-22 12:20 UTC, akshatdubeysf commented on sandbox/chat-example/facade/chat-notif-facade/src/controllers/index.ts
> +export * from './ping.controller';
No controller in the facade?

2021-09-22 12:22 UTC, sunishka1 commented on sandbox/chat-example/facade/chat-notif-facade/src/controllers/index.ts
> +export * from './ping.controller';
The facade wasn't completed as mentioned earlier.

2021-09-22 12:22 UTC, sunishka1 commented on sandbox/chat-example/services/notification-service/src/application.ts
> +    this.bind(NotificationBindings.PushProvider).toProvider(SocketIOProvider);
Not sure about it. But I was asked to use socket io for this task.

2021-09-22 12:47 UTC, akshatdubeysf commented on sandbox/chat-example/services/notification-service/src/application.ts
> +    this.bind(NotificationBindings.PushProvider).toProvider(SocketIOProvider);
Oh ok.

2021-09-22 12:47 UTC, akshatdubeysf commented on sandbox/chat-example/facade/chat-notif-facade/src/controllers/index.ts
> +export * from './ping.controller';
Added draft label to this PR.

2021-09-28 17:19 UTC, sunishka1 commented on sandbox/chat-example/facade/chat-notif-facade/src/controllers/index.ts
> +export * from './ping.controller';
In the PR heading?

2021-09-29 05:02 UTC, sunishka1 commented on sandbox/chat-example/services/notification-service/src/application.ts
> +    this.component(AuthenticationServiceComponent);
I wanted to try the sourceloop Authentication Service.

2021-09-29 05:03 UTC, sunishka1 commented on sandbox/chat-example/services/notification-service/src/datasources/auth-db.datasource.ts
> +  name: AuthDbSourceName,
Because I used the Authentication service of sourceloop in the example.

2021-12-07 11:14 UTC, akshatdubeysf commented on sandbox/chat-example/services/notification-service/src/datasources/auth-db.datasource.ts
> +  name: AuthDbSourceName,
Is this fixed?

2021-12-07 11:16 UTC, sunishka1 commented on sandbox/chat-example/services/notification-service/src/datasources/auth-db.datasource.ts
> +  name: AuthDbSourceName,
Yes I explained the reason earlier only and you said it was fine

2022-03-22 11:26 UTC, closed without merging