feat(payment-service): add subscription payments
sourcefuse/loopback4-microservice-catalog pull request #360
Opened 2021-10-01 05:27 UTC by sumiter92

## Description

Adds subscription feature in payment service that supports configurable multiple payment gateways.

Fixes #359 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] Code conforms with the style guide

2021-10-13 11:10 UTC, samarpan-b requested changes

2021-10-13 11:10 UTC, samarpan-b commented on services/payment-service/src/controllers/transactions.controller.ts
> +  @get(`/transactions/subscriptionid/{id}`)
incorrect REST format for url.

2021-10-20 15:46 UTC, akshatdubeysf commented on services/payment-service/src/controllers/transactions-subscriptions.controller.ts
> +    const templates = await this.templatesRepository.find({
Why not use findOne?

2021-10-20 15:51 UTC, akshatdubeysf commented on services/payment-service/src/controllers/transactions-subscriptions.controller.ts
> +      await this.gatewayHelper.subscriptionCreate(
incase paymentTemplate is undefined?

2021-12-31 11:54 UTC, akshatdubeysf commented on services/payment-service/src/controllers/subscriptions.controller.ts
> +  @get('/subscriptions/count')
authorization and authentication?

2022-01-07 10:58 UTC, sumiter92 commented on services/payment-service/src/controllers/subscriptions.controller.ts
> +  @get('/subscriptions/count')
added

2022-01-15 10:00 UTC, merged