feat(hidden-api): adds hidden-api feature (#143)
sourcefuse/loopback4-microservice-catalog pull request #364
Opened 2021-10-05 20:11 UTC by Jyoti-13

## Description
A way to hide some of the APIs of a microservice if not needed #143

Please delete options that are not relevant.
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:
- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] API Documentation in code was updated

2021-10-20 15:30 UTC, samarpan-b approved these changes

2021-10-20 15:31 UTC, samarpan-b commented on enhancer/operation-spec-enhancer.ts
> +import {apiHide} from './utility';
add to sourceloop core please

2021-10-20 19:42 UTC, akshatdubeysf requested changes

2021-10-20 19:42 UTC, akshatdubeysf commented on README.md
> +    this.add(createBindingFromClass(OperationSpecEnhancer));
Add this to the individual services so user only has to bind the config values, not this.

2021-11-10 12:00 UTC, Jyoti-13 commented on enhancer/operation-spec-enhancer.ts
> +import {apiHide} from './utility';
Done.

2021-11-10 12:00 UTC, Jyoti-13 commented on README.md
> +    this.add(createBindingFromClass(OperationSpecEnhancer));
Done.

2021-11-10 12:00 UTC, Jyoti-13 commented on packages/core/src/component.ts
> +import { OperationSpecEnhancer } from './enhancer/operation-spec-enhancer';
Done.

2021-11-10 12:00 UTC, Jyoti-13 commented on services/audit-service/src/keys.ts
> +
Done.

2021-11-10 12:01 UTC, Jyoti-13 commented on packages/core/src/keys.ts
> +
Done.

2021-11-10 12:01 UTC, Jyoti-13 commented on packages/core/src/keys.ts
> +  httpMethod: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
Done.

2021-11-10 12:01 UTC, Jyoti-13 commented on packages/core/src/enhancer/utility.ts
> +  if (path['get'] && apiSearch[1]['httpMethod'] === 'GET') {
Done.

2021-11-10 12:01 UTC, Jyoti-13 commented on packages/core/src/enhancer/utility.ts
> +}
Done.

2021-11-10 12:01 UTC, Jyoti-13 commented on packages/core/src/enhancer/utility.ts
> +import {HttpMethod, OasKeyMap} from '../enums/http-oas.enum';
Done.

2021-11-10 12:02 UTC, Jyoti-13 commented on packages/core/src/enums/http-oas.enum.ts
> +export enum HttpMethod {
Done.

2021-11-10 12:03 UTC, akshatdubeysf approved these changes

2021-11-10 12:04 UTC, merged