refactor(core): prepublish for user onboarding
sourcefuse/loopback4-microservice-catalog pull request #379
Opened 2021-10-12 09:57 UTC by yeshamavani

gh-00

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-10-20 15:41 UTC, akshatdubeysf requested changes

2021-10-20 15:41 UTC, akshatdubeysf commented on packages/core/package.json
> +    "registry": "http://localhost:4873/",
Registry should not be localhost?

2021-10-20 15:41 UTC, akshatdubeysf commented on sandbox/audit-ms-example/CHANGELOG.md
> +## <small>0.2.7 (2021-10-13)</small>
Why is audit-ms-example effected?

2021-10-20 15:41 UTC, akshatdubeysf commented on sandbox/audit-ms-example/package.json
> +  "version": "0.2.7",
??

2021-10-21 09:49 UTC, closed without merging

2021-10-21 09:50 UTC, yeshamavani commented
raised another Pr and merged the same.