feat(sandbox): example for feature toggle service
sourcefuse/loopback4-microservice-catalog pull request #398
Opened 2021-10-29 10:28 UTC by yeshamavani

MIGRATION CHANGE:
migration-20211019091305- example for feature toggle service
migration-20210913104858- example for feature toggle service

gh-396

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #396

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-03 05:25 UTC, akshatdubeysf requested changes

2021-11-03 05:25 UTC, akshatdubeysf commented on sandbox/feature-toggle-example/src/application.ts
> +        Authorization:
This should be from environment

2021-11-03 05:25 UTC, akshatdubeysf commented on sandbox/feature-toggle-example/src/application.ts
> +      url: 'http://localhost:4242/api/',
Pick from environment

2021-11-03 05:25 UTC, akshatdubeysf commented on sandbox/feature-toggle-example/src/application.ts
> +    unleash.initialize({
Why not take just the config from user and create unleash instance in the component?

2021-11-08 08:07 UTC, yeshamavani commented on sandbox/feature-toggle-example/src/application.ts
> +        Authorization:
done

2021-11-08 08:07 UTC, yeshamavani commented on sandbox/feature-toggle-example/src/application.ts
> +      url: 'http://localhost:4242/api/',
done

2021-12-06 06:59 UTC, akshatdubeysf reviewed
Why package-locks changed for inmail and video-conf services?

2021-12-06 07:00 UTC, akshatdubeysf commented
@yeshamavani fix sonar and audit

2021-12-06 08:09 UTC, yeshamavani commented
those were may be rebase changes @akshatdubeysf

2021-12-07 10:02 UTC, yeshamavani commented on sandbox/feature-toggle-example/src/application.ts
> +    unleash.initialize({
not needed

2021-12-10 11:36 UTC, merged