fix(search-client): reduce gap between input box and recent searches
sourcefuse/loopback4-microservice-catalog pull request #400
Opened 2021-11-01 10:18 UTC by barleendhaliwal

reduce gap between input box and recent searches if no result found & do not open drop down in case no recent searches

## Description

Reduce gap between input box and recent searches if no result found & do not open drop down in case no recent searches

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-01 14:24 UTC, akshatdubeysf requested changes

2021-11-01 14:24 UTC, akshatdubeysf commented on packages/search/projects/search-lib/src/lib/search/search.component.html
> +  <div *ngIf="suggestionsDisplay && recentSearches.length" class="search-popup">
suggestions would not be visible if there are no recentSearches?

2021-11-02 06:26 UTC, barleendhaliwal commented on packages/search/projects/search-lib/src/lib/search/search.component.html
> +  <div *ngIf="suggestionsDisplay && recentSearches.length" class="search-popup">
fixed

2021-11-02 11:34 UTC, akshatdubeysf commented on packages/search/projects/search-lib/src/lib/search/search.component.ts
> +    this.config.models.every(item => {
use find ?

2021-11-02 11:34 UTC, akshatdubeysf commented on packages/search/projects/search-lib/src/lib/search/search.component.ts
> +        modelsWithSuggestions.every(modelWithSuggestions => {
Why use every instead of forEach?

2021-11-02 13:23 UTC, barleendhaliwal commented on packages/search/projects/search-lib/src/lib/search/search.component.ts
> +        modelsWithSuggestions.every(modelWithSuggestions => {
every allows me to break from loop and unnecessary iteration can be avoided

2021-11-02 14:02 UTC, barleendhaliwal commented on packages/search/projects/search-lib/src/lib/search/search.component.ts
> +    this.config.models.every(item => {
fixed

2021-11-03 05:13 UTC, akshatdubeysf commented on packages/search/projects/search-lib/src/lib/search/search.component.ts
> +        modelsWithSuggestions.every(modelWithSuggestions => {
ok

2021-11-03 05:13 UTC, akshatdubeysf approved these changes

2021-11-03 06:38 UTC, merged