feat(sandbox): example of payment-service
sourcefuse/loopback4-microservice-catalog pull request #402
Opened 2021-11-03 09:50 UTC by sumiter92

## Description

Adds example of payment-service to run as a service

Fixes #401 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] Code conforms with the style guide

2021-11-10 07:44 UTC, akshatdubeysf requested changes

2021-11-10 07:44 UTC, akshatdubeysf commented on sandbox/docker-compose.yml
> +  payment-backend-example:
migrations?

2021-11-10 07:44 UTC, akshatdubeysf commented on sandbox/payment-example/backend/package.json
> +  "name": "payment-example-backend",
@sourceloop/payment-example-backend

2021-11-10 07:44 UTC, akshatdubeysf commented on sandbox/payment-example/backend/src/application.ts
> +} from '@sourceloop/payment-service/dist/providers';
Export these from the index.ts of the service so the import from dist is not required

2021-11-10 07:44 UTC, akshatdubeysf commented on sandbox/payment-example/backend/src/application.ts
> +    this.bind(StripeBindings.StripeHelper).toProvider(StripeProvider);
These should be bound by default in the component?

2021-12-31 11:51 UTC, akshatdubeysf requested changes

2021-12-31 11:51 UTC, akshatdubeysf commented on sandbox/payment-example/backend/package.json
> +  "description": "backend",
??

2022-01-12 10:57 UTC, sumiter92 commented on sandbox/payment-example/backend/package.json
> +  "description": "backend",
done, changed

2022-01-12 10:57 UTC, sumiter92 commented on sandbox/payment-example/backend/package.json
> +  "name": "payment-example-backend",
done, changed

2022-01-19 09:05 UTC, sumiter92 commented on sandbox/docker-compose.yml
> +  payment-backend-example:
added

2022-01-19 09:05 UTC, sumiter92 commented on sandbox/payment-example/backend/src/application.ts
> +} from '@sourceloop/payment-service/dist/providers';
done in service and modified here too

2022-01-19 09:06 UTC, sumiter92 commented on sandbox/payment-example/backend/src/application.ts
> +    this.bind(StripeBindings.StripeHelper).toProvider(StripeProvider);
done

2022-01-21 05:28 UTC, merged