feat(sandbox): added UI to chat example
sourcefuse/loopback4-microservice-catalog pull request #420
Opened 2021-11-10 18:02 UTC by AnkurBansalSF

added UI to chat-notification example

gh-345

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2021-11-12 09:09 UTC, akshatdubeysf requested changes

2021-11-12 09:09 UTC, akshatdubeysf commented on sandbox/chat-notification-pubnub-example/frontend/angular.json
> +    "demo": {
Change project name here as well

2021-11-12 09:09 UTC, akshatdubeysf commented on sandbox/chat-notification-pubnub-example/frontend/angular.json
> +  "defaultProject": "demo"
project name

2021-11-12 09:09 UTC, akshatdubeysf commented on sandbox/chat-notification-pubnub-example/frontend/src/app/app.component.ts
> +      channels: [environment.USER1_UUID, environment.USER2_UUID],
Should'nt this be based on the User?

2021-11-12 09:09 UTC, akshatdubeysf commented on sandbox/chat-notification-pubnub-example/frontend/src/app/chat/chat.component.ts
> +      if (this.senderUUID === this.uuid1) {
???

2021-11-12 09:09 UTC, akshatdubeysf commented on sandbox/chat-notification-pubnub-example/frontend/src/app/chat/chat.component.ts
> +      data.sort((a, b) => {
Why not use the order filter in the API?

2021-11-12 09:19 UTC, AnkurBansalSF commented on sandbox/chat-notification-pubnub-example/frontend/src/app/chat/chat.component.ts
> +      if (this.senderUUID === this.uuid1) {
Did this so that I don't have to manually enter ID of second user.

2021-11-16 08:31 UTC, AnkurBansalSF commented on sandbox/chat-notification-pubnub-example/frontend/angular.json
> +    "demo": {
done

2021-11-16 08:31 UTC, AnkurBansalSF commented on sandbox/chat-notification-pubnub-example/frontend/angular.json
> +  "defaultProject": "demo"
done

2021-11-16 08:31 UTC, AnkurBansalSF commented on sandbox/chat-notification-pubnub-example/frontend/src/app/app.component.ts
> +      channels: [environment.USER1_UUID, environment.USER2_UUID],
fixed

2021-11-16 08:31 UTC, AnkurBansalSF commented on sandbox/chat-notification-pubnub-example/frontend/src/app/chat/chat.component.ts
> +      data.sort((a, b) => {
done

2021-11-29 14:32 UTC, yeshamavani approved these changes

2021-12-06 07:01 UTC, akshatdubeysf commented
@AnkurBansalSF fix sonar issue

2021-12-06 12:23 UTC, akshatdubeysf approved these changes

2021-12-31 11:33 UTC, akshatdubeysf requested changes

2021-12-31 11:33 UTC, akshatdubeysf commented on sandbox/chat-notification-pubnub-example/frontend/src/app/chat/chat.component.ts
> +  styles: [
better to keep styles in a file

2021-12-31 11:33 UTC, akshatdubeysf commented on sandbox/chat-notification-pubnub-example/frontend/src/environments/environment.prod.ts
> +  production: true
should atleast have the same variables as environment.ts, with maybe some placeholder values.

2021-12-31 11:33 UTC, akshatdubeysf commented on sandbox/chat-notification-pubnub-example/frontend/package.json
> +  "name": "@sourceloop/chat-notif-example_ui",
description, license

2022-01-10 11:05 UTC, merged