microservice-catalog sandbox latest version
sourcefuse/loopback4-microservice-catalog pull request #452
Opened 2022-01-05 16:05 UTC by Jyoti-13

## Description

Updated sandox examples to the latest version.

2022-01-10 05:23 UTC, akshatdubeysf commented
@Jyoti-13 fix PR title and description

2022-01-12 07:25 UTC, akshatdubeysf approved these changes

2022-01-12 18:05 UTC, samarpan-b requested changes
revert all package locks of services

2022-01-12 18:05 UTC, samarpan-b commented on packages/core/package-lock.json
> +  "lockfileVersion": 1,
revert this

2022-01-13 08:07 UTC, Jyoti-13 commented on packages/core/package-lock.json
> +  "lockfileVersion": 1,
Reverted.

2022-01-13 16:46 UTC, samarpan-b commented
Please update dockerfile as well @Jyoti-13

2022-01-17 06:35 UTC, Jyoti-13 commented
> Please update dockerfile as well @Jyoti-13

Done.

2022-01-28 08:06 UTC, samarpan-b requested changes

2022-01-28 08:06 UTC, samarpan-b commented on sandbox/audit-ms-example/Dockerfile
> +FROM node:16-slim
use node:16-alpine

2022-01-31 06:15 UTC, Jyoti-13 commented on sandbox/audit-ms-example/Dockerfile
> +FROM node:16-slim
updated

2022-01-31 11:47 UTC, merged