Fixes in Feature-toggle-service
sourcefuse/loopback4-microservice-catalog pull request #458
Opened 2022-01-12 08:36 UTC by AnkurBansalSF

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-12 15:34 UTC, akshatdubeysf approved these changes

2022-01-12 15:34 UTC, akshatdubeysf commented on services/feature-toggle-service/src/component2.ts
> +import {
use a better name for the file.

2022-01-12 18:04 UTC, samarpan-b requested changes

2022-01-12 18:04 UTC, samarpan-b commented on services/feature-toggle-service/src/component2.ts
> +export class FeatureToggleComponent implements Component {
file name incorrect

2022-01-12 18:04 UTC, samarpan-b commented on services/feature-toggle-service/src/component2.ts
> +    this.application.component(CoreComponent);
why repeating everything ? I dont understand this at all

2022-01-15 09:16 UTC, samarpan-b approved these changes

2022-01-15 09:16 UTC, merged