fix(authentication-service): change response of signup and forget password
sourcefuse/loopback4-microservice-catalog pull request #459
Opened 2022-01-12 09:13 UTC by akshatdubeysf

BREAKING CHANGE:
removed response body and changed response code of signup-token and forget-password apis

## Description

change response of signup and forget password, add validation for internal user during forget and reset password

Fixes #457 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [X] Performed a self-review of my own code
- [X] npm test passes on your machine
- [X] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-12 09:23 UTC, samarpanB requested changes

2022-01-12 09:23 UTC, samarpanB commented on packages/core/src/enums/auth-provider.enum.ts
> +  KEYCLOAK = 'keycloak',
add other providers too

2022-01-12 09:23 UTC, samarpanB commented on services/authentication-service/.env.defaults
> +DB_HOST=
remove these

2022-01-12 09:23 UTC, samarpanB commented on services/authentication-service/src/controllers/signup-request.controller.ts
> +    await handler(token, expiryDuration, signUpRequest.email);
send it as DTO only, so that it can be managed easily in future

2022-01-12 09:23 UTC, samarpanB commented on services/authentication-service/src/controllers/forget-password.controller.ts
> +    await forgetPasswordHandler(token, expiryDuration, user.email, user);
use the same DTO object

2022-01-12 09:56 UTC, akshatdubeysf commented on services/authentication-service/.env.defaults
> +DB_HOST=
But the build fails as they are added in the env schema

2022-01-12 10:22 UTC, akshatdubeysf commented on packages/core/src/enums/auth-provider.enum.ts
> +  KEYCLOAK = 'keycloak',
done

2022-01-12 21:03 UTC, samarpan-b requested changes

2022-01-12 21:03 UTC, samarpan-b commented on services/authentication-service/src/controllers/forget-password.controller.ts
> +      user: user,
why do we need user model here ? we should not send that.

2022-01-13 05:55 UTC, sf-kansara approved these changes

2022-01-13 06:37 UTC, akshatdubeysf commented on services/authentication-service/src/controllers/forget-password.controller.ts
> +      user: user,
It was part of the ForgetPasswordDto, can be removed if not required.

2022-01-13 07:05 UTC, akshatdubeysf commented on services/authentication-service/src/controllers/forget-password.controller.ts
> +      user: user,
done

2022-01-13 16:41 UTC, samarpan-b approved these changes

2022-01-13 16:43 UTC, merged