fix(user-onboarding): add properties to tourState, save state initially, add tourComplete observable
sourcefuse/loopback4-microservice-catalog pull request #462
Opened 2022-01-14 08:27 UTC by barleendhaliwal

## Description
added status and prop to tourState model, fix state not getting saved in case undefined, add tourComplete observable that can be subscribed to, add setSessionIdGenerator function in tourStoreService

Fixes # gh-0

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-15 09:21 UTC, samarpan-b requested changes

2022-01-15 09:21 UTC, samarpan-b commented on packages/user-onboarding/projects/user-onboarding-lib/src/models/index.ts
> +export * from './Props';
follow file naming convention. File names cant start with caps

2022-01-15 09:21 UTC, samarpan-b commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-store-service.service.ts
> +  private sessionGenerator: () => string = () => {
cant we use any existing uuid library ?

2022-01-15 10:19 UTC, barleendhaliwal commented on packages/user-onboarding/projects/user-onboarding-lib/src/models/index.ts
> +export * from './Props';
fixed naming convention for all files in models

2022-01-15 10:19 UTC, barleendhaliwal commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-store-service.service.ts
> +  private sessionGenerator: () => string = () => {
fixed

2022-01-15 10:56 UTC, akshatdubeysf approved these changes

2022-01-15 10:56 UTC, akshatdubeysf commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-service.service.ts
> +              this.tourStoreService
Can make this a function, and use that everywhere

2022-01-15 10:56 UTC, akshatdubeysf commented on packages/user-onboarding/projects/user-onboarding-lib/src/lib/tour-service.service.ts
> +            (event: {index: number; tour: Shepherd.Tour; tourId: string}) => {
Create a type for this instance.

2022-01-16 17:13 UTC, samarpan-b reviewed
File names are still incorrect @barleendhaliwal . They should be kebab case. I am merging it for now. Please fix the pending comments in a new PR separately.

2022-01-16 17:14 UTC, merged

2022-01-16 17:15 UTC, samarpan-b commented
Also fix sonar in next PR. @barleendhaliwal