feat(core): add component to authenticate swagger ui access
sourcefuse/loopback4-microservice-catalog pull request #467
Opened 2022-01-17 05:29 UTC by akshatdubeysf

## Description

add component to authenticate swagger ui access

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [X] Performed a self-review of my own code
- [X] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the style guide
- [X] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-01-17 12:37 UTC, samarpan-b requested changes

2022-01-17 12:37 UTC, samarpan-b commented on packages/core/src/components/swagger-authentication/component.ts
> +export class SwaggerAuthenticationComponent implements Component {
add to sourceloop core by default and a config for switching it on and off

2022-01-18 05:30 UTC, akshatdubeysf commented on packages/core/src/components/swagger-authentication/component.ts
> +export class SwaggerAuthenticationComponent implements Component {
done

2022-01-28 08:02 UTC, samarpan-b approved these changes

2022-01-28 08:02 UTC, merged