feat(video-conferencing-service): add twilio support, replaced crypto-random-string with nanoid
sourcefuse/loopback4-microservice-catalog pull request #492
Opened 2022-01-25 10:15 UTC by rohitvishwakarma-sf

gh-447

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-02-07 06:43 UTC, akshatdubeysf requested changes

2022-02-07 06:43 UTC, akshatdubeysf commented on services/video-conferencing-service/openapi.md
> +fetch('/session/token',
Token should still be on linkId

2022-02-07 06:43 UTC, akshatdubeysf commented on services/video-conferencing-service/src/__tests__/helpers.ts
> +      mediaMode: VideoChatEnums.MediaMode.Routed,
This should be VonageEnum as I don't think these options are available in twilio

2022-02-07 06:43 UTC, akshatdubeysf commented on services/video-conferencing-service/src/controllers/video-chat-session.controller.ts
> -    @param.path.string('meetingLinkId') meetingLinkId: string,
Why removed this?

2022-02-07 06:43 UTC, akshatdubeysf commented on services/video-conferencing-service/src/providers/twilio/twilio.service.ts
> +  twilioBaseUrl = 'https://video.twilio.com';
should be from config

2022-02-07 06:43 UTC, akshatdubeysf commented on services/video-conferencing-service/src/providers/twilio/twilio.service.ts
> +    return Promise.resolve();
this would return before the delete happens

2022-02-07 06:43 UTC, akshatdubeysf commented on services/video-conferencing-service/src/providers/twilio/twilio.service.ts
> +    return Promise.resolve({
make it async and use simple return?

2022-02-07 06:43 UTC, akshatdubeysf commented
@rohitvishwakarma-sf reflect breaking changes in the PR ddescription

2022-02-09 05:12 UTC, rohitvishwakarma-sf commented on services/video-conferencing-service/src/__tests__/helpers.ts
> +      mediaMode: VideoChatEnums.MediaMode.Routed,
done

2022-02-09 05:13 UTC, rohitvishwakarma-sf commented on services/video-conferencing-service/src/providers/twilio/twilio.service.ts
> +  twilioBaseUrl = 'https://video.twilio.com';
done

2022-02-09 09:29 UTC, rohitvishwakarma-sf commented on services/video-conferencing-service/src/controllers/video-chat-session.controller.ts
> -    @param.path.string('meetingLinkId') meetingLinkId: string,
restored

2022-02-12 14:06 UTC, merged