fix(authentication-service): fix keycloak logout after token refresh
sourcefuse/loopback4-microservice-catalog pull request #597
Opened 2022-03-10 09:04 UTC by akshatdubeysf

## Description

 fix keycloak logout after token refresh

Fixes #596

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [X] Performed a self-review of my own code
- [X] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [X] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-10 09:39 UTC, samarpanB requested changes

2022-03-10 09:39 UTC, samarpanB commented on services/authentication-service/src/modules/auth/login.controller.ts
> +import {ExternalTokens} from '../..';
this sometimes fail. make it '../types'

2022-03-10 09:39 UTC, samarpanB commented on services/authentication-service/src/types.ts
> +  externalAuthToken: string;
make these optional

2022-03-10 10:14 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +import {ExternalTokens} from '../..';
fixed

2022-03-10 10:14 UTC, akshatdubeysf commented on services/authentication-service/src/types.ts
> +  externalAuthToken: string;
fixed

2022-03-13 06:06 UTC, samarpanB approved these changes

2022-03-13 06:06 UTC, merged