docs(README): updating readme file for services
sourcefuse/loopback4-microservice-catalog pull request #613
Opened 2022-03-19 08:11 UTC by parul147

## Description
 updating readme file for services

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-22 07:52 UTC, akshatdubeysf commented on packages/cli/README.md
> +- First Step is to install SourceLoop CLI globally in your system using the below command.
These changes are not required for now, these would get updated automatically by clu

2022-03-22 07:52 UTC, akshatdubeysf commented on packages/cli/README.md
> +- First Step is to install SourceLoop CLI globally in your system using the below command.
only for the the usage and getting started section

2022-03-22 11:22 UTC, samarpan-b requested changes
We need some illustrations or diagrams for each service as well

2022-03-22 11:22 UTC, samarpan-b commented on README.md
> +## Sourceloop CLI
add a link and mention for it on top

2022-03-22 11:22 UTC, samarpan-b commented on packages/cli/README.md
> +- Generating services and facades folder to host microservice.
make sure these are same as confluence page

2022-03-24 06:12 UTC, parul147 commented on README.md
> +## Sourceloop CLI
okay

2022-03-24 06:13 UTC, parul147 commented on packages/cli/README.md
> +- Generating services and facades folder to host microservice.
yes, I double checked my references from the confluence page.

2022-04-21 06:37 UTC, akshatdubeysf approved these changes

2022-05-10 06:03 UTC, merged