feat(in-mail-service): Implementation of In-mail service
sourcefuse/loopback4-microservice-catalog pull request #68
Opened 2020-08-28 07:03 UTC by bhavyasf

SFO-141

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2020-08-31 08:45 UTC, samarpan-b commented
@bhavyasf please rebas eit. Also test cases are failing. please check

2020-08-31 08:57 UTC, samarpan-b requested changes

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/README.md
> +```sql
why this ? Put migration in a separate folder as executable scripts like we do elsewhere

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/migrations/database.json
> +{
use latest lb4 cli. in that this file wont be needed

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/src/controllers/collector.controller.ts
> +  @authorize(['*'])
why * ?

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/src/controllers/collector.controller.ts
> +              properties: {
why properties like this ? use LB4 decorators

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/src/controllers/collector.controller.ts
> +    @param.path.string('version') version: string,
use Filter provided by LB4

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/src/controllers/collector.controller.ts
> +    @param.path.number('limit') limit: number,
Please do LB4 way.

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/src/controllers/collector.controller.ts
> +    @param.path.string('messageId') messageId: string,
All the GET APIs have incorrect signatures. Please make them similar to LB4 standards

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/src/controllers/originator.controller.ts
> +    @requestBody({
same comment as in other controller

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/src/helpers/repository.helper.ts
> +export const repositoryHelper = {
no need of this. use services for business logic if needed

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/src/models/group.model.ts
> +export enum VisibilityMarker {
keep enums in separate files

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/src/repositories/attachment.repository.ts
> +export class AttachmentRepository extends DefaultCrudRepository<
extend from usermodifyrepo

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/src/repositories/attachment.repository.ts
> +    const currentUser = await this.getCurrentUser();
not needed. use different base class

2020-08-31 08:57 UTC, samarpan-b commented on services/in-mail-service/src/repositories/message.repository.ts
> +    repositoryHelper.addFalseDeletedConditionInInclude(filter);
I dont understand this at all. Why is it done like this ?

2020-08-31 09:03 UTC, bhavyasf commented on services/in-mail-service/src/helpers/repository.helper.ts
> +export const repositoryHelper = {
Ok. Basically the purpose of this helper was to fetch only data in default where `deleted = false`

2020-08-31 09:04 UTC, bhavyasf commented on services/in-mail-service/src/models/group.model.ts
> +export enum VisibilityMarker {
ok!

2020-08-31 09:06 UTC, bhavyasf commented on services/in-mail-service/src/repositories/message.repository.ts
> +    repositoryHelper.addFalseDeletedConditionInInclude(filter);
Only used to fetch data in which `deleted = false` and for GET APIs  removing the deleted attribute

2020-08-31 09:06 UTC, bhavyasf commented on services/in-mail-service/src/repositories/attachment.repository.ts
> +export class AttachmentRepository extends DefaultCrudRepository<
Ok!

2020-08-31 09:07 UTC, samarpan-b commented on services/in-mail-service/src/repositories/message.repository.ts
> +    repositoryHelper.addFalseDeletedConditionInInclude(filter);
There is a base repo for that already. No custom work needed.

2020-08-31 09:24 UTC, bhavyasf commented on services/in-mail-service/README.md
> +```sql
Already added. I think I just need to be removed

2020-08-31 10:10 UTC, bhavyasf commented on services/in-mail-service/src/controllers/collector.controller.ts
> +    @param.path.string('version') version: string,
version comes from the API request parameter that's why I used params.path

2020-08-31 10:12 UTC, bhavyasf commented on services/in-mail-service/migrations/database.json
> +{
that's used for migrations using `db-migrate`

2020-08-31 10:20 UTC, bhavyasf commented on services/in-mail-service/src/repositories/attachment.repository.ts
> +    const currentUser = await this.getCurrentUser();
can you tell me which one to use?

2020-08-31 10:46 UTC, samarpan-b commented on services/in-mail-service/src/repositories/attachment.repository.ts
> +    const currentUser = await this.getCurrentUser();
check repositories in auth micro service

2020-08-31 13:30 UTC, bhavyasf commented on services/in-mail-service/src/index.ts
> +   ComposeMailBody,
Will be using in vmsl for type

2020-09-13 11:14 UTC, bhavyasf commented on services/in-mail-service/src/controllers/collector.controller.ts
> +              properties: {
item used as getModelSchemaRef.

2020-09-13 12:24 UTC, bhavyasf commented on services/in-mail-service/src/controllers/collector.controller.ts
> +    @param.path.string('version') version: string,
others used as filter.

2020-09-16 07:23 UTC, samarpan-b commented
rebase please @bhavyasf

2020-09-16 09:22 UTC, samarpan-b requested changes

2020-09-16 09:22 UTC, samarpan-b commented on services/in-mail-service/src/controllers/collector.controller.ts
> +    const threadFilter: Filter<Thread> = {
is it working ?

2020-09-16 09:22 UTC, samarpan-b commented on services/in-mail-service/src/controllers/collector.controller.ts
> +      version,
whats the purpose of version ? It seems to be unused.

2020-09-16 09:22 UTC, samarpan-b commented on services/in-mail-service/src/models/id-array.model.ts
> +export class IdArrays extends Entity {
@model missing

2020-09-16 09:22 UTC, samarpan-b commented on services/in-mail-service/src/models/id-response.model.ts
> +export class IdResponse extends Entity {
@model missing

2020-09-16 09:45 UTC, bhavyasf commented on services/in-mail-service/src/controllers/collector.controller.ts
> +      version,
API version as discussed with @hitesh-sourcefuse

2020-09-16 09:47 UTC, bhavyasf commented on services/in-mail-service/src/controllers/collector.controller.ts
> +    const threadFilter: Filter<Thread> = {
yes. tested locally

2020-09-16 09:47 UTC, bhavyasf commented on services/in-mail-service/src/models/id-array.model.ts
> +export class IdArrays extends Entity {
ok

2020-09-16 09:48 UTC, bhavyasf commented on services/in-mail-service/src/models/id-response.model.ts
> +export class IdResponse extends Entity {
ok

2020-09-16 10:35 UTC, samarpan-b commented
can u check why CI check is failing ?

2020-09-16 10:49 UTC, samarpan-b requested changes

2020-09-16 10:49 UTC, samarpan-b commented on services/in-mail-service/src/models/id-response.model.ts
> +export class IdResponse extends Entity {
is there a table name like this ? if yes, then its incorrect format.

2020-09-16 13:30 UTC, merged