feat(authentication-service): implement 2-factor-authentication
sourcefuse/loopback4-microservice-catalog pull request #686
Opened 2022-04-18 09:24 UTC by AnkurBansalSF

## Description

implemented otp strategy using loopback4-authentication package

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-20 07:35 UTC, akshatdubeysf commented
@AnkurBansalSF mention issue number in PR

2022-04-20 07:39 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      this.logger.error(error);
Throw error from sendOtp service instead catching and throwing again?

2022-04-20 07:39 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +  ): Promise<{
create a type?

2022-04-20 07:39 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    req: {
Create a model

2022-04-20 07:39 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/providers/otp-verify.provider.ts
> +        throw new HttpErrors.Unauthorized(AuthErrorKeys.InvalidCredentials);
log here instead of in controller

2022-04-20 07:39 UTC, akshatdubeysf commented on services/authentication-service/src/providers/otp-generate.provider.ts
> +const crypto = require('crypto');
why require instead of import?

2022-04-22 12:38 UTC, AnkurBansalSF commented on services/authentication-service/src/providers/otp-generate.provider.ts
> +const crypto = require('crypto');
done

2022-04-22 12:50 UTC, akshatdubeysf requested changes

2022-04-22 12:50 UTC, akshatdubeysf commented on services/authentication-service/src/component.ts
>      this.application
just use this.services?

2022-04-22 12:50 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      key: key,
```
{
  key,
}
```

2022-04-22 12:50 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      code: this.createCode(otpCache),
have a provider in between similar to other code endpoints, so user can use caching/encryption if required

2022-04-22 12:50 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/providers/otp-verify.provider.ts
> +        throw new HttpErrors.Unauthorized(AuthErrorKeys.InvalidCredentials);
Create and throw a new error saying invalid Key?

2022-04-22 12:50 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/providers/otp-verify.provider.ts
> +        throw new HttpErrors.Unauthorized('Invalid OTP');
Create and use AuthErrorKeys

2022-04-22 12:50 UTC, akshatdubeysf commented on services/authentication-service/src/providers/google-authenticator-verify.provider.ts
> +        throw new HttpErrors.Unauthorized('Invalid Key');
AuthErrorKeys?

2022-04-22 12:50 UTC, akshatdubeysf commented on services/authentication-service/src/providers/google-authenticator-verify.provider.ts
> +        throw new HttpErrors.Unauthorized('Invalid OTP');
AuthErrorKeys?

2022-04-22 13:39 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      this.logger.error(error);
done

2022-04-22 13:39 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/login.controller.ts
> +  ): Promise<{
done

2022-04-22 13:39 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    req: {
done

2022-04-22 13:39 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/providers/otp-verify.provider.ts
> +        throw new HttpErrors.Unauthorized(AuthErrorKeys.InvalidCredentials);
done

2022-04-22 13:40 UTC, AnkurBansalSF commented on services/authentication-service/src/component.ts
>      this.application
not working

2022-04-22 13:41 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      key: key,
not working

2022-04-22 13:41 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      code: this.createCode(otpCache),
done

2022-04-22 13:42 UTC, AnkurBansalSF commented on services/authentication-service/src/providers/google-authenticator-verify.provider.ts
> +        throw new HttpErrors.Unauthorized('Invalid Key');
done

2022-04-22 13:42 UTC, AnkurBansalSF commented on services/authentication-service/src/providers/google-authenticator-verify.provider.ts
> +        throw new HttpErrors.Unauthorized('Invalid OTP');
done

2022-04-25 09:41 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/login.controller.ts
> +      key: key,
done

2022-05-09 06:15 UTC, akshatdubeysf requested changes

2022-05-09 06:15 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    otp: process.env.OTP_SENDER_FUNCTION,
remove this if not in use

2022-05-09 06:15 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    const token = jwt.sign(codePayload, otpCache.clientSecret, {
use code writer here

2022-05-09 06:15 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    return this.otpSenderService.sendOtp(client, user);
This should be done through the decorator

2022-05-09 06:15 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/providers/google-authenticator-verify.provider.ts
> +          .create({...authenticator.allOptions()})
use directly .create(authenticator.allOptions())

2022-05-09 10:34 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    otp: process.env.OTP_SENDER_FUNCTION,
done

2022-05-09 10:34 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    const token = jwt.sign(codePayload, otpCache.clientSecret, {
done

2022-05-09 10:35 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/login.controller.ts
> +    return this.otpSenderService.sendOtp(client, user);
done

2022-05-09 10:35 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/providers/google-authenticator-verify.provider.ts
> +          .create({...authenticator.allOptions()})
done

2022-05-10 05:56 UTC, akshatdubeysf approved these changes

2022-05-10 05:59 UTC, merged