base code for clm-ocr adapter
sourcefuse/loopback4-microservice-catalog pull request #687
Opened 2022-04-19 09:06 UTC by kundan-sf

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-20 10:55 UTC, akshatdubeysf requested changes

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/Dockerfile
> +# Check out https://hub.docker.com/_/node to select a new base image
Not required for a package

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/README.md
> +
Put actual readme and description

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/package.json
> +    "name": "ocr-ocr",
proper name with sourceloop prefix

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/package.json
> +    }
add private: true

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/public/index.html
> +<!DOCTYPE html>
not required in a package

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/src/component.ts
> +        [RequestBindings.FetchProvider.key]: RequestProvider
should bind both the providers that are provided by the component?

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/src/keys.ts
> +export namespace RequestBindings {
Change the to something more specific

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/src/keys.ts
> +    export const Config = BindingKey.create < HttpClientInitOpts | null> ('sf.request.config');
formatting

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/src/opentelemetry-registry.ts
> +import {JaegerExporter} from '@opentelemetry/exporter-jaeger';
this file is not required in a package

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/src/providers/fetchClient/fetch-client.provider.ts
> +            ...jsonHeaders,
would throw error if jsonHeaders is undefined

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/src/providers/fetchClient/fetch-client.provider.ts
> +                if (req.method?.toUpperCase() === 'POST') {
only post requests allowed?

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/src/providers/fetchClient/fetch-client.provider.ts
> +    async get < T > (url: string, req: RequestInit = {}): Promise < T > {
what is the purpose of this then?

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/src/providers/index.ts
> +export * from './fetchClient';
folder name patter is incorrect

2022-04-20 10:55 UTC, akshatdubeysf commented on packages/contract-ocr/src/providers/types.ts
> +export type HttpClientInitOpts = {
these values appear in two files?

2022-04-25 10:51 UTC, kundan-sf commented on packages/contract-ocr/Dockerfile
> +# Check out https://hub.docker.com/_/node to select a new base image
Okay done in my latest PR

2022-04-29 09:16 UTC, akshatdubeysf commented on packages/loopback4-fetch-client/src/providers/fetchClient/fetch-client.provider.ts
> +import {inject, Provider, ValueOrPromise} from '@loopback/core';
why the same provider twice?

2022-05-04 06:22 UTC, closed without merging