feat(cache): initial code for cache mixin
sourcefuse/loopback4-microservice-catalog pull request #734
Opened 2022-04-25 13:35 UTC by barleendhaliwal

## Description

- This package contains a mixin which can be used to cache get responses using redis.
- Added Readme file on how to use it and other configuration required

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [x] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-04-27 14:24 UTC, samarpan-b requested changes
add test cases

2022-04-27 14:24 UTC, samarpan-b commented on packages/cache/src/mixins/cache.mixin.ts
> +        return await this.executeRedisCommand(`EVAL`, [
make sure this script is safe.

2022-04-27 14:24 UTC, samarpan-b commented on packages/cache/src/mixins/cache.mixin.ts
> +      return new Promise((resolve, reject) => {
why wrapped in promise ?

2022-04-27 14:24 UTC, samarpan-b commented on packages/cache/src/mixins/cache.mixin.ts
> +          this.cacheDataSource.connector.execute(
this is already a promise. No need to wrap

2022-04-27 14:24 UTC, samarpan-b commented on packages/cache/src/mixins/cache.mixin.ts
> +    executeRedisCommand(command: string, args: (string | number)[]) {
this must be async function

2022-04-27 14:24 UTC, samarpan-b commented on packages/cache/src/mixins/cache.mixin.ts
> +    async clearCache() {
mention return types please

2022-04-27 14:24 UTC, samarpan-b commented on packages/cache/src/mixins/cache.mixin.ts
> +    getKey(id?: ID, filter?: FilterExcludingWhere<M>, options?: Options) {
why this function ?

2022-04-28 08:09 UTC, barleendhaliwal commented on packages/cache/src/mixins/cache.mixin.ts
> +      return new Promise((resolve, reject) => {
If no callback function is given to execute function then it gives error : AssertionError [ERR_ASSERTION]: callback must be a function. Even if I give empty callback function and await the result will always be undefined.

2022-04-28 09:45 UTC, akshatdubeysf approved these changes

2022-04-28 09:45 UTC, akshatdubeysf commented on packages/cache/Dockerfile
> +# Check out https://hub.docker.com/_/node to select a new base image
purpose of docker file in a mixin repo?

2022-04-28 09:59 UTC, barleendhaliwal commented on packages/cache/Dockerfile
> +# Check out https://hub.docker.com/_/node to select a new base image
Deleted docker file

2022-04-29 09:22 UTC, barleendhaliwal commented
Added Unit test cases 
![Screenshot from 2022-04-29 14-49-16](https://user-images.githubusercontent.com/85155575/165918142-11a8978f-6f47-4cbc-aaaf-61e1a0fd3a5c.png)

2022-05-16 07:33 UTC, merged