feat(ocr-parser): Implementation for ocr-parser module
sourcefuse/loopback4-microservice-catalog pull request #757
Opened 2022-05-02 06:52 UTC by vijay-webApps

## Description
Implemented OCR-Parser to help finding and extracting contract clauses and details from a PDF document

Fixes #756 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-04 05:28 UTC, akshatdubeysf commented on packages/ocr-parser/README.md
> +# OcrParser
README?

2022-05-04 05:28 UTC, akshatdubeysf commented on packages/ocr-parser/projects/ocr-parser-lib/package.json
> +  "name": "ocr-parser-lib",
name should follow sourceloop convention

2022-05-04 05:28 UTC, akshatdubeysf commented on packages/ocr-parser/projects/ocr-parser-lib/package.json
> +  "name": "ocr-parser-lib",
name should follow sourceloop convention

2022-05-04 10:50 UTC, akshatdubeysf commented on packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/components/html-viewer/html-viewer.component.ts
> +        timerId = setTimeout(() => {
why not use timeout from rxjs?

2022-05-04 10:50 UTC, akshatdubeysf commented on packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/components/html-viewer/html-viewer.component.ts
> +      markedElements[0].scrollIntoView({ // scroll to first mark text
Can this be written in a better way than to hardcode getting first index with mark tag?

2022-05-04 10:50 UTC, akshatdubeysf commented on packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/ocr-parser.component.ts
> +  selector: 'sourceloop-ocrParser',
try to keep name hyphenated

2022-05-09 06:01 UTC, vijay-webApps commented on packages/ocr-parser/README.md
> +# OcrParser
Fixed

2022-05-09 06:02 UTC, vijay-webApps commented on packages/ocr-parser/projects/ocr-parser-lib/package.json
> +  "name": "ocr-parser-lib",
Fixed

2022-05-09 06:02 UTC, akshatdubeysf requested changes

2022-05-09 06:02 UTC, akshatdubeysf commented on packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/components/html-viewer/html-viewer.component.ts
> +    console.log(markedElements);
No console.log

2022-05-09 06:02 UTC, vijay-webApps commented on packages/ocr-parser/projects/ocr-parser-lib/package.json
> +  "name": "ocr-parser-lib",
Fixed

2022-05-09 06:02 UTC, vijay-webApps commented on packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/components/html-viewer/html-viewer.component.ts
> +        timerId = setTimeout(() => {
Fixed

2022-05-09 06:03 UTC, vijay-webApps commented on packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/components/html-viewer/html-viewer.component.ts
> +      markedElements[0].scrollIntoView({ // scroll to first mark text
Fixed

2022-05-09 06:03 UTC, vijay-webApps commented on packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/ocr-parser.component.ts
> +  selector: 'sourceloop-ocrParser',
Fixed

2022-05-10 13:03 UTC, vijay-webApps commented on packages/ocr-parser/projects/ocr-parser-lib/src/lib/ocr-parser/components/html-viewer/html-viewer.component.ts
> +    console.log(markedElements);
Fixed

2022-05-10 13:03 UTC, vijay-webApps commented on packages/ocr-parser/package.json
> +  "private": true,
Fixed

2022-05-11 05:13 UTC, akshatdubeysf approved these changes

2022-05-11 06:29 UTC, merged