Gh 759
sourcefuse/loopback4-microservice-catalog pull request #767
Opened 2022-05-05 06:00 UTC by kundan-sf

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-09 04:56 UTC, akshatdubeysf requested changes

2022-05-09 04:56 UTC, akshatdubeysf commented on packages/fetch-client/dist/component.js
> +"use strict";
Do not push the dist code

2022-05-09 04:57 UTC, akshatdubeysf commented
Fix description

2022-05-09 05:11 UTC, akshatdubeysf requested changes

2022-05-09 05:11 UTC, akshatdubeysf commented on packages/fetch-client/src/providers/fetch-client/fetch-client.provider.ts
> +        if (willSendRequest) {
What is this and how is it set? no mention in the readme?

2022-05-09 05:11 UTC, akshatdubeysf commented on packages/fetch-client/src/providers/fetch-client/fetch-client.provider.ts
> +        console.log(body)
use logger instead of console.log, also log such things only at certain log levels like debug

2022-05-09 05:11 UTC, akshatdubeysf commented on packages/fetch-client/src/providers/fetch-client/fetch-client.provider.ts
> +        console.log(JSON.stringify(response))
same

2022-05-09 05:11 UTC, akshatdubeysf commented on services/ocr-s3-service/.nyc_output/05682290-16bb-4fd8-869d-b93f79cec49f.json
> +{}
This should not be pushed, add it to gitignore

2022-05-09 05:48 UTC, kundan-sf commented on packages/fetch-client/src/providers/fetch-client/fetch-client.provider.ts
> +        if (willSendRequest) {
buildRequestArgs function will form complete http request based on the provided url and arguments.
No need to mention in the readme.

2022-05-09 05:56 UTC, akshatdubeysf requested changes

2022-05-09 05:56 UTC, akshatdubeysf commented on services/ocr-s3-service/src/controllers/ocr-object.controller.ts
> +  async asyncForEach<T>(
Why is this a method of OcrObjectController, should'nt it be external function

2022-05-09 05:56 UTC, akshatdubeysf commented on services/ocr-s3-service/src/controllers/ocr-object.controller.ts
> +    // eslint-disable-next-line
If you are using eslint-disable, use it with a specific rule and only if absolutely required.

2022-05-09 05:56 UTC, akshatdubeysf commented on services/ocr-s3-service/src/controllers/ocr-object.controller.ts
> +          'rakuten-clm-ml-dev',
should be picked from env

2022-05-09 05:56 UTC, akshatdubeysf commented on services/ocr-service/README.md
> +# ocr-service
readme?

2022-05-09 05:56 UTC, akshatdubeysf commented on services/ocr-s3-service/README.md
> +# ocr-s3-service
readme?

2022-05-09 05:56 UTC, akshatdubeysf commented on services/ocr-service/src/controllers/contract.controller.ts
> +    description: 'hcr file converter'
hocr?

2022-05-09 05:56 UTC, akshatdubeysf commented on services/ocr-service/src/controllers/contract.controller.ts
> +    @inject.getter(RequestBindings.FetchProvider) private readonly requestProvider: Getter<IRequest>,
same it something better like getRequestProvider.

2022-05-09 05:56 UTC, akshatdubeysf commented on services/ocr-service/src/controllers/contract.controller.ts
> +    const provider = await this.requestProvider();
here change it to requestProvider and the method call to getRequestProvider

2022-05-09 05:56 UTC, akshatdubeysf commented on services/ocr-service/src/controllers/contract.controller.ts
> +  // @post('/contract-file')
?????

2022-05-11 05:42 UTC, akshatdubeysf approved these changes

2022-05-11 05:44 UTC, merged