add the cache datasource for authentication base service
sourcefuse/loopback4-microservice-catalog pull request #770
Opened 2022-05-09 08:13 UTC by yeshamavani

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #626

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-10 07:48 UTC, akshatdubeysf requested changes

2022-05-10 12:24 UTC, yeshamavani commented on packages/cli/src/generators/datasource/templates/name.datasource.ts.tpl
> +<% if (project.serviceDependency === 'authentication-service') { -%>
done the changes for all the services

2022-05-11 06:01 UTC, akshatdubeysf commented on packages/cli/src/enum.ts
> +  [key in string]: string;
Also how is the case of multiple datasources handled?

2022-05-11 09:44 UTC, akshatdubeysf approved these changes

2022-05-11 09:45 UTC, merged