feat(user-tenant-service): adds user tenant service
sourcefuse/loopback4-microservice-catalog pull request #772
Opened 2022-05-10 10:28 UTC by sumiter92

## Description

Adds user tenant service

Fixes  #623 

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] Code conforms with the style guide

2022-05-11 08:46 UTC, akshatdubeysf requested changes

2022-05-11 08:46 UTC, akshatdubeysf commented on services/user-tenant-service/src/controllers/ping.controller.ts
> +    // try {
??

2022-05-12 10:46 UTC, sumiter92 commented on services/user-tenant-service/README.md
> +# @sourceloop/payment-service
done

2022-05-12 10:47 UTC, sumiter92 commented on services/user-tenant-service/src/controllers/ping.controller.ts
> +    // try {
removed

2022-05-17 08:59 UTC, akshatdubeysf commented on services/user-tenant-service/Dockerfile
> +FROM node:10-slim
Dockerfile not required in a component

2022-05-17 08:59 UTC, akshatdubeysf commented on services/user-tenant-service/package.json
> +    "migration.js",
This file is missing?

2022-05-17 08:59 UTC, akshatdubeysf commented on services/user-tenant-service/public/index.html
> +  <title>services</title>
user-tenant-service

2022-05-26 10:35 UTC, sumiter92 commented on services/user-tenant-service/public/index.html
> +  <title>services</title>
done

2022-05-26 10:35 UTC, sumiter92 commented on services/user-tenant-service/package.json
> +    "migration.js",
done

2022-06-02 14:34 UTC, akshatdubeysf approved these changes

2022-06-02 14:34 UTC, akshatdubeysf commented on services/user-tenant-service/src/controllers/ping.controller.ts
> +// import {get, HttpErrors, ResponseObject} from '@loopback/rest';
????

2022-06-02 14:34 UTC, akshatdubeysf commented on services/user-tenant-service/src/controllers/ping.controller.ts
> +// import {PgdbDataSource} from '../datasources';
???

2022-06-02 14:34 UTC, akshatdubeysf commented on services/user-tenant-service/src/controllers/ping.controller.ts
> +    // @inject('datasources.pgdb') private readonly dataSource: PgdbDataSource,
??

2022-06-02 14:34 UTC, akshatdubeysf commented on services/user-tenant-service/src/controllers/role-user-tenant.controller.ts
> +// import {PermissionKey} from '@local/rakuten-core';
??

2022-06-02 14:34 UTC, akshatdubeysf commented on services/user-tenant-service/src/controllers/user-group.controller.ts
> +    this.groupRepository.updateById(id, {
Why is this added manually?

2022-06-02 14:34 UTC, akshatdubeysf commented on services/user-tenant-service/src/controllers/user-group.controller.ts
> +    this.groupRepository.updateById(id, {
Use usermodifiablecrud repo

2022-06-02 14:34 UTC, akshatdubeysf commented on services/user-tenant-service/src/models/group.model.ts
> +// import {UserTenantGroupType} from '@local/rakuten-core';
??

2022-06-28 14:06 UTC, akshatdubeysf approved these changes

2022-06-30 10:30 UTC, sumiter92 commented on services/user-tenant-service/src/controllers/user-signup.controller.ts
> +export const PMS_SIGN_UP_RESPONSE_DESCRIPTION = 'Success Response.';
done , changed

2022-06-30 10:54 UTC, merged