feat(authentication-service): add MFA
sourcefuse/loopback4-microservice-catalog pull request #782
Opened 2022-05-13 09:59 UTC by AnkurBansalSF

created services and controllers for MFA

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-16 06:28 UTC, akshatdubeysf requested changes

2022-05-16 06:28 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/login.controller.ts
> +        throw new HttpErrors.Forbidden('User not verified by OTP');
Use the error keys, change message to be use second factor instead of OTP

2022-05-16 06:28 UTC, akshatdubeysf commented on services/authentication-service/src/providers/otp-sender.provider.ts
> +      // throw new HttpErrors.NotImplemented(`OtpSenderFn not implemented`);
??

2022-05-16 06:28 UTC, akshatdubeysf commented on services/authentication-service/src/component.ts
> +    this.providers[AuthCodeBindings.AUTH_CODE_WRITER_PROVIDER.key] =
What is the purpose of this when there is a code writer already?

2022-05-16 06:28 UTC, akshatdubeysf commented on services/authentication-service/src/services/mfa.service.ts
> +    if (strategyName === STRATEGY.LOCAL) {
This code should be dynamic na? For the first factor, there shouldn't be a condition for each strategy

2022-05-16 06:28 UTC, akshatdubeysf commented on services/authentication-service/src/services/mfa.service.ts
> +    const otp = await this.otpService.sendOtp(this.client, this.user.username);
It could attempt to send response twice, resulting in an error

2022-05-16 06:30 UTC, akshatdubeysf commented
fix the PR description as well

2022-06-02 15:09 UTC, akshatdubeysf requested changes

2022-06-02 15:09 UTC, akshatdubeysf commented on services/authentication-service/src/providers/otp.provider.ts
> +      const secret = authenticator.generateSecret();
Why is the secret generated here as well

2022-06-02 15:09 UTC, akshatdubeysf commented on services/authentication-service/src/services/otp.service.ts
> +    client: AuthClient | undefined,
Why not use ? operator?

2022-06-02 15:26 UTC, AnkurBansalSF commented on services/authentication-service/package.json
> +    "loopback4-authentication": "file:../../../../extensions/loopback4-authentication/loopback4-authentication-6.1.2.tgz",
added mfa property to payload interface, which is imported from auth package,
will raise a PR in auth-package

2022-06-02 15:26 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/types.ts
> +  qrCode?: string;
I'll remove it.

2022-06-02 15:30 UTC, AnkurBansalSF commented on services/authentication-service/src/providers/otp.provider.ts
> +      const secret = authenticator.generateSecret();
It is better to generate a new secret for every otp.
earlier, secret was stored in .env, which is not not apt. It will have security issues.

2022-06-06 11:29 UTC, akshatdubeysf requested changes

2022-06-06 11:29 UTC, akshatdubeysf commented on services/authentication-service/migrations/sqls/20210318100600-init-up.sql
> +	secret_key					 varchar(100)  ,
create a new migration

2022-06-07 06:54 UTC, akshatdubeysf approved these changes

2022-06-07 11:21 UTC, akshatdubeysf approved these changes

2022-06-17 07:19 UTC, akshatdubeysf requested changes

2022-06-17 07:19 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/otp.controller.ts
> +        return {userId};
Why is this API returning userId?

2022-06-17 07:19 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/otp.controller.ts
> +        return {userId};
why not just have a void 200 or 404 response

2022-06-17 07:19 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/otp.controller.ts
> +        return {userId};
and has a name like has-qr or something like that

2022-06-17 07:19 UTC, akshatdubeysf commented on services/authentication-service/src/modules/auth/otp.controller.ts
> +        return {userId};
or it could return the QR code

2022-06-20 06:36 UTC, AnkurBansalSF commented on services/authentication-service/src/modules/auth/otp.controller.ts
> +        return {userId};
done

2022-06-20 06:47 UTC, akshatdubeysf approved these changes

2022-06-21 11:13 UTC, akshatdubeysf commented
add test cases and example

2022-06-23 09:36 UTC, akshatdubeysf commented on services/authentication-service/src/__tests__/acceptance/otp.controller.acceptance.ts
> +  it('should have property isGenerated', async () => {
This covers only one case for each endpoint

2022-06-23 09:36 UTC, akshatdubeysf commented on services/authentication-service/src/__tests__/unit/mfa.provider.unit.ts
> +    it('checks if provider returns a function', async () => {
Add more useful tests

2022-06-23 09:37 UTC, akshatdubeysf commented
conflicts

2022-06-23 11:06 UTC, akshatdubeysf commented on services/authentication-service/src/__tests__/unit/modules-provider/otp-verify.provider.unit.ts
> +      expect(result).to.be.eql('Invalid Credentials');
Check for error type

2022-06-23 16:44 UTC, AnkurBansalSF commented on services/authentication-service/src/__tests__/acceptance/otp.controller.acceptance.ts
> +  it('should have property isGenerated', async () => {
fixed

2022-06-24 09:49 UTC, akshatdubeysf approved these changes

2022-06-24 09:50 UTC, merged