feat(cli): add new update command to cli
sourcefuse/loopback4-microservice-catalog pull request #835
Opened 2022-06-14 13:37 UTC by yeshamavani

gh-528

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-15 07:22 UTC, akshatdubeysf requested changes

2022-06-15 07:22 UTC, akshatdubeysf commented on packages/cli/src/generators/update/index.ts
> +    // const pkgDeps: {
???

2022-06-15 07:22 UTC, akshatdubeysf commented on packages/cli/src/generators/update/index.ts
> +    if (dependency !== tempDependency) {
return dependency !== tempDependency

2022-06-16 16:57 UTC, samarpan-b requested changes

2022-06-16 16:57 UTC, samarpan-b commented on packages/cli/src/generators/update/index.ts
> +    if (!this.fs.exists(join(this.destinationPath(), 'lerna.json'))) {
why is this needed at rot only ?

2022-06-16 16:57 UTC, samarpan-b commented on packages/cli/src/generators/update/index.ts
> +        await super.checkLoopBackProject();
await inside loop is simply bad programming

2022-06-16 16:57 UTC, samarpan-b commented on packages/cli/src/generators/update/index.ts
> +      for (const folder of folders) {
cant we reduce time complexity here ? Its O(n^2) right now. Try reducing it to O(n)

2022-06-16 16:57 UTC, samarpan-b commented on packages/cli/src/generators/update/index.ts
> +    return readdirSync(folderPath, {withFileTypes: true})
shouldn't we use async method here ?

2022-06-16 16:57 UTC, samarpan-b commented on packages/cli/src/generators/update/index.ts
> +      if (devDep && this._compare(tempDependency, devDep)) {
this._compare is invoked multiple times in the same fn. We can invoke once and use its value. This improves performance of the code.

2022-06-16 16:57 UTC, samarpan-b commented on packages/cli/src/types.ts
> +export interface DependencyType {
move types specific to sl update  command into separate file.

2022-06-17 14:44 UTC, yeshamavani commented on packages/cli/src/generators/update/index.ts
> +        await super.checkLoopBackProject();
we will need this as not able to achieve desired flow without it

2022-06-17 14:44 UTC, yeshamavani commented on packages/cli/src/generators/update/index.ts
> +      for (const folder of folders) {
actually the outer loop is fixed so it is like m*n = 3n,

2022-06-17 14:44 UTC, yeshamavani commented on packages/cli/src/generators/update/index.ts
> +      if (devDep && this._compare(tempDependency, devDep)) {
removed the function checking directly

2022-06-17 14:44 UTC, yeshamavani commented on packages/cli/src/types.ts
> +export interface DependencyType {
done

2022-07-04 06:08 UTC, akshatdubeysf approved these changes

2022-07-04 06:41 UTC, merged