fix(cli): add redis to facade
sourcefuse/loopback4-microservice-catalog pull request #836
Opened 2022-06-16 12:54 UTC by AnkurBansalSF

## Description

added a redis datasource to facades.

Fixes #792 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-17 06:54 UTC, yeshamavani requested changes

2022-06-18 08:23 UTC, AnkurBansalSF commented on packages/cli/src/generators/microservice/templates/src/application.ts.ejs
> +    console.log('my changes');
done

2022-06-18 08:23 UTC, AnkurBansalSF commented on packages/cli/src/generators/microservice/index.ts
> +      nameArr;
fixed

2022-06-20 06:48 UTC, akshatdubeysf commented on packages/cli/src/generators/microservice/index.ts
> +    if (this.projectInfo.facade) {
this.options.facade?

2022-06-20 08:38 UTC, AnkurBansalSF commented on packages/cli/src/generators/microservice/index.ts
> +    if (this.projectInfo.facade) {
done

2022-06-22 11:09 UTC, akshatdubeysf approved these changes

2022-06-23 07:57 UTC, merged