feat(feature-toggle): add new package for feature check decorator
sourcefuse/loopback4-microservice-catalog pull request #842
Opened 2022-06-21 09:55 UTC by yeshamavani

BREAKING CHANGE:
decorator removed from service and moved to package

gh-837

## Description

Created a new package extension for feature-toggle, that provides a method level decorator to check if feature is allowed or not.

Fixes #837 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## Checklist:

- [x] Performed a self-review of my own code
- [x] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [x] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-06-23 08:01 UTC, akshatdubeysf commented on packages/feature-toggle/README.md
> +# @sourceloop/feature-toggle
This still seems to be about the Feature Toggle Service

2022-07-01 07:40 UTC, yeshamavani commented on packages/core/package.json
>    "main": "dist/index.js",
by mistake, reverted!!

2022-07-01 08:08 UTC, akshatdubeysf requested changes

2022-07-01 08:08 UTC, akshatdubeysf commented on packages/feature-toggle/src/keys.ts
> +// }
??

2022-07-01 08:17 UTC, yeshamavani commented on packages/feature-toggle/src/keys.ts
> +// }
removed

2022-07-04 09:45 UTC, yeshamavani commented on packages/feature-toggle/src/__tests__/unit/README.md
> +# Unit tests
added.

2022-07-05 11:19 UTC, samarpan-b requested changes
should be generated using lb4 extension

2022-07-06 06:03 UTC, merged