notification user creation along with notification
sourcefuse/loopback4-microservice-catalog pull request #87
Opened 2020-10-23 18:58 UTC by mayank-SFIN571

## Description

Added logic to create a notification user entry along with notification creation.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2020-10-26 07:25 UTC, samarpan-b requested changes

2020-10-26 07:25 UTC, samarpan-b commented on services/notification-service/src/controllers/notification.controller.ts
> +      throw new HttpErrors.Forbidden(AuthErrorKeys.UnknownError);
why forbidden ? This is 422

2020-10-26 07:28 UTC, mayank-SFIN571 commented on services/notification-service/src/controllers/notification.controller.ts
> +      throw new HttpErrors.Forbidden(AuthErrorKeys.UnknownError);
Done

2020-10-27 04:31 UTC, samarpan-b approved these changes

2020-10-27 04:31 UTC, merged