docs(user-tenant-service): update the readme
sourcefuse/loopback4-microservice-catalog pull request #879
Opened 2022-07-06 10:55 UTC by sumiter92

## Description

update the readme with correct values.

Fixes #878 

## Type of change

- [ ] Readme update

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] Code conforms with the style guide

2022-07-06 15:33 UTC, akshatdubeysf requested changes

2022-07-06 15:33 UTC, akshatdubeysf commented on services/user-tenant-service/README.md
> +A Loopback Microservice primarily used for user-tenant implementation along with authenticcation service to set the api's for user-tenants.
spelling mistake

2022-07-06 15:33 UTC, akshatdubeysf commented on services/user-tenant-service/README.md
Change this as well

2022-07-11 10:15 UTC, sumiter92 commented on services/user-tenant-service/README.md
> +A Loopback Microservice primarily used for user-tenant implementation along with authenticcation service to set the api's for user-tenants.
done

2022-07-11 10:17 UTC, sumiter92 commented on services/user-tenant-service/README.md
done

2022-07-11 10:58 UTC, akshatdubeysf approved these changes

2022-07-11 10:59 UTC, closed without merging