docs(ReadMe): update readme file for sourceloop core
sourcefuse/loopback4-microservice-catalog pull request #970
Opened 2022-08-12 05:39 UTC by Surbhi-sharma1

gh-254

## Description
update readme file for sourceloop core

Fixes # (issue)
#254 
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-12 06:48 UTC, yeshamavani requested changes

2022-08-12 06:48 UTC, yeshamavani commented on packages/core/README.md
> +- Install the authentication service
Authentication?

2022-08-12 06:48 UTC, yeshamavani commented on packages/core/README.md
> +Adapters works as a bridge between two incompatible interfaces. This type of design pattern comes under structural pattern as this pattern combines the capability of two independent interfaces.
no need to explain adapter pattern, if you feel the need can give links to the article that explains it

2022-08-12 06:48 UTC, yeshamavani commented on packages/core/README.md
> +  this.providers = {[LOGGER.BINDINGS.LOG_ACTION.key]: LoggerProvider};
We bind the provider like this in application 
this.bind(LOGGER.BINDINGS.LOG_ACTION.toProvider(
      LoggerProvider,
    );

2022-08-12 06:48 UTC, yeshamavani commented on packages/core/README.md
> +  model Class i.e. createdBy and modifiedBy. The column names needed to be there in DB within that table are 'createdBy' and 'modifiedBy'.
?

2022-08-12 06:50 UTC, Surbhi-sharma1 commented on packages/core/README.md
> +Adapters works as a bridge between two incompatible interfaces. This type of design pattern comes under structural pattern as this pattern combines the capability of two independent interfaces.
ok

2022-08-24 06:11 UTC, Surbhi-sharma1 commented on packages/core/README.md
> +- Install the authentication service
changes done

2022-08-24 06:11 UTC, Surbhi-sharma1 commented on packages/core/README.md
> +  this.providers = {[LOGGER.BINDINGS.LOG_ACTION.key]: LoggerProvider};
done

2022-08-24 06:12 UTC, Surbhi-sharma1 commented on packages/core/README.md
> +  model Class i.e. createdBy and modifiedBy. The column names needed to be there in DB within that table are 'createdBy' and 'modifiedBy'.
changes done

2022-09-17 13:09 UTC, akshatdubeysf requested changes

2022-09-17 13:09 UTC, akshatdubeysf commented on packages/core/README.md
> +npm i @sourceloop/authentication-service
This seems wrong?

2022-09-17 13:09 UTC, akshatdubeysf commented on packages/core/README.md
> +A model describes business domain objects(shape of data) to be persisted in the database, for example, Customer, Address, and Order. It usually defines a list of properties with name, type, and other
You also need to describe the different models provided like BaseEntity, etc and the fields provided by them

2022-09-17 13:09 UTC, akshatdubeysf commented on packages/core/README.md
> +DefaultUserModifyCrudRepository -A repository Class which will provide CRUD operations for default user modifications.
DefaultUserModifyCrudRepository also add modified by fields, you need to mention that as well

2022-09-17 13:09 UTC, akshatdubeysf commented on packages/core/README.md
> +-import the sequence you want to use.for example,import ServiceSequence in your application component file.
Need to explain what is service sequence, what is secure sequence, etc

2022-09-19 07:52 UTC, Surbhi-sharma1 commented on packages/core/README.md
> +DefaultUserModifyCrudRepository -A repository Class which will provide CRUD operations for default user modifications.
ok sir

2022-09-19 08:09 UTC, Surbhi-sharma1 commented on packages/core/README.md
> +A model describes business domain objects(shape of data) to be persisted in the database, for example, Customer, Address, and Order. It usually defines a list of properties with name, type, and other
done

2022-10-03 11:16 UTC, Surbhi-sharma1 commented on packages/core/README.md
> +npm i @sourceloop/authentication-service
done

2022-10-03 11:16 UTC, Surbhi-sharma1 commented on packages/core/README.md
> +DefaultUserModifyCrudRepository -A repository Class which will provide CRUD operations for default user modifications.
done

2022-10-16 09:59 UTC, akshatdubeysf approved these changes

2022-10-16 10:02 UTC, merged